### ISSUE TITLE
Setting up the marble demo on my custom blockhcain from hyperledger fabric dev-net

### ISSUE THREAD

**Issue by shubhamvrkr** [IBM-Blockchain-Archive/marbles#10]
is it possible to run this marble demo on the hyperledger/fabric local network?

**Comment by mastersingh24** [comment]
https://github.com/IBM-Blockchain/marbles/blob/master/local_blockchain.md

**Comment by sufiyanghori** [comment]
yes you can, https://github.com/IBM-Blockchain/marbles/blob/master/tutorial_part1.md
