### ISSUE TITLE
Document points to external document with broken link

### ISSUE THREAD

**Issue by aeberbach** [IBM-Blockchain-Archive/marbles#104]
https://github.com/IBM-Blockchain/marbles/blob/v3.0/docs/use_local_hyperledger.md

refers to 

https://hyperledger-fabric.readthedocs.io/en/latest/ 

as Getting Started Instructions.

Linked documents instructs user to download https://logs.hyperledger.org/sandbox/vex-yul-hyp-jenkins-2/fabric-binaries/release.tar.gz which no longer exists.

Should link be changed so that document https://github.com/hyperledger/fabric/blob/master/docs/source/getting_started.rst is used instead, where the release.tar.gz is linked correctly?

**Comment by dshuffma-ibm** [comment]
well I'd prefer users use the `readthedocs` version since it has that handy left nav.  I can forward the broken link on to the correct team, but I don't see the `release.tar.gz` link in either doc? 

Which heading is it near or is it inside another linked page from: https://hyperledger-fabric.readthedocs.io/en/latest/getting_started.html

**Comment by aeberbach** [comment]
It is the instructions given for "Curl the artifacts and binaries" If I capture the link better - http://fabric-rtd.readthedocs.io/en/latest/getting_started.html - you can see it at the top of the page.

curl -L https://logs.hyperledger.org/sandbox/vex-yul-hyp-jenkins-2/fabric-binaries/release.tar.gz -o release.tar.gz 2> /dev/null;  tar -xvf release.tar.gz

points to a binary that isn't there. If readthedocs is preferred I guess they should fix it.

**Comment by nickgaski** [comment]
@aeberbach - you'll notice that you and David are showing two different URL's above.  The one that David has linked to is the production one; yours is a staging site that too many people have come across.  I am going to redirect the staging to avoid this confusion.  Follow the production link to find the tarball

**Comment by dshuffma-ibm** [comment]
fixed, marbles now points to the better instructions link

https://github.com/IBM-Blockchain/marbles/commit/c9dd762f0cfd45a7850086ae22067ce82921f902
