### ISSUE TITLE
Is there a separate way for deploying chaincode if the repository is on github.ibm.com?

### ISSUE THREAD

**Issue by suffiasameera** [IBM-Blockchain-Archive/marbles#105]
I'm trying to deploy a chaincode using the Swagger API on Bluemix. However, the path in the DeploySpec field happens to be a repository on github.ibm.com. Is it possible to deploy a chaincode if it lies in a github.ibm.com? Is there any separate procedure for it?

Can someone please help me out?

Thanks!

**Comment by dshuffma-ibm** [comment]
afraid not.  in fabric v0.6 when using the REST APIs chaincode must be on github.com.

**Comment by suffiasameera** [comment]
Thank you :)
