### ISSUE TITLE
Hosting marbles on Bluemix

### ISSUE THREAD

**Issue by rskumar45** [IBM-Blockchain-Archive/marbles#106]
Dear Team
Tutorials for Marbles It is mentioned :- 
(https://github.com/IBM-Blockchain/marbles/blob/v3.0/docs/tutorial_start_here.md)
4. Host Marbles
Last but not least we need marbles running somewhere.
Choose 1 option below:
•	Option 1: Host marbles on Bluemix - instructions
•	Option 2: Host marbles locally - instructions
 But in Option 1 Run Marbles on Bluemix, You have mentioned
 (https://github.com/IBM-Blockchain/marbles/blob/v3.0/docs/host_marbles_bluemix.md)  

Run Marbles on Bluemix (command line)
1.	Well to do this correctly you need to first run marbles locally.

Does that mean that one has to follow the steps in Host Marbles Locally ,
 even if you choose Bluemix ?  Why ?
https://github.com/IBM-Blockchain/marbles/blob/v3.0/docs/host_marbles_locally.md
Regards
Surya Kumar

**Comment by dshuffma-ibm** [comment]
Yes, but only b/c its a warm up to configure everything correctly.  

The chances that an avg user can run Marbles on Bluemix on their first try is about 0.5%.  There is quite a bit of configuration to do.  Trouble shooting marbles config settings when hosting on Bluemix will take 5-10 minutes per test.  That's far too long and it makes me worried the user may kill themselves before they realize an `http` should have been `https` or some other silly error.  Therefore the instructions suggest running it locally, where you can test those type of settings in around 5-10 seconds.

**Comment by rskumar45** [comment]
Thanks for your suggestion @dshuffma-ibm .

Yes. It is true , there are lot of configurations to be done, and many to be rerun after corrections.

Now my question in view of your suggestion 'running it locally', I have a query .

In Marbles - Demo, it is mentioned in '2. Get a Network', it is mentioned 
(https://github.com/IBM-Blockchain/marbles/blob/v3.0/docs/tutorial_start_here.md)

2.    Get a Network
Now we need a blockchain network.
Choose 1 option below:
•	Option 1: Create a network with the Bluemix IBM Blockchain Service - instructions
Refer document   Marbles demo  - Use Bluemix IBM Blockchain Service
•	Option 2: Use a locally hosted Hyperledger Network - instructions
Update: local instructions are a work in progress

In view of your suggestion  running it locally, should I follow above option 2 instead of option 1 as per the instruction ?

**Comment by dshuffma-ibm** [comment]
use option 1.  

there are different parts to this demo. the Marbles app, and the blockchain network.  see the gray boxes in the [diagram](https://github.com/IBM-Blockchain/marbles/blob/v3.0/README.md#application-communication-flow).

1. Marbles app - I highly recommend to run this one locally.  B/c you need to fiddle with the settings to get it communicating with your network.
2. Blockchain Network - I recommended to use the Bluemix service for this one.  There are no settings to fiddle with if you use the service.

**Comment by rskumar45** [comment]
Thanks @dshuffma-ibm 

Sorry for belated reply.
