### ISSUE TITLE
Deploy to Bluemix button no longer works

### ISSUE THREAD

**Issue by masterDev1985** [IBM-Blockchain-Archive/marbles#112]
There are two issues with the 'Deploy to Bluemix' button in the `v2.0` branch of this repository.

1. The button attempts to deploy the master branch of the repository.  The master branch only supports fabric v1.0.  This branch was not intended to be used with the Deploy to Bluemix button, due to how the service credentials currently work.  You used to be able to set the deployment branch with a `&branch=<git_branch>` parameter at the end of the button URL.  This does not appear to work anymore with the recent updates to Bluemix Devops.  The parameter is ignore and the master branch is always selected.  Try it for yourself: https://bluemix.net/deploy?repository=https://github.com/ibm-blockchain/marbles.git&branch=v2.0

I though the deployment process might have changed, but the Bluemix docs still indicate that I'm doing this the right way.  Check https://console.ng.bluemix.net/docs/develop/deploy_button.html to see for yourself.  Those docs will mention Jazzhub as the host for the deployment pipeline.

2. Bluemix Devops does not create an instance of the Blockchain service for the marbles v2.0 app to bind to.  It used to do so.  If use the Deploy to Bluemix button today, and then manually switch the pipeline branch to `v2.0` after the pipeline is created, you will get a deployment error like this:

```
Preparing to start the job...
Downloading build artifacts...
Target: https://api.ng.bluemix.net
Using manifest file /home/pipeline/f050da5b-b74d-442e-b072-6f6fb9784826/manifest.yml

Creating app marbles-20170608132817670 in org davery@us.ibm.com / space dev as davery@us.ibm.com...
OK

Creating route marbles-20170608132817670.mybluemix.net...
OK

Binding marbles-20170608132817670.mybluemix.net to marbles-20170608132817670...
OK

Uploading marbles-20170608132817670...
Uploading app files from: /home/pipeline/f050da5b-b74d-442e-b072-6f6fb9784826
Uploading 305.7K, 99 files

                             
Done uploading
OK
FAILED
Could not find service myblockchain to bind to marbles-20170608132817670

Finished: FAILED
```

It would appear that the `.bluemix/pipeline.yml` file is ignored by Devops

I'll leave it up to @dshuffma-ibm to decide what should be done about this, if anything.

**Comment by masterDev1985** [comment]
The workaround for these issues is to switch the build branch of the generated pipeline to `v2.0` from master and to create a starter plan instance of the blockchain service named `myblockchain` in the same space where you are deploying your app.  This appears to still work; the `manifest.yml` appears to still be functional.

**Comment by dshuffma-ibm** [comment]
the point of the `deploy to bluemix` buttons is to make it easy to:
1 - deploy the app's code
2 - create the services and bind

if it no longer does these things (and its not our fault) then, i'm voting for removing the buttons.

people can always follow our instructions to use bluemix normally

**Comment by masterDev1985** [comment]
Yeah that sounds reasonable to me.  I haven't ruled out the possibility that the button can work and we just need to configure things a little differently due to the devops updates.  However, until this theoretical process is documented, I don't think it's worth spending time on.  This feature is causing confusion right now, so it should be removed until we have a fix.

**Comment by dshuffma-ibm** [comment]
buttons removed
