### ISSUE TITLE
go get gopkg.in/ibm-blockchain/marbles.v2/chaincode/part2 doesn't exist

### ISSUE THREAD

**Issue by SandySun2000** [IBM-Blockchain-Archive/marbles#113]
https://github.com/IBM-Blockchain/marbles/blob/v1.0/chaincode/part2/part2_chaincode.go

This code didn't copy over to the v2.0 and V3.0. So when user click on 

the "Source Code" and "API Documentation" Buttons from http://gopkg.in/ibm-blockchain/marbles.v2/chaincode/part2, got page not found 404 error

**Comment by dshuffma-ibm** [comment]
I believe you made that link yourself, or got it from someone who edited one.  I can't find this exact link in my code on any branch `http://gopkg.in/ibm-blockchain/marbles.v2/chaincode/part2,`  but I think I know how this happened. If you look in the documentation for V1 it has the link in a very similar form, but its for **v1**.

![image](https://user-images.githubusercontent.com/16085295/27038004-b61c8090-4f57-11e7-9906-6c81a3bf23fa.png)
^^ this is correct and works.

You or someone may have edited this link for v2, but things have moved.

If you look in the v2 documentation:
![image](https://user-images.githubusercontent.com/16085295/27038028-ce733c2e-4f57-11e7-957d-8dd00baea11c.png)
^^ this is also correct and works.


If you stick to the v2 documentation, you should be good.

**Comment by SandySun2000** [comment]
Thanks for your quick reply, I will check where does the  http://gopkg.in/ibm-blockchain/marbles.v2/chaincode/part2 link come from?

**Comment by SandySun2000** [comment]
Matt already slack to you about where the doc links were broke. I will close the issue once you update the links from GUI
