### ISSUE TITLE
preflight check failed when deploying the project in Docker 

### ISSUE THREAD

**Issue by qianlizimu** [IBM-Blockchain-Archive/marbles#114]
I made some changes to the codes of Marbles Project to make users create some accounts and manage them. My project is at: https://github.com/qianlizimu/marbles/tree/v2.0. When I deployed the project in Docker in Mac, I got this error message:
 ……
New GET request for /apple-touch-icon.png
Error Handeler -  /apple-touch-icon.png
GET /apple-touch-icon.png 404 168.900ms - -
[ibc-js] Deploy Chaincode - Complete
[preflight check] 1: testing if chaincode is ready
[ibc-js] read - success: {jsonrpc: '2.0', result: { status:'OK' }, id:1493795194403 }
[preflight check] 1 :  failed, trying again
……

I don't know what caused this. How to solve this problem? Thanks!

**Comment by dshuffma-ibm** [comment]
the `preflight` part is expecting a query resp to return `null`.  it looks like yours is returning `status: OK`.  if that is part of your changes, then you should change the preflight code, or comment it out.  its in app.js line [277](https://github.com/IBM-Blockchain/marbles/blob/v2.0/app.js#L277).

the point of this code is to test if the chaincode is alive and healthy before moving on.

**Comment by dshuffma-ibm** [comment]
closing, inactivity.
