### ISSUE TITLE
Cannot find module 'stream-buffers' while installing chaincode on local fabric.

### ISSUE THREAD

**Issue by Tigermisu** [IBM-Blockchain-Archive/marbles#115]
Hello. I am following the tutorial in the readme to run the marbles v3 app, but I am getting stuck when it is time to install and instantiate the chaincode.

According to https://github.com/IBM-Blockchain/marbles/blob/v3.0/docs/install_chaincode_locally.md , all that is needed is to run the commands `node install_chaincode.js` and then `node instantiate_chaincode.js`. The first time I ran install_chaincode, it seemed to do so successfully, but when I ran the second command, it gave me an `Error: Cannot find module 'stream-buffers'`. I thought I had messed up somewhere, so I came back and restarted fabric ( sudo docker-compose -f docker-compose-marblesv3.yaml down and then follow the steps to get it up again) and this time it is giving me the error since the first step, the chain code install ( `node install_chaincode.js` ).

This is the stacktrace:

> user@computer:~/Desktop/ibmblockchain/marbles/scripts$ node install_chaincode.js 
info: Loaded config file /home/chris/Desktop/ibmblockchain/marbles/config/marbles3.json
info: Loaded creds file /home/chris/Desktop/ibmblockchain/marbles/config/blockchain_creds_docker.json
info: Returning a new winston logger with default configurations
module.js:471
    throw err;
    ^

> Error: Cannot find module 'stream-buffers'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/chris/Desktop/ibmblockchain/marbles/node_modules/fabric-client/lib/packager/Golang.js:23:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

What could be causing this error?

**Comment by mrshah-at-work** [comment]
I think you are running this on a Mac.

Can you run `npm install stream-buffers` and run those commands again?

**Comment by Tigermisu** [comment]
I am using Ubuntu 16.04 on a x64 machine, but the command did solve the issue, thank you!
