### ISSUE TITLE
Image tag of couchdb should be `hyperledger/fabric-couchdb` instead of `couchdb`

### ISSUE THREAD

**Issue by guoger** [IBM-Blockchain-Archive/marbles#116]
I think image tag of couchdb in `docker-compose-marblesv3.yaml` should be `hyperledger/fabric-couchdb` instead of `couchdb`.

**Comment by guoger** [comment]
Just tried `fabric-couchdb`, doesn't work... official `couchdb` works. Maybe we should exclude it from `download-images.sh`?

**Comment by mrshah-at-work** [comment]
The `fabric-couchdb` image was not published when marbles was written. Thus, we have `couchdb`. We will update it in the next refresh of marbles.

**Comment by guoger** [comment]
@mrshah-at-ibm great! Feel free to close the issue, or leave it open to keep track.
