### ISSUE TITLE
Host marbles locally 

### ISSUE THREAD

**Issue by rskumar45** [IBM-Blockchain-Archive/marbles#117]
Dear Team ,

When try to run gulp marbles1  I am getting the following error (msg attached)
[Error Msg gulb marbles1.docx](https://github.com/IBM-Blockchain/marbles/files/1084844/Error.Msg.gulb.marbles1.docx)

And as per the instruction in the error message , when I am unable to follow the steps mentioned in url
https://github.com/IBM-Blockchain/marbles/blob/v3.0/docs/use_bluemix_hyperledger.md

This is because as of now, there is no space in the Bluemix limited beta  to create a service.
Message file attached
[Msg No space in Limited Beta - Bluemix.docx](https://github.com/IBM-Blockchain/marbles/files/1084856/Msg.No.space.in.Limited.Beta.-.Bluemix.docx)

Is there a way out ?

Thanks & Regards
Surya Kumar

**Comment by dshuffma-ibm** [comment]
So the error message is showing you how to fix itself **if you are using the blockchain service** for your network.  But you don't have to use the service. Since the service has limited space, I'd encourage you to try the local hyperledger fabric setup.  This is [option 2](https://github.com/IBM-Blockchain/marbles#2-get-a-network) on the "2. Get a Network" step.  

In case you skipped some instructions you may want to look over [steps 0-4](https://github.com/IBM-Blockchain/marbles#0-setup-local-environment).

**Comment by rskumar45** [comment]
The Prerequisite for setting up the local hyperledger fabric setup says that:

These instructions have been tested on Ubuntu 14 and OSX. It may work for Windows 10 if you install the Bash shell. Note: Windows 7 users will need a virtual machine running some flavor of Linux.

And I am using Windows 7 system (64 bit- 4 GB RAM).  In view of this how do we proceed

**Comment by dshuffma-ibm** [comment]
Have you ever setup a virtual machine before? I'd recommend [Virtual Box](https://www.virtualbox.org/wiki/Downloads) with [Ubuntu 16](https://www.ubuntu.com/download/desktop).  

once that is setup you will bootup your virtual ubuntu via virtual box.  from there you can follow the marbles instructions.  make sure to run all the instructions/commands on the ubuntu machine, not your host (windows) machine.

**Comment by rskumar45** [comment]
I have Oracle VM in my system. Can I install Ubuntu on this VM ?
--------------------------------------------
On Tue, 6/20/17, dshuffma-ibm <notifications@github.com> wrote:

 Subject: Re: [IBM-Blockchain/marbles] Host marbles locally (#117)
 To: "IBM-Blockchain/marbles" <marbles@noreply.github.com>
 Cc: "Surya Kumar" <rskumar45@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Tuesday, June 20, 2017, 1:34 PM
 
 Have you ever setup a virtual
 machine before? I'd recommend Virtual
 Box with Ubuntu
 16.
 once that is setup you will bootup your virtual ubuntu
 via virtual box.  from there you can follow the marbles
 instructions.  make sure to run all the
 instructions/commands on the ubuntu machine, not your host
 (windows) machine.
 
 —
 You are
 receiving this because you authored the thread.
 Reply
 to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by dshuffma-ibm** [comment]
Maybe? I'm not sure what the difference is since Oracle also owns Virtual Box. If I were you I'd use Virtual Box since its very common, thus you can find lots of tutorials/help online.

**Comment by rskumar45** [comment]
To get decent performance what would you recomend for Minimum RAM to be allocated and size of the virtual disk.
I have already installed GoLang and Node.js in Windows .
Do I have to install these again in VM along with Docker and Docker compose?

**Comment by dshuffma-ibm** [comment]
128 GB of RAM and 1TB of disk

**Comment by dshuffma-ibm** [comment]
lol jk, 4GB of RAM and 20GB of disk would be plenty.  probably could go as low as 2GB of RAM.

and yes, you'd have to install golang, nodejs, docker, docker compose inside the VM.

**Comment by rskumar45** [comment]
I have installed Ubuntu 16.04 Xenial on VM.
I am trying to install Docker in Ubuntu using instructions given in 
https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/

On step 4 while following command to set up the stable repository , I am getting an error "IndexError : pieces[2].strip()"

The command used by me:-
sudo add-apt-repository \
"deb [arch=amd64] https://download.docker.com/linux/ubuntu/dists/$(lsb_release -cs)/stable"

I have attached the error message

![index out of range](https://user-images.githubusercontent.com/28441510/27687917-4f4ae2ec-5cf6-11e7-8f36-7654199b8a2c.PNG)
cef4ee0fc.PNG)

Please guide me to fix this error.

Thanks & Regards
Surya Kumar

**Comment by mrshah-at-work** [comment]
@rskumar45 we cannot address the docker installation issues. Please refer to https://github.com/docker/docker-ce
