### ISSUE TITLE
Instantiate Marbles fails with the error "Error: 3 = 2 "

### ISSUE THREAD

**Issue by freemanlatrell** [IBM-Blockchain-Archive/marbles#118]

**Comment by dshuffma-ibm** [comment]
you cannot use `marbles v3.0 chaincode` on a **beta** network.  though you can use the PR version. https://github.com/IBM-Blockchain/marbles/pull/89

a new marbles (v4.0) will be out sometime in the coming weeks that will work with beta fabric.

**Comment by dshuffma-ibm** [comment]
alternatively try this [marbles-beta.zip](https://github.com/IBM-Blockchain/marbles/files/1103708/marbles-beta.zip)

**Comment by dshuffma-ibm** [comment]
closing, inactivity
