### ISSUE TITLE
Issue bringing up Fabric-Orderer

### ISSUE THREAD

**Issue by hchawla1** [IBM-Blockchain-Archive/marbles#119]
In Step 3, Start our network:

All 7 containers ahow up in docker ps command  except fabric orderer.

$ docker ps
```CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS                                            NAMES
9ede1022bea5        hyperledger/fabric-peer   "peer node start -..."   4 seconds ago       Up 2 seconds        0.0.0.0:7056->7051/tcp, 0.0.0.0:7058->7053/tcp   peer1
d318a4ee37dc        hyperledger/fabric-peer   "peer node start -..."   4 seconds ago       Up 1 second         0.0.0.0:8056->7051/tcp, 0.0.0.0:8058->7053/tcp   peer3
eb37ff6b770b        hyperledger/fabric-peer   "peer node start -..."   5 seconds ago       Up 3 seconds        0.0.0.0:8051->7051/tcp, 0.0.0.0:8053->7053/tcp   peer2
b382380051fe        hyperledger/fabric-peer   "peer node start -..."   5 seconds ago       Up 3 seconds        0.0.0.0:7051->7051/tcp, 0.0.0.0:7053->7053/tcp   peer0
cc571d53ef02        hyperledger/fabric-ca     "sh -c 'fabric-ca-..."   7 seconds ago       Up 4 seconds        0.0.0.0:7054->7054/tcp                           ca_peerOrg1
e82e56f62adf        hyperledger/fabric-ca     "sh -c 'fabric-ca-..."   7 seconds ago       Up 5 seconds        0.0.0.0:8054->7054/tcp                           ca_peerOrg2
4723a0dd4a0d        couchdb                   "tini -- /docker-e..."   7 seconds ago       Up 5 seconds        0.0.0.0:5984->5984/tcp                           couchdb```

Error Log from orderer
$ sudo docker logs orderer0
```2017-06-27 01:22:07.465 UTC [SW_BCCSP] openKeyStore -> DEBU 001 KeyStore opened at [/etc/hyperledger/msp/orderer/keystore]...done
2017-06-27 01:22:07.465 UTC [BCCSP_FACTORY] initBCCSP -> DEBU 002 Initialize BCCSP [SW]
2017-06-27 01:22:07.465 UTC [msp] getPemMaterialFromDir -> DEBU 003 Reading directory /etc/hyperledger/msp/orderer/signcerts
2017-06-27 01:22:07.467 UTC [msp] getPemMaterialFromDir -> DEBU 004 Inspecting file /etc/hyperledger/msp/orderer/signcerts/ordererOrg1orderer1-cert.pem
2017-06-27 01:22:07.469 UTC [msp] getPemMaterialFromDir -> DEBU 005 Reading directory /etc/hyperledger/msp/orderer/cacerts
2017-06-27 01:22:07.470 UTC [msp] getPemMaterialFromDir -> DEBU 006 Inspecting file /etc/hyperledger/msp/orderer/cacerts/ordererOrg1-cert.pem
2017-06-27 01:22:07.472 UTC [msp] getPemMaterialFromDir -> DEBU 007 Reading directory /etc/hyperledger/msp/orderer/signcerts
2017-06-27 01:22:07.473 UTC [msp] getPemMaterialFromDir -> DEBU 008 Inspecting file /etc/hyperledger/msp/orderer/signcerts/ordererOrg1orderer1-cert.pem
2017-06-27 01:22:07.474 UTC [msp] getPemMaterialFromDir -> DEBU 009 Reading directory /etc/hyperledger/msp/orderer/admincerts
2017-06-27 01:22:07.476 UTC [msp] getPemMaterialFromDir -> DEBU 00a Inspecting file /etc/hyperledger/msp/orderer/admincerts/ordererOrg1-cert.pem
2017-06-27 01:22:07.477 UTC [msp] getPemMaterialFromDir -> DEBU 00b Reading directory /etc/hyperledger/msp/orderer/intermediatecerts
2017-06-27 01:22:07.478 UTC [msp] NewBccspMsp -> DEBU 00c Creating BCCSP-based MSP instance
2017-06-27 01:22:07.478 UTC [msp] GetLocalMSP -> DEBU 00d Created new local MSP
2017-06-27 01:22:07.478 UTC [msp] Setup -> DEBU 00e Setting up MSP instance OrdererMSP
2017-06-27 01:22:07.478 UTC [msp] newIdentity -> DEBU 00f Creating identity instance for ID &{OrdererMSP IDENTITY}
2017-06-27 01:22:07.478 UTC [msp] newIdentity -> DEBU 010 Creating identity instance for ID &{OrdererMSP IDENTITY}
2017-06-27 01:22:07.479 UTC [msp] newIdentity -> DEBU 011 Creating identity instance for ID &{OrdererMSP IDENTITY}
2017-06-27 01:22:07.480 UTC [SW_BCCSP] loadPrivateKey -> DEBU 012 Loading private key [9707908924f92bbaa5c8a6961c260dc4992ad2fd7043cccf3f3948ffbea989e1] at [/etc/hyperledger/msp/orderer/keystore/9707908924f92bbaa5c8a6961c260dc4992ad2fd7043cccf3f3948ffbea989e1_sk]...
panic: Unable to bootstrap orderer. Error reading genesis block file: open /etc/hyperledger/configtx/twoorgs.orderer.block: no such file or directory

goroutine 1 [running]:
panic(0xb06980, 0xc420274980)
	/opt/go/src/runtime/panic.go:500 +0x1a1
github.com/hyperledger/fabric/orderer/common/bootstrap/file.(*fileBootstrapper).GenesisBlock(0xc420274970, 0xc420274970)
	/opt/gopath/src/github.com/hyperledger/fabric/orderer/common/bootstrap/file/bootstrap.go:44 +0x233
main.main()
	/opt/gopath/src/github.com/hyperledger/fabric/orderer/main.go:142 +0x1d36```

**Comment by hchawla1** [comment]
I think setup_sdk.sh needs to be updated and point to master branch of https://github.com/hyperledger/fabric-sdk-node.git instead of v1.0.0-alpha

**Comment by hchawla1** [comment]
and all the images downloaded are alpha version for example -> x86_64-1.0.0-alpha

**Comment by hchawla1** [comment]
@dshuffma-ibm any updates on the latest version to be available and is there good documentation for migrating fabric from v0.6 to v1.0

**Comment by dshuffma-ibm** [comment]
marbles does not currently work on Beta nor RC1 fabric.  the marbles doc is pointing towards alpha images b/c thats the correct version of fabric for marbles v3.0

however there will be a marbles v4.0 very soon (days away) 
**[update you can use the 'experimental' branch for `v1.0.0-rc1` or `v1.0.0` fabric]**


i'm not aware of any documentation to help someone migrate from v0.6 to v1.0.  it is very different! more of a start over, than a migrate.

**Comment by sagar87966** [comment]
@hchawla1  i'm also facing the same issue .....
orderer      | 2017-07-25 04:08:00.085 UTC [msp] NewBccspMsp -> DEBU 00c Creating BCCSP-based MSP instance
orderer      | 2017-07-25 04:08:00.085 UTC [msp] GetLocalMSP -> DEBU 00d Created new local MSP
orderer      | 2017-07-25 04:08:00.085 UTC [msp] Setup -> DEBU 00e Setting up MSP instance DEFAULT
orderer      | 2017-07-25 04:08:00.085 UTC [msp] newIdentity -> DEBU 00f Creating identity instance for ID &{DEFAULT IDENTITY}
orderer      | 2017-07-25 04:08:00.085 UTC [msp] newIdentity -> DEBU 010 Creating identity instance for ID &{DEFAULT IDENTITY}
orderer      | 2017-07-25 04:08:00.085 UTC [msp] newIdentity -> DEBU 011 Creating identity instance for ID &{DEFAULT IDENTITY}
orderer      | panic: Unable to bootstrap orderer. Error reading genesis block file: open orderer.block: no such file or directory
orderer      |
orderer      | goroutine 1 [running]:
orderer      | panic(0xb06980, 0xc420269aa0)
orderer      |  /opt/go/src/runtime/panic.go:500 +0x1a1
orderer      | github.com/hyperledger/fabric/orderer/common/bootstrap/file.(*fileBootstrapper).GenesisBlock(0xc420269a80, 0xc420269a80)
orderer      |  /opt/gopath/src/github.com/hyperledger/fabric/orderer/common/bootstrap/file/bootstrap.go:44 +0x233
orderer      | main.main()
orderer      |  /opt/gopath/src/github.com/hyperledger/fabric/orderer/main.go:142 +0x1d36
-------did any one found solution over it

**Comment by dmsong2007** [comment]
i'm also facing the same issue. Is there a way around this?

panic: Unable to bootstrap orderer. Error reading genesis block file: read /var/hyperledger/orderer/orderer.genesis.block: is a directory

goroutine 1 [running]:
panic(0xb72100, 0xc420354460)
        /opt/go/src/runtime/panic.go:500 +0x1a1
github.com/hyperledger/fabric/orderer/common/bootstrap/file.(*fileBootstrapper).GenesisBlock(0xc420354440, 0xc420354440)
        /opt/gopath/src/github.com/hyperledger/fabric/orderer/common/bootstrap/file/bootstrap.go:44 +0x233
main.initializeBootstrapChannel(0xc4201d4d80, 0x1246880, 0xc420364180)
        /opt/gopath/src/github.com/hyperledger/fabric/orderer/main.go:162 +0x759
main.initializeMultiChainManager(0xc4201d4d80, 0x1243480, 0x128b4a8, 0xc4201fc520, 0x1)
        /opt/gopath/src/github.com/hyperledger/fabric/orderer/main.go:211 +0xa0
main.main()
        /opt/gopath/src/github.com/hyperledger/fabric/orderer/main.go:75 +0x392
dmsong@fabric1:~/e2e_cli$ panic: Unable to bootstrap orderer. Error reading genesis block file

my docker version
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false

docker images 
REPOSITORY                     TAG                              IMAGE ID            CREATED             SIZE
hyperledger/fabric-ca          latest                           c5632a55979c        9 hours ago         238MB
hyperledger/fabric-ca          x86_64-1.0.6-snapshot-da11ecb    c5632a55979c        9 hours ago         238MB
<none>                         <none>                           faea65efd85f        24 hours ago        1.26GB
hyperledger/fabric-testenv     latest                           c06fe616ef97        24 hours ago        1.4GB
hyperledger/fabric-testenv     x86_64-1.0.6-snapshot-a8728bc0   c06fe616ef97        24 hours ago        1.4GB
hyperledger/fabric-buildenv    latest                           b041df137e2b        24 hours ago        1.31GB
hyperledger/fabric-buildenv    x86_64-1.0.6-snapshot-a8728bc0   b041df137e2b        24 hours ago        1.31GB
hyperledger/fabric-orderer     latest                           fa1855168760        24 hours ago        151MB
hyperledger/fabric-orderer     x86_64-1.0.6-snapshot-a8728bc0   fa1855168760        24 hours ago        151MB
hyperledger/fabric-peer        latest                           411414158fda        24 hours ago        154MB
hyperledger/fabric-peer        x86_64-1.0.6-snapshot-a8728bc0   411414158fda        24 hours ago        154MB
hyperledger/fabric-javaenv     latest                           e621b2417e72        34 hours ago        1.41GB
hyperledger/fabric-javaenv     x86_64-1.0.6-snapshot-a8728bc0   e621b2417e72        34 hours ago        1.41GB
hyperledger/fabric-ccenv       latest                           4f116492db82        34 hours ago        1.28GB
hyperledger/fabric-ccenv       x86_64-1.0.6-snapshot-a8728bc0   4f116492db82        34 hours ago        1.28GB
hyperledger/fabric-tools       x86_64-1.0.5                     6a8993b718c8        5 days ago          1.33GB
hello-world                    latest                           f2a91732366c        3 weeks ago         1.85kB
hyperledger/fabric-baseimage   x86_64-0.3.2                     c92d9fdee998        3 months ago        1.26GB
hyperledger/fabric-baseos      x86_64-0.3.2                     bbcbb9da2d83        3 months ago        129MB
hyperledger/fabric-tools       latest                           ae6b0f53cb70        6 months ago        1.32GB
hyperledger/fabric-tools       x86_64-1.0.0-beta                ae6b0f53cb70        6 months ago        1.32GB
hyperledger/fabric-baseimage   x86_64-0.3.1                     9f2e9ec7c527        7 months ago        1.27GB
hyperledger/fabric-baseos      x86_64-0.3.1                     4b0cab202084        7 months ago        157MB

**Comment by pyraman** [comment]
I'm facing the same issue:
2018-04-03 04:06:33.641 UTC [orderer/common/server] initializeSecureServerConfig -> INFO 001 Starting orderer with TLS enabled
panic: <ctrl+b>**Unable to bootstrap orderer. Error reading genesis block file: read /var/hyperledger/orderer/orderer.genesis.block: is a directory**</ctrl+b>

goroutine 1 [running]:
github.com/hyperledger/fabric/orderer/common/bootstrap/file.(*fileBootstrapper).GenesisBlock(0xc420114490, 0xc42001406c)
	/opt/gopath/src/github.com/hyperledger/fabric/orderer/common/bootstrap/file/bootstrap.go:44 +0x1e4
github.com/hyperledger/fabric/orderer/common/server.initializeBootstrapChannel(0xc420388780, 0x135a260, 0xc42011a000)
	/opt/gopath/src/github.com/hyperledger/fabric/orderer/common/server/main.go:186 +0x5bd
github.com/hyperledger/fabric/orderer/common/server.initializeMultichannelRegistrar(0xc420388780, 0x1356a60, 0x13ba518, 0xc420116b98, 0x1, 0x1, 0x2f1)
	/opt/gopath/src/github.com/hyperledger/fabric/orderer/common/server/main.go:234 +0xa0
github.com/hyperledger/fabric/orderer/common/server.Start(0xcd744a, 0x5, 0xc420388780)
	/opt/gopath/src/github.com/hyperledger/fabric/orderer/common/server/main.go:94 +0x2c3
github.com/hyperledger/fabric/orderer/common/server.Main()
	/opt/gopath/src/github.com/hyperledger/fabric/orderer/common/server/main.go:74 +0x120
main.main()
	/opt/gopath/src/github.com/hyperledger/fabric/orderer/main.go:15 +0x20
