### ISSUE TITLE
Instantiate Chaincode w/Bluemix

### ISSUE THREAD

**Issue by rskumar45** [IBM-Blockchain-Archive/marbles#122]
Dear dshuffa

This wrt  Marbles Demo.

I was following the steps given in document "Install and Instantiate Chaincode w/Bluemix" (https://github.com/IBM-Blockchain/marbles/blob/v3.0/docs/install_chaincode.md)

 I was Instantiating the chaincode as per the steps below:-

1. As input argument  I entered 357.
2. From the "Channel" drop down, select our 1 and only channel (MarblesTrading Alliance)
3.  Then clicked the "Submit" button.

Screen shot attached
![image](https://user-images.githubusercontent.com/28441510/27761877-797207e2-5e83-11e7-8505-459ab00dee2f.png)

After refresh I got initial Instantiate screen back. I did not get the screen mentioned in the document Install and Instantiate Chaincode w/Bluemix.

Screen shot attached
![image](https://user-images.githubusercontent.com/28441510/27761889-dfd05b74-5e83-11e7-92d2-9b2af83d88fe.png)

Did I do anything wrong ?

Thanks & Regards
Surya Kumar

**Comment by rskumar45** [comment]
Dear @dshuffma-ibm 

Please help with above issue.

Thanks & Regards
Surya Kumar

**Comment by dshuffma-ibm** [comment]
@rskumar45 to get to the next screen follow the steps below the picture.  it will not refresh the page to the same one as in the picture. you have to follow the steps.

![image](https://user-images.githubusercontent.com/16085295/27969566-5424d15a-6319-11e7-9530-f38cf4c561f8.png)


i'll try to tweak the wording

**Comment by rskumar45** [comment]
Thanks @dshuffma-ibm .

It worked .

Regards
Surya Kumar
