### ISSUE TITLE
Error when starting orderer - Failed to initialize local MSP: admin 0 is invalid

### ISSUE THREAD

**Issue by ravengit** [IBM-Blockchain-Archive/marbles#126]
If I follow the instructions in https://github.com/IBM-Blockchain/marbles/blob/v3.0/docs/use_local_hyperledger.md and use the downloadable docker images, everything works fine and I'm able to run the Marbles app without any problem.

But instead of using those downloadable docker images, if I compile/make those docker images  (using "make docker") from https://github.com/hyperledger/fabric. I get this error when starting the orderer:

```
orderer0    | 2017-07-12 04:38:12.817 UTC [orderer/main] initializeLocalMsp -> CRIT 01b Failed to initialize local MSP: admin 0 is invalid, validation error Could not obtain certification chain, err A CA certificate cannot be used directly by this MSP
```

Can someone give me some pointers? Thanks!

**Comment by dshuffma-ibm** [comment]
you probably want to ask this on [hyperledger's Jira](https://jira.hyperledger.org).  I doubt anyone here knows the answer.
