### ISSUE TITLE
Install chaincode certificate error - experimental branch

### ISSUE THREAD

**Issue by cassio-rossi** [IBM-Blockchain-Archive/marbles#128]
I'm trying to use the **experimental** branch to run the marbles example on my local machine (everything local) and, after running the command _node install_chaincode.js_, I'm getting the following error:

```
error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: The creator certificate is not valid, err The supplied identity is not valid, Verify() returned x509: certificate signed by unknown authority
    at /Users/cassiorossi/Desktop/Development/Projects/Blockchain/demo/marbles/node_modules/grpc/src/node/src/client.js:434:17
error: [fcw] Failed to obtain endorsement for transaction. code=2, 
error: [fcw] Error in install catch block object code=2, 
```

Everything else went Ok (except I have to change the key orgs, from '**PeerOrg1**' to '**Org1MSP**' - to find the correct org otherwise, I got the message "Cannot find org.")

What could be wrong? How to generate the "correct" certificate? I tried to use Bluemix but V1 is not available yet.

Please help. Thanks, Cassio

**Comment by dshuffma-ibm** [comment]
try the new setup instructions + new v4.0 marbles

**Comment by dshuffma-ibm** [comment]
closing, inactivity
