### ISSUE TITLE
Cannot find module 'stream-buffers'

### ISSUE THREAD

**Issue by hintcnuie** [IBM-Blockchain-Archive/marbles#129]
When running command 
  gulp marbels3

it throws error message as below, does anyone face this before?   thanks

log:
   

> marbles/config/blockchain_creds_docker.json
[10:50:19] Starting 'build-sass'...
[10:50:19] Finished 'build-sass' after 2.91 ms
info: Returning a new winston logger with default configurations
module.js:471
    throw err;
    ^

Error: Cannot find module 'stream-buffers'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/chenzhengwei/Documents/BlockChain/applications/marbles/node_modules/fabric-client/lib/packager/Golang.js:23:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by hintcnuie** [comment]
well, fixed this by:

> `npm install stream-buffers`
![snip20170728_12](https://user-images.githubusercontent.com/4081542/28700608-6db7fce4-7383-11e7-8990-824309fed157.png)

`gulp marbles3`
`[10:55:21] Using gulpfile ~/Documents/BlockChain/applications/marbles/gulpfile.js`
`[10:55:21] Starting 'start_marbles3'...`

`[International Marbles Trading Consortium] 1`

`[10:55:21] Finished 'start_marbles3' after 147 μs`
`[10:55:21] Starting 'build-sass'...`
`[10:55:21] Finished 'build-sass' after 13 ms`
`[10:55:21] Starting 'watch-sass'...`
`[10:55:21] Finished 'watch-sass' after 12 ms`
`[10:55:21] Starting 'watch-server'...`
`[10:55:21] Finished 'watch-server' after 7.02 ms`
`[10:55:21] Starting 'server'...`
`info: Loaded config file /Users/c/Documents/BlockChain/applications/marbles/config/marbles3.json`
`info: Loaded creds file /Users/c/Documents/BlockChain/applications/marbles/config/blockchain_creds_docker.json`
`info: Returning a new winston logger with default configurations`
`info: Loaded config file /Users/c/Documents/BlockChain/applications/marbles/config/marbles3.json`
`info: Loaded creds file /Users/c/Documents/BlockChain/applications/marbles/config/blockchain_creds_docker.json`
`debug: cache busting hash js 1501210522279 css 1501210522279`
------------------------------------------ Server Up - localhost:3001 ------------------------------------------
------------------------------------------ Websocket Up ------------------------------------------
`warn: no tls cert or path found in creds json: /Users/c/Documents/BlockChain/applications/marbles/config/blockchain_creds_docker.json`
`warn: no tls cert found for cas in creds json: /Users/c/Documents/BlockChain/applications/marbles/config/blockchain_creds_docker.json`
`warn: no tls cert or path found in creds json: /Users/c/Documents/BlockChain/applications/marbles/config/blockchain_creds_docker.json`
`warn: no tls cert found for orderers in creds json: /Users/c/Documents/BlockChain/applications/marbles/config/blockchain_creds_docker.json`
`warn: no tls cert or path found in creds json: /Users/c/Documents/BlockChain/applications/marbles/config/blockchain_creds_docker.json`
`warn: no tls cert found for peers in creds json: /Users/c/Documents/BlockChain/applications/marbles/config/blockchain_creds_docker.json`

`debug: Detected that we have NOT launched successfully yet`
`debug: Open your browser to http://localhost:3001 and login as "admin" to initiate startup` 






  Can the gulp script avoid this issue next time for new users?

**Comment by dshuffma-ibm** [comment]
what version of marbles are you using? the v3.0 branch has stream-buffers in the [package.json](https://github.com/IBM-Blockchain/marbles/blob/v3.0/package.json#L20)

**Comment by dshuffma-ibm** [comment]
closing, inactivity
