### ISSUE TITLE
error: [Chain.js]: Peer with URL grpc://localhost:7051 already exists

### ISSUE THREAD

**Issue by GemstoneZheng** [IBM-Blockchain-Archive/marbles#130]
I get this response when I execute the  script "node instantiate_chaincode.js",
how to fix it ?
Has anyone come across this situation?

**Comment by rafizanbaharum** [comment]
Yup I'm seeing the same thing. But the marble app is working correctly
error: [Chain.js]: Peer with URL grpc://localhost:7051 already exists

**Comment by GemstoneZheng** [comment]
Ok, Thank you. I'll try again
