### ISSUE TITLE
Issue compiling the blockchain

### ISSUE THREAD

**Issue by SBerda** [IBM-Blockchain-Archive/marbles#134]
Hi,
I'm currently working on the marbles hyperledger project
When I  want to compile the blockchain with  « go build » , I have the following errors :
```
./read_ledger.go:108: assignment count mismatch: 3 = 2
./read_ledger.go:128: assignment count mismatch: 3 = 2
./read_ledger.go:178: assignment count mismatch: 3 = 2
./read_ledger.go:232: assignment count mismatch: 3 = 2
```
The file producing the error is located in :
https://github.com/IBM-Blockchain/marbles/tree/v3.0/chaincode/src/marbles

The line that making the error is the following :
queryKeyAsStr, queryValAsBytes, err := ownersIterator.Next()

I'm having the same issue as this guy on this webpage (at the end):
https://github.com/renatoaguimaraes/hyperledger-fabric-chaincode-v1
I have tried to contact him to ask him but i'm waiting his answer..

Do you guys have any idea ?

Thank you

Best regards

Simon

**Comment by dshuffma-ibm** [comment]
You cannot use the marbles chaincode on the v3.0 branch with fabric v1.0.0. You can however use the [experimental branch](https://github.com/IBM-Blockchain/marbles/tree/experimental) w/ fabric v1.0.0.

**Comment by SBerda** [comment]
Thanks, that fixed it :)
