### ISSUE TITLE
How can I instantiate a chaincode after stoping/starting without reseting data

### ISSUE THREAD

**Issue by lucasthompsonamg** [IBM-Blockchain-Archive/marbles#135]
What I have to do when I reboot my machine, How can I bring everything up again without lost everything?

I tried to 
```
cd ../basic-network
    ./stop.sh
```
After machine goes on
```
cd ../basic-network
    ./start.sh
node install_chaincode.js
node instantiate_chaincode.js
```

gulp marbles_local

But in instantiate_chaincode looks like by default reset the onwers and previews data, could you help?

Thanks
Lucas

**Comment by mrshah-at-work** [comment]
@lucasthompsonamg I looked at the https://github.com/hyperledger/fabric-samples/blob/release/basic-network/start.sh script. The first thing it does is, `docker-compose -f docker-compose.yml down` which deletes all the containers of the existing network.

Can you try to remove that line from the start.sh script and try again?

**Comment by dshuffma-ibm** [comment]
closing, inactivity
