### ISSUE TITLE
typo error  'url' in docs/use_local_hyperledger.md

### ISSUE THREAD

**Issue by hintcnuie** [IBM-Blockchain-Archive/marbles#138]
In docs/use_local_hyperledger.md,  there is a line :

`url -sSL https://goo.gl/iX9dek | sudo bash`

I think it should be 
`curl -sSL https://goo.gl/iX9dek | sudo bash`

Is it

**Comment by dshuffma-ibm** [comment]
thanks, [fixed](https://github.com/IBM-Blockchain/marbles/commit/ad23b0e96fea53e55537ae010400317d83ef1463#diff-0ae7bea2078e652658cb9b22199783deR31)
