### ISSUE TITLE
fs.access error

### ISSUE THREAD

**Issue by bd37** [IBM-Blockchain-Archive/marbles#14]
When I start node app.js, I receive the following error. How can I fix this?

```
    fs.access(unzip_cc_dest, cb_file_exists);                                       //check if files exist ye
       ^
```

TypeError: Object #<Object> has no method 'access'
    at cb_ready (/root/marbles/node_modules/ibm-blockchain-js/index.js:181:6)
    at /root/marbles/node_modules/ibm-blockchain-js/lib/helper.js:44:4
    at Object.oncomplete (fs.js:107:15)

**Comment by dshuffma-ibm** [comment]
Update node to v4.4.3+ (v0.12.0 should work as well but its no longer a LTS version), and then update npm with:

```
npm update npm
```

**Comment by dshuffma-ibm** [comment]
@bd37 did it work?  if so please close this issue.
