### ISSUE TITLE
Getting error when i run node install_chaincode.js

### ISSUE THREAD

**Issue by nirmal1988** [IBM-Blockchain-Archive/marbles#141]
Using win10, 64bit and trying marbles V4
Getting error when i run node install_chaincode.js
![image](https://user-images.githubusercontent.com/15016894/29919613-8b329876-8e39-11e7-9e7a-eb5761bae22a.png)

docker ps
![image](https://user-images.githubusercontent.com/15016894/29919530-3d5310e0-8e39-11e7-900f-05aee2d8c74f.png)

docker version
![image](https://user-images.githubusercontent.com/15016894/29919572-60a6ee36-8e39-11e7-8c38-61ea141cfd73.png)

**Comment by mrshah-at-work** [comment]
I see that install chaincode request is going to the CA `localhost:7051` instead of the peer.. Can you update it to the peer `localhost:7056` or `localhost:7058` depending on which one is the API port and the other one is the event port?

**Comment by dhyey20** [comment]
@mrshah-at-ibm It is actually going to peer `peer0.org1`.
@nirmal1988 Can you also share the peer logs, do you see any error there?

**Comment by nirmal1988** [comment]
Followed all the steps again in another VM and everything worked!!!!

Thanks @mrshah-at-ibm n @dhyey20

**Comment by knagware** [comment]
Hi, 
@mrshah,i am trying to install chaincode to cluster running on kubernetes inside Bluemix as container service, but it's failed due to peer key not found,, I think script trying to deploy localy... Do you have install chain code. Sh for kubernetes

**Comment by mrshah-at-work** [comment]
@knagware I have answered your question at https://github.com/IBM-Blockchain/ibm-container-service/issues/5.. You have to use your cluster's public IP address and the ports exposed by the services to communicate with the nodes.
