### ISSUE TITLE
tr1 header issue

### ISSUE THREAD

**Issue by tublu123** [IBM-Blockchain-Archive/marbles#142]
while running npm install -g composer-cli

getting this issue

 CXX(target) Release/obj.target/native/src/hashtable.o
In file included from ../src/hashtable.cpp:1:
../src/hashtable.h:7:10: fatal error: 'tr1/unordered_map' file not found
#include <tr1/unordered_map>
         ^
1 error generated.
make: *** [Release/obj.target/native/src/hashtable.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 16.6.0
gyp ERR! command "/usr/local/Cellar/node/8.4.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /usr/local/lib/node_modules/composer-cli/node_modules/hashtable
gyp ERR! node -v v8.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hashtable@2.0.2 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hashtable@2.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kaustavr/.npm/_logs/2017-08-31T12_39_07_844Z-debug.log

As already discussed Mac OS new version does not have tr1 header.
Any ways it can be solved ????

**Comment by mrshah-at-work** [comment]
This issue is not regarding marbles, correct?

Anyway, try using node version 6.x.x.

**Comment by dshuffma-ibm** [comment]
@tublu123 I'm afraid this repo can only help with marbles questions and some general hyperledger fabric questions.  `composer` related issues should be brought up [here](https://hyperledger.github.io/composer/support/support-index.html)


to be clear `composer-cli` is not required for `marbles`

**Comment by tublu123** [comment]
ok thanx

**Comment by tublu123** [comment]
yes ...  i am trying to install composer cli ... but getting fatal error
for tr1 header.


On 31 Aug 2017 6:43 p.m., "Mihir Shah" <notifications@github.com> wrote:

This issue is not regarding marbles, correct?

Anyway, try using node version 6.x.x.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/IBM-Blockchain/marbles/issues/142#issuecomment-326291300>,
or mute the thread

**Comment by tublu123** [comment]
ok... thanx
