### ISSUE TITLE
Marbles Request timed out 

### ISSUE THREAD

**Issue by YvesHarrison** [IBM-Blockchain-Archive/marbles#145]
Hi, I used Docker for Windows 10, and ran the Marbles v2.0 on local blockchain network. I changed value of in core.yaml to 30000 and rebuild the image. I also changed line near line 233 in app.js into:
options: {
									quiet: true, 
									tls: detect_tls_or_not(peers), 							
									maxRetry: 1,										
									timeout: 300000 																
	}
But I still meet with the problem mentioned below:
 [ibc-js] Deploy Chaincode - Starting
[ibc-js]        function: init , arg: [ '99' ]

         Waiting...
[ibc-js] deploy - failure: 408
! looks like a deploy error, holding off on the starting the socket
 { name: 'deploy() error',
  code: 408,
  details: 'Request timed out' }

**Comment by dshuffma-ibm** [comment]
Ah sorry, but we are not supporting Marbles 2.0 anymore. Its provided as is.

I would encourage you to upgrade to v1.0 Fabric which works with Marbles 4.0.  To be clear you would have to update the hyperledger fabric you are running locally, and the marbles application code.

**Comment by YvesHarrison** [comment]
@dshuffma-ibm thanks
