### ISSUE TITLE
Install and Instantiate Chaincode w/Local Hyperledger Fabric

### ISSUE THREAD

**Issue by rodrigoribeiro87** [IBM-Blockchain-Archive/marbles#146]
Hello,
I have followed this tutorial (https://github.com/IBM-Blockchain/marbles/blob/v4.0/README.md#installchaincode) step by step, at 
step 3. Install and Instantiate Chaincode,
Option 2: Install and instantiate chaincode with the SDK locally 
when I try to install chaincode using prebaked crypto for a locally hosted Hyperledger Fabric Network, I always have the below error:

error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: Failed to deserialize creator identity, err The supplied identity is not valid, Verify() returned x509: certificate signed by unknown authority (possibly because of "x509: ECDSA verification failure" while trying to verify candidate authority certificate "ca.org1.example.com")
    at /home/cielolabs/fabric-samples/marbles/node_modules/grpc/src/node/src/client.js:434:17
error: [fcw] Failed to obtain endorsement for transaction. code=2, 
error: [fcw] Error in install catch block object code=2, 

I started to follow the steps to create the certificate and public key files manually, but Im not sure if this is the problem. 

Do you have some clue to solve it?

Thanks,

![captura de tela de 2017-09-12 11-03-36](https://user-images.githubusercontent.com/19937707/30329898-12867a76-97aa-11e7-9633-78aab87c5a47.png)

**Comment by dshuffma-ibm** [comment]
The Peer doesn't trust you. It doesn't like the crypto material you are providing. This _could_ be because the network or marbles is not up to date.  The certificates were updated about 7 days ago.

I would recommend deleting your local network containers/images, and do a fresh pull on `fabric-samples` and `marbles` to make sure you are up to date.

let me know if that doesn't work

**Comment by rodrigoribeiro87** [comment]
Wowww tks =D
Ive got it!
I deleted everything and started all over... Now its working!
Tks

**Comment by dshuffma-ibm** [comment]
Great!
