### ISSUE TITLE
Setup more than one company running locally

### ISSUE THREAD

**Issue by joaquimpedrooliveira** [IBM-Blockchain-Archive/marbles#148]
How can I configure more than one company running the example locally?

**Comment by dshuffma-ibm** [comment]
I'm assuming you are using the basic local network setup. This complicates things b/c the default setup only provides one set of crypto material, one peer and one CA. However you can reuse the crypto/peers/etc if you only want to cosmetically explore what two companies using marbles would look like. 

Ok so to fudge it, we just need two marble apps using the same resources.  We need to copy the  `marbles_local.json` file and create a new one. name it `marbles_local_2.json`. In this file change:
  - change the `company` field to your new company
  - change the `port` field to 3002

Next edit `gulpfile.js` add these lines near the bottom 

```js
gulp.task('marbles_local_2', ['env_local', 'watch-sass', 'watch-server', 'server']);
gulp.task('env_local', function () {
	env['creds_filename'] = 'marbles_local_2.json';
});
```

Run the first marbles app with `gulp marbles_local`, and run the second app with `gulp marbles_local_2`.

That's it.

.

Just want to repeat that the instructions above are not appropriate for a real setup.  Multiple companies would not share peers/crypto.  This is the quick way.  Doing it proper would include the steps above **and** you need to create a new `blockchain_creds_local.json` file.  It would point to different peers/CAs/crypto.

**Comment by joaquimpedrooliveira** [comment]
@dshuffma-ibm , thanks for your prompt response. I'm using the basic local network setup and just want to create another company for demo purposes.

Duplicating `marbles_local.json` and adding new tasks to `gulpfile.js` worked like a charm. However, when I try to transfer marbles from one company to another, I get the following message:
`error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: The company 'United Marbles' cannot authorize transfers for 'Company2'.)`.

I believe I need to adjust something else, maybe the endorsment policy. Am I right?

**Comment by joaquimpedrooliveira** [comment]
Ooops, I just realized that the `write_ledger.go` chaincode file has the following restriction:
 ```go 
// check authorizing company
	if res.Owner.Company != authed_by_company{
		return shim.Error("The company '" + authed_by_company + "' cannot authorize transfers for '" + res.Owner.Company + "'.")
	}
```

So I'm assuming it is a business rule. Is it right?

**Comment by dshuffma-ibm** [comment]
correctamundo! that is the example rule where chaincode itself can reject a request.  so there is nothing _wrong_ with the request, its just against the rules.

note that you can trade marbles **into** another company, you just can't take them out.

**Comment by joaquimpedrooliveira** [comment]
Ok, @dshuffma-ibm ! Thank you very much for your help!

**Comment by mastreips** [comment]
I needed to change the env_local value to env_local2 for this to work correctly - otherwise it would gulp would keep launching company 2 - 

`gulp.task('marbles_local_2', ['env_local2', 'watch-sass', 'watch-server', 'server']);
gulp.task('env_local2', function () {
	env['creds_filename'] = 'marbles_local_2.json';
});`

**Comment by KrupaSM** [comment]
I am trying to create two example company running locally. I followed those steps mentioned above. Transaction is happening when i transfer marbles from Company_two to United Marble, But when i do transfer from United Marble to Company_two it's showing following error
Blockchain network error - The company 'Company_two' cannot authorize transfers for 'United Marble'

**Comment by dshuffma-ibm** [comment]
@KrupaSM that is intended, you are seeing the chaincode logic working.  it is specifically coded to prevent such a trade.  its just an example, if you want to change that behavior you can modify the [chaincode](https://github.com/IBM-Blockchain/marbles/blob/master/chaincode/src/marbles/write_ledger.go#L291)
(also remember to install/instantiate your new version of chaincode)
