### ISSUE TITLE
install and instantiate fail

### ISSUE THREAD

**Issue by belltanellc** [IBM-Blockchain-Archive/marbles#149]
I changed the install and instantiate scripts to chaincode_id=marbles and all was well.

scripts/install and instantiate use chaincode_id=marbles01 but config/blockchain_creds_local has = marbles

**Comment by dshuffma-ibm** [comment]
so whats the issue exactly?

if you change the chaincode id, you will want to also change it in the blockchain_creds_local.json file.

a screen shot or dump of the logs you are seeing would help.

**Comment by magicliang** [comment]
I met same issue here.

Apparently, the ui bootstrap needs to find a chaincode named "marbles".

But the install_chaincode.js and instantiate_chaincode.js install and instantiate a chaincode named "marbles01".

User has to change blockchain_creds_local's content to let ui try to find "marbles01" as target chaincode.

In summary, current branch of this repo has chaincode name inconsistency, a smoking test/regression test can fix that, I wonder why you didn't meet this.

**Comment by dshuffma-ibm** [comment]
@magicliang thanks, fixed the scripts to use `marbles` instead of `marbles01` https://github.com/IBM-Blockchain/marbles/commit/c222be76eb32cc8da42bb71f4e2aa3ba7883bdf9
