### ISSUE TITLE
Gulp error

### ISSUE THREAD

**Issue by himanshutyagi36** [IBM-Blockchain-Archive/marbles#15]
Hi, 
I am trying to setup marbles with my bluemix. I have deployed the app directly to bluemix and now following the instructions. But I'm getting a "Unhandled error event" in 'events.js' line 141,  error on gulp command. Can anyone please explain what I might be doing wrong.
<img width="391" alt="screen shot 2016-06-15 at 11 44 31 am" src="https://cloud.githubusercontent.com/assets/5171506/16086775/b2920a5c-32ee-11e6-9612-0914e27a2afe.png">

**Comment by dshuffma-ibm** [comment]
there was an issue with OSX and our gulpfile.  I just pushed a change to fix it https://github.com/IBM-Blockchain/marbles/commit/2aeadb70068e182c7e73615895d29636925be152

clone/pull the latest update!

**Comment by dshuffma-ibm** [comment]
@tortuga90 did it work for you?  if so please close the issue.
