### ISSUE TITLE
 Could not find configtx.yaml

### ISSUE THREAD

**Issue by nirmal1988** [IBM-Blockchain-Archive/marbles#152]
I am using first-network application(https://github.com/hyperledger/fabric-samples).

When i run the command to generate(./byfn.sh -m generate) the channel artifacts it gives me following error.
![image](https://user-images.githubusercontent.com/15016894/31226844-41ee05f2-a9c7-11e7-9fa6-722966adc01d.png)

However i already exported FABRIC_CFG_PATH, but it still gives me this error.
FABRIC_CFG_PATH is already printed in screenshot as "/c/apps/fabric-samples/first-network"
Attached the other files
[configtx.yaml.txt](https://github.com/IBM-Blockchain/marbles/files/1359255/configtx.yaml.txt)
[crypto-config.yaml.txt](https://github.com/IBM-Blockchain/marbles/files/1359254/crypto-config.yaml.txt)

Can anyone please help me in this?

**Comment by dshuffma-ibm** [comment]
marbles is not the appropriate repo for this question. please try Hyperledger's [Jira](https://jira.hyperledger.org/secure/Dashboard.jspa).
