### ISSUE TITLE
Fabric install hash ae4e37d

### ISSUE THREAD

**Issue by rgabonada** [IBM-Blockchain-Archive/marbles#153]
Question: which step in the Fabric install do you enter the hash ae4e37d? It's not clear based on the instructions.

**Comment by dshuffma-ibm** [comment]
ok, i'll have to improve the docs. you enter it after you cloned the fabric:

![image](https://user-images.githubusercontent.com/16085295/31388644-a7d104c2-ad9c-11e7-884b-36d5e66b1ff3.png)

**Comment by rgabonada** [comment]
Thank you. I can see the instructions have been updated now.
