### ISSUE TITLE
Verifying fabric install error

### ISSUE THREAD

**Issue by rgabonada** [IBM-Blockchain-Archive/marbles#154]
On verifying Fabric install in $GOPATH/src/github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example02, I get the error-

No such file or directory (nopkcs11)

**Comment by dshuffma-ibm** [comment]
strange, are you running the command `go build --tags nopkcs11 ./`

**Comment by rgabonada** [comment]
I ran the go build command using a single dash and that resulted ok --

go build -tags nopkcs11 ./

**Comment by dshuffma-ibm** [comment]
great. pretty sure `--tags` and `-tags` are equivalent, they both work for me.
