### ISSUE TITLE
Error on installing chaincode - cannot find module

### ISSUE THREAD

**Issue by rgabonada** [IBM-Blockchain-Archive/marbles#161]
I get this error when I tried to install chaincode -

![cannot find module winston](https://user-images.githubusercontent.com/18723210/31571176-8be34acc-b053-11e7-8668-9d92ea785154.PNG)

![winston var](https://user-images.githubusercontent.com/18723210/31571181-966246f6-b053-11e7-8fcc-a55aab74a22c.PNG)

**Comment by dshuffma-ibm** [comment]
The [setup steps](https://github.com/IBM-Blockchain/marbles/blob/v4.0/docs/install_chaincode_locally.md#setup) are required.  From the root of the marbles directory run:  `npm install`

**Comment by rgabonada** [comment]
Thanks. That fixed my issue.
