### ISSUE TITLE
Error: Orderer not found.

### ISSUE THREAD

**Issue by git-rearden** [IBM-Blockchain-Archive/marbles#162]
Followed instructions for local 

~/fabric-tools/marbles/scripts$ node install_chaincode.js
info: Loaded config file /home/<username>/fabric-tools/marbles/config/marbles_local.json
info: Loaded creds file /home/<username>/fabric-tools/marbles/config/blockchain_creds_local.json
---------------------------------------
info: Lets install some chaincode - marbles v4
---------------------------------------
info: First we enroll
key:  orderer.example.com  ("my" extra debug in helper.js)
/home/<username>/fabric-tools/marbles/utils/helper.js:251
				throw new Error('Orderer not found.');
				^

Error: Orderer not found.
    at Object.helper.getOrderersUrl (/home/<username>/fabric-tools/marbles/utils/helper.js:251:11)
    at Object.helper.makeEnrollmentOptionsUsingCert (/home/<username>/fabric-tools/marbles/utils/helper.js:566:24)
    at Object.<anonymous> (/home/<username>/fabric-tools/marbles/scripts/install_chaincode.js:38:32)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)

 docker ps
CONTAINER ID        IMAGE                                   COMMAND                  CREATED             STATUS              PORTS                                            NAMES
937b9d41069c        dev-peer0.org1.example.com-fabcar-1.0   "chaincode -peer.a..."   About an hour ago   Up About an hour                                                     dev-peer0.org1.example.com-fabcar-1.0
e0f0c28a31fd        hyperledger/fabric-tools                "/bin/bash"              About an hour ago   Up About an hour                                                     cli
b6ace037e164        hyperledger/fabric-peer                 "peer node start"        About an hour ago   Up About an hour    0.0.0.0:7051->7051/tcp, 0.0.0.0:7053->7053/tcp   peer0.org1.example.com
5213d5c54c97        hyperledger/fabric-orderer              "orderer"                About an hour ago   Up About an hour    0.0.0.0:7050->7050/tcp                           orderer.example.com
84510a54d41e        hyperledger/fabric-couchdb              "tini -- /docker-e..."   About an hour ago   Up About an hour    4369/tcp, 9100/tcp, 0.0.0.0:5984->5984/tcp       couchdb
0ada6bcc309e        hyperledger/fabric-ca                   "sh -c 'fabric-ca-..."   About an hour ago   Up About an hour    0.0.0.0:7054->7054/tcp                           ca.example.com

**Comment by dshuffma-ibm** [comment]
your file `blockchain_creds_local.json` is missing an orderer or maybe just the orderer's `url` field.

if you checkout the other credential files such as `blockchian_creds_tls.json` you can see how the orderer section should look:
```js
"orderers": {
	"fabric-orderer": {
		"url": "grpc://localhost:7050"  //<- this is only an example, it may not be the correct url for you
	}
},
```

**Comment by git-rearden** [comment]
Thank you very much. I'll give it a try.

**Comment by dshuffma-ibm** [comment]
closing, inactivity

**Comment by rameshb444** [comment]
Hi, 

is this fixed ? I am facing the same issue while running marbles.

**Comment by dshuffma-ibm** [comment]
@rameshb444 this is due to user error.  your JSON is invalid.  it is up to you to fix it. 

check my last comment.  something is malformed and preventing it from finding the orderer url.

**Comment by rameshb444** [comment]
Hi @dshuffma-ibm - 

Thanks for your reply. I have done those changes in my connection_profile_local.json file. It worked fine as expected.
