### ISSUE TITLE
Unable to locate fabric-client

### ISSUE THREAD

**Issue by chainhead** [IBM-Blockchain-Archive/marbles#164]
While trying to run `node query.js`,I am facing this issue about `fabric-client` not being available. I have run `sudo npm -g install` in the `fabcar` folder. I even forced the dependency to `fabric-client@1.0.2` in `package.json`; but, no luck.

Can you please advise how to get around this?

**Comment by dshuffma-ibm** [comment]
strange.  after running the npm install command did you see errors?  I suppose its possible the command did not complete and thats why you don't have `fabric-client` installed. 

oh I wonder if its b/c you tried to install them globally.  I haven't tried that, though I would have thought that's fine.  you may want to run `sudo npm install` instead (no -g)

**Comment by dshuffma-ibm** [comment]
closing, inactive
