### ISSUE TITLE
Marbles Fabric Client: Getting error while connecting to self managed blockchain network

### ISSUE THREAD

**Issue by surendra-kushwaha** [IBM-Blockchain-Archive/marbles#167]
Hi Team,
We are getting some issue while enrolment innTLS enabled self managed blockchain network.
Marbles SDK client fail to connect to enroll to blockchain network.
 error: "error: Error: Calling enrollment endpoint failed with error [Error: write EPROTO 140057963788096:error:1411713E:SSL routines:ssl_check_srvr_ecc_cert_and_alg:ecc cert not for signing:../deps/openssl/openssl/ssl/ssl_lib.c:2520:
140057963788096:error:14082130:SSL routines:ssl3_check_cert_and_algorithm:bad ecc cert:../deps/openssl/openssl/ssl/s3_clnt.c:3550:
]" 
Please provide any solution for this issue.

Thanks

**Comment by dshuffma-ibm** [comment]
I haven't seen this error before.  Is there anything fancy in your network, like is it behind a proxy? Also are you really using TLS on your CA? 

This might be a wild guess, but you may want to update openssl on your system running the node code.

**Comment by brankoterzic** [comment]
Getting the same error on my custom network configuration.

**Comment by brankoterzic** [comment]
@dshuffma-ibm @surendra-kushwaha  I have resolved this as changing the docker-compose-base.yaml env variable:      

`>  - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/57c1bb43dd38d9308f3585f080bb2b3f1bfcce44841e1a3b54602e253469e7b7_sk #this should be renamed after crypto material genration. The file is located at ../crypto-config/peerOrganizations/org1.example.com/ca/`
