### ISSUE TITLE
Unable to Install chaincode on local network

### ISSUE THREAD

**Issue by sushantrane** [IBM-Blockchain-Archive/marbles#170]
Unable to Install chaincode on local network. I have been following the setup guide to install on a local network. 

node install_chaincode.js
info: Loaded config file /home/azuser/work/marbles/config/marbles_local.json
info: Loaded creds file /home/azuser/work/marbles/config/blockchain_creds_local.json
info: Lets install some chaincode - marbles v4
info: First we enroll
info: [fcw] Going to enroll with admin cert!  peer_urls=[grpc://localhost:7051], channel_id=mychannel, uuid=marbles-Docker Compose Network-mychannel-fabric-peer-org1, orderer_url=grpc://localhost:7050, msp_id=Org1MSP
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/root/.hfc-key-store/cd96d5260ad4757551ed4a5a991e62130f8008a0bf996e4e4b84cd097a747fec-priv'
    at Error (native)

Not sure what I am doing wrong here. Any help is apprecaited. 

Thanks,

Sushant Rane

**Comment by dshuffma-ibm** [comment]
try what this guy did: https://github.com/IBM-Blockchain/marbles/issues/168

I wonder if something has shifted/changed in the fabric samples repo...  I don't remember needing to do this originally.

**Comment by sushantrane** [comment]
I had set this up about 2 weeks ago and was working fine and as expected. When i am trying it today, it seems to be failing. I will try and copy the contents and see.

**Comment by sushantrane** [comment]
It works after creating the /.hfc-key-store and copying the contents. Thanks.

**Comment by ishwaryaatrity** [comment]
@sushantrane which content we need to copy ?
after creating a hfc-key-store folder
