### ISSUE TITLE
Facing problem while running command 'node install_chaincode.js'

### ISSUE THREAD

**Issue by rohagarw** [IBM-Blockchain-Archive/marbles#173]
[fcw] Going to enroll with admin cert!  peer_urls=[grpc://192.168.99.100:7051], channel_id=mychannel, uuid=marbles-Docker Compose Network-mychannel-fabric-peer-org1, orderer_url=grpc://192.168.99.100:7050, msp_id=Org1MSP
events.js:183
      throw er; // Unhandled 'error' event
      ^
Error: ENOENT: no such file or directory, open 'C:\Users\rohit\.hfc-key-store\cd96d5260ad4757551ed4a5a991e62130f8008a0bf996e4e4b84cd097a747fec-priv'

Facing the above error..I tried to debug it and I think the error is in file  ..\fabric-samples\marbles\utils\fc_wrangler\enrollment.js  from line no. 196

Thanks in advance..!!

**Comment by dshuffma-ibm** [comment]
try [what this guy did](https://github.com/IBM-Blockchain/marbles/issues/168) which was to:

> Copied the contents of /fabcar/hfc-key-store into a newly created folder Users/Govind/.hfc-key-store.
Now it works.
