### ISSUE TITLE
error running while running  install_chaincode.js 

### ISSUE THREAD

**Issue by amarm85** [IBM-Blockchain-Archive/marbles#174]
amar@amar-VirtualBox:~/workspace/marbles/scripts$ node install_chaincode.js 
info: Loaded config file /home/amar/workspace/marbles/config/marbles_local.json
info: Loaded creds file /home/amar/workspace/marbles/config/blockchain_creds_local.json
---------------------------------------
info: Lets install some chaincode - marbles v4
---------------------------------------
info: First we enroll
info: [fcw] Going to enroll with admin cert!  peer_urls=[grpc://localhost:7051], channel_id=mychannel, uuid=marbles-Docker Compose Network-mychannel-fabric-peer-org1, orderer_url=grpc://localhost:7050, msp_id=Org1MSP
error: [Client.js]: TypeError: this is not a typed array.
    at Function.from (native)
    at importKey (/home/amar/workspace/marbles/node_modules/fabric-client/lib/impl/CryptoSuite_ECDSA_AES.js:180:26)
    at /home/amar/workspace/marbles/node_modules/fabric-client/lib/Client.js:1098:35
error: [fcw] Failed to get enrollment marbles-Docker Compose Network-mychannel-fabric-peer-org1 TypeError: this is not a typed array.
    at Function.from (native)
    at importKey (/home/amar/workspace/marbles/node_modules/fabric-client/lib/impl/CryptoSuite_ECDSA_AES.js:180:26)
    at /home/amar/workspace/marbles/node_modules/fabric-client/lib/Client.js:1098:35
error: [fcw] could not format error
error: error enrolling { parsed: 'Blockchain network error - could not format error',
  raw: [TypeError: this is not a typed array.] } undefined

**Comment by dshuffma-ibm** [comment]
were you able to get around this?  sounds like the SDK doesn't like one of your input arguments.

**Comment by amarm85** [comment]
Yes I updated my Node version and it worked !! Thanks
