### ISSUE TITLE
should be able to use the hfc key store location without copying cred files

### ISSUE THREAD

**Issue by dshuffma-ibm** [IBM-Blockchain-Archive/marbles#175]
marbles (for a local fabric network) currently copies creds from a folder generated by `fabric-samples`.  this scheme no longer works since the cred files are now uniquely generated. (marbles can't find the cred files anymore) this prevents any operation that needs the so called `admin` certificates, such as install/instantiate.

marbles should be more flexible and setup the SDK to use the generated files.  need to change the `helper.getKvsPath()` code.
  

symptoms look like:
`Error: ENOENT: no such file or directory, open '/Users/oldgeezer7/.hfc-key-store/giberish260ad477551ed4a5a991e2130f8008a0bf96e4e4084cd097a74f8c-priv'
`

**Comment by skerbz** [comment]
This doesn't help me know how to fix this issue at all?
I get the same issue as the #186

**Comment by vinayakkulkarni** [comment]
```bash
Vinayaks-MacBook-Pro:scripts work$ mkdir /Users/work/.hfc-key-store/
Vinayaks-MacBook-Pro:scripts work$ ln -s /Users/work/Development/blockchain/fabric-samples/fabcar/hfc-key-store/ /Users/work/.hfc-key-store/
```

Symlinking does the trick for now.

**Comment by dshuffma-ibm** [comment]
done in v5.0
