### ISSUE TITLE
Given setup script link returns 404

### ISSUE THREAD

**Issue by javapriyan** [IBM-Blockchain-Archive/marbles#176]

**Comment by jeffet** [comment]
I think the endpoint has been changed.  Try  curl -sSL https://goo.gl/6wtTN5 -o setup_script.sh

**Comment by dshuffma-ibm** [comment]
thanks, corrected in https://github.com/IBM-Blockchain/marbles/commit/51014f86bc4d69a11c9c63ba8c8f0b42bb8f6148
