### ISSUE TITLE
Problem in creating Blockchain network on Fabric with three organizations

### ISSUE THREAD

**Issue by rohagarw** [IBM-Blockchain-Archive/marbles#178]
I was able to successfully execute tools like configtxgen and cryptogen with relevant files modified for three organizations.

But when I am trying to start the network using command CHANNEL_NAME=$CHANNEL_NAME TIMEOUT=10000 docker-compose -f docker-compose-cli.yaml up -d
It's throwing an error

$ CHANNEL_NAME=$CHANNEL_NAME TIMEOUT=10000 docker-compose -f docker-compose-cli.yaml up -d
WARNING: The COMPOSE_PROJECT_NAME variable is not set. Defaulting to a blank string.
Pulling peer0.org3.example.com (hyperledger/fabric-peer:latest)...
ERROR: manifest for hyperledger/fabric-peer:latest not found

I even searched on net and found the following remedy https://stackoverflow.com/questions/43830372/error-manifest-for-hyperledger-fabric-ordererlatest-not-found
But even this is not working.

Pls help...Thanks in advance.

**Comment by dshuffma-ibm** [comment]
ah, not sure anyone here can help.  You should make an issue on the [Hyperledger Fabric Jira](https://jira.hyperledger.org/secure/Dashboard.jspa)
