### ISSUE TITLE
Number of marbles created when creating a new user

### ISSUE THREAD

**Issue by AmarjitDatta** [IBM-Blockchain-Archive/marbles#179]
Hi,
Thank you for this application. It is really useful.
I have a quick question. When we create a new user, it creates 3 marbles for each user. How can we control this? Can you tell me the file whether this parameter is configured? 

I want to investigate a situation when each user will not have zero marble.

**Comment by dshuffma-ibm** [comment]
check out [app.js line 308](https://github.com/IBM-Blockchain/marbles/blob/v4.0/app.js#L308). 

There is an array that has 1 entry per marble, per marble owner.  Then we use line 318,  `async.each(marbles....)`, to create each marble asynchronously.
