### ISSUE TITLE
No net address for eth1

### ISSUE THREAD

**Issue by himanshutyagi36** [IBM-Blockchain-Archive/marbles#18]
I'm following the tutorial for setting up environment and network in my own laptop.My VP are setup and I'm able to query and invoke transactions on them. In the steps for "Marbles Adjust for local network" , in the step 6 it says to change the setup.js and figure out the address the Vagrant virtual machine offers to the local machine. When I run `ifconfig` there is no `eth1 - net addr` (as shown in screenshot. ) 
<img width="489" alt="screen shot 2016-07-03 at 11 23 27 pm" src="https://cloud.githubusercontent.com/assets/5171506/16550178/30b81b30-4175-11e6-95ee-c16780accf5d.png">

While setting up the Vagrant environment, I used Wi-Fi adapter to bridge connection between vagrant and local machine

**Comment by dshuffma-ibm** [comment]
The people manning this repo do not have high experience troubleshooting with vagrant. Please post over here https://github.com/hyperledger/fabric/issues for help with your issue.

Alternatively use the Bluemix IBM Blockchain service outline in tutorial 1.
