### ISSUE TITLE
OCR not execute inside the Container 

### ISSUE THREAD

**Issue by aswinkumarrhex** [IBM-Blockchain-Archive/marbles#180]
Hi 
installed GO -TESSARECT inside the container fabric-tools. But application still not able to recognize the same at runtime. 
![sm1](https://user-images.githubusercontent.com/20457599/34297240-f8aeeccc-e73c-11e7-9f57-52a4a5ad3af5.png)
![sm2](https://user-images.githubusercontent.com/20457599/34297241-f97a6078-e73c-11e7-8de0-33c410972cd6.png)

**Comment by kozeros** [comment]
Could you specify the issues more clearly?

**Comment by dshuffma-ibm** [comment]
@aswinkumarrhex you likely need to vendor your `gosseract` package.  [golang vendoring tutorial](https://blog.gopheracademy.com/advent-2015/vendor-folder/)

**Comment by dshuffma-ibm** [comment]
closing inactivity
