### ISSUE TITLE
How to add external package in chaincode.

### ISSUE THREAD

**Issue by rajasekar1** [IBM-Blockchain-Archive/marbles#181]
Hi,

I am using ubuntu with docker, In my code i need to use some **third party GO packages** for smart contract.  
When i try to install packages in "cli" container, it shows `chaincode/input/src/marbles/marbles.go:29:2: cannot find package ....`.

Note: Without external package application is working fine.

**Comment by dshuffma-ibm** [comment]
you need to create a vendor folder. read this [Go vendoring tutorial](https://blog.gopheracademy.com/advent-2015/vendor-folder/).

**Comment by dshuffma-ibm** [comment]
closing inactivity.  attaching example though 
[marbles-vendor.zip](https://github.com/IBM-Blockchain/marbles/files/1802685/marbles-vendor.zip)
