### ISSUE TITLE
Lost while creating network

### ISSUE THREAD

**Issue by birshah** [IBM-Blockchain-Archive/marbles#183]
After installation of all software, I tried to create network. However, Bluemix doesnt allow to create network after clicking on blockchain (not sure as I had created my account some time ago) - and it continued to ask me to upgrade account by paying money.
I thought of local hosting but for Windows7, it asks to create virtual environment to run Linux (bash) and I didnt find instructions to create it.

**Comment by mrshah-at-work** [comment]
@birshah you can try to follow the instructions here - https://ibm-blockchain.github.io/

**Comment by dshuffma-ibm** [comment]
closing inactivity
