### ISSUE TITLE
Cannot npm install Mac OSX

### ISSUE THREAD

**Issue by tgmerritt** [IBM-Blockchain-Archive/marbles#185]
`

sudo npm install

> pkcs11js@1.0.12 install /Users/i851546/fabric-samples/fabcar/node_modules/pkcs11js
> node-gyp rebuild

gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/Users/i851546/fabric-samples/fabcar/node_modules/pkcs11js/build'
gyp ERR! System Darwin 17.3.0
gyp ERR! command "/usr/local/Cellar/node@8/8.9.4/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/i851546/fabric-samples/fabcar/node_modules/pkcs11js
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN fabcar@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pkcs11js@1.0.12 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pkcs11js@1.0.12 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/i851546/.npm/_logs/2018-01-04T21_56_15_597Z-debug.log

`

I've used Node 8 because Node 9 was throwing an error, I've installed gcc via homebrew, I've searched the pkcs11js site to no avail - I cannot understand what's actually happening here.  I am unable to install pkcs11js directly via npm.

Please help!

**Comment by mrshah-at-work** [comment]
@tgmerritt Can you try using Node 6.x?

**Comment by tgmerritt** [comment]
That appears to have worked.  May I request that this be added to the installation instructions (at least a note about Node 9 and 8 not working with pkcs11js)?

**Comment by dshuffma-ibm** [comment]
Step [0. Setup Local Environment](https://github.com/IBM-Blockchain/marbles#0-setup-local-environment) points to a doc which does mention the node limitations: 
![image](https://user-images.githubusercontent.com/16085295/34590718-86a97864-f186-11e7-8bf2-a6b94ef2f2b2.png) Though it doesn't point out v9... and the wording isn't great.  I'll tweak that this week.

I was actually hoping most of our dependencies would have been upgraded by now and we can use node 8.... but I guess we still need to wait a bit.
