### ISSUE TITLE
Can't get beyond step 2 in the Hyperledger Fabric local installation - help needed

### ISSUE THREAD

**Issue by adamcz3** [IBM-Blockchain-Archive/marbles#189]
On running ./startFabric.sh, I get the following errors:

docker-compose -f docker-compose.yml down
Removing network net_basic

docker-compose -f docker-compose.yml up -d ca.example.com orderer.example.com peer0.org1.example.com couchdb
Creating orderer.example.com ... error
Creating couchdb ... 
Creating orderer.example.com ... 
Creating ca.example.com ... 

ERROR: for orderer.example.com  Cannot start service orderer.example.com: Mounts denied: 

There are various other errors and can't get past this stage - help greatly appreciated!

**Comment by dshuffma-ibm** [comment]
this repo probably won't offer great advise on your situation. non-the-less this may help you: https://stackoverflow.com/questions/45122459/docker-mounts-denied-the-paths-are-not-shared-from-os-x-and-are-not-known

there are probably more details needed below `Mounts denied:`

**Comment by dshuffma-ibm** [comment]
closing inactivity
