### ISSUE TITLE
Query error on new deployment from local

### ISSUE THREAD

**Issue by sirishonline** [IBM-Blockchain-Archive/marbles#19]
**Getting the following error**
When I call this function on new deployment,

chaincode.query.read(['_marbleindex']

_error: { name: 'query() error',
  code: 400,
  details: '{"Error": "Error:Failed to launch chaincode spec(Error starting container: API error (500): Error: image library/dev-3939016b-d70c-4a46-b754-dcc10d9ceb87_vp1-c29ff1807036492ec8602bb935cee8cc7cb6a45eba307aa642bed12ceceb9dc997e54edd6584936e3976b54125f94a931527494284360aa88bd9ea051aab2da1 not found\n)"}' }_

**Comment by mrshah-at-work** [comment]
Looks like the chaincode deployment failed and it was not able to create/find the chaincode image.

Can you try to deploy the chaincode again?

Are you modifying the chaincode before deploying it? If yes, can you make sure that the chaincode compiles correctly?

**Comment by sirishonline** [comment]
I have customized the Marbles chaincode to the below chaincode. 
https://github.com/sirishonline/NPSChaincode/blob/master/nps_chaincode.go

When I try deploying with original chaincode also, I am getting the same error
https://github.com/IBM-Blockchain/marbles-chaincode/blob/master/part2/part2_chaincode.go

How to compile chaincode?

**Comment by mrshah-at-work** [comment]
I tried compiling your chaincode, it looks good.
I downloaded the chaincode to my $GOPATH/src folder and ran `go build nps_chaincode.go`

Can you try to deploy it again?

**Comment by sirishonline** [comment]
**Successfully deployed.**

{ OK: 'Successfully deployed chainCode.',
  message: 'c29ff1807036492ec8602bb935cee8cc7cb6a45eba307aa642bed12ceceb9dc997e54edd6584936e3976b54125f94a931527494284360aa88bd9ea051aab2da1' }

**Getting the same error:**

error: { name: 'query() error',
  code: 400,
  details: '{"Error": "Error:Failed to launch chaincode spec(Error starting container: API error (500): Error: image library/dev-29121fd2-25f3-43dd-ab94-38d30b99fc4e_vp1-c29ff1807036492ec8602bb935cee8cc7cb6a45eba307aa642bed12ceceb9dc997e54edd6584936e3976b54125f94a931527494284360aa88bd9ea051aab2da1 not found\n)"}' }

**Comment by dshuffma-ibm** [comment]
If the original marble chaincode didn't work either than its not a chaincode related problem.  There is something off in the network you stood up.  I'd trash it and rebuild, or use our [blockchain service](https://github.com/IBM-Blockchain/marbles/blob/master/tutorial_part1.md#setup-options) on Bluemix.

**Comment by sirishonline** [comment]
@dshuffma-ibm I have used the below network only. 
https://github.com/IBM-Blockchain/marbles/blob/master/tutorial_part1.md#setup-options

**Comment by dshuffma-ibm** [comment]
We have been experiencing issues with the Bluemix blockchain service for about a week. If you are trying to use the default network then you will have issues since this network is a Bluemix one.  Best to come back later when its resolved.

**Comment by dshuffma-ibm** [comment]
The service is back, try again.
