### ISSUE TITLE
How to set marbles for multipeers which are in different machines 

### ISSUE THREAD

**Issue by aithavinay** [IBM-Blockchain-Archive/marbles#192]
When trying the marbles for multipeer system ,marble container is not running in all  peers but database is replicating..

**Comment by dshuffma-ibm** [comment]
are you trying to run multiple marble's chaincode? or just multiple marbles node js apps, or both?

as for the chaincode:
1. make sure all your peers have joined some common channel you will be using
2. install the chaincode on each peer.  
3. instantiate the cc on the common channel (you only need to send the instantiate to 1 peer)
4. done

as for the node js app, just try starting 1 app and pointing it at your favorite peer for now. edit the `config` [files](https://github.com/IBM-Blockchain/marbles/blob/v4.0/docs/config_file.md).
