### ISSUE TITLE
Need a branch named "master" to convert this to a starter kit

### ISSUE THREAD

**Issue by dolph** [IBM-Blockchain-Archive/marbles#193]
In order to convert this repository to a [starter kit](https://console.bluemix.net/developer/blockchain/starter-kits) (blockchain does not have any as of this writing), it _should_ have the following three branches:

- `development`: deploys to `dev-console.stage1.bluemix.net` (development)
- `stage1`: deploys to `console.stage1.bluemix.net` (staging)
- `master`: deploys to `console.bluemix.net` (production)

However, only the `master` branch really matters (we have other ways to do development and testing, so and the production console is the only real goal). As a workaround, I've been planning to fork the latest branch of this repository to `github.com/ibm/blockchain-marbles`, and add the starter-kit related bits there. That's inevitably going to be confusing for downstream consumers, but it would work.

Instead, I'm hoping that you can find a way to support a `master` branch on this repository (it doesn't have to be the project's default branch or anything, it just needs to be very stable).

**Comment by stevemar** [comment]
Adding a bit more context, the end result would live here: https://console.bluemix.net/developer/blockchain/starter-kits and be similar to these other starter kits: https://console.bluemix.net/developer/watson/starter-kits

@dolph can you speak to the files that we would need to drop into the `master` branch if it were created.

**Comment by dshuffma-ibm** [comment]
@dolph don't fork it, making a master branch won't be a problem. there will be some other changes coming very soon.  what timeline are you thinking?

**Comment by stevemar** [comment]
@dshuffma-ibm we were thinking end of March

**Comment by dolph** [comment]
The only new file that is _strictly_ required is `blueprint.json` in the root of the project. [This is an example](https://github.com/dolph/ibm-cloud-node-express-starter-kit/blob/master/blueprint.json) `blueprint.json` with all possible services and tags enabled (so a vast superset of what this repo would need).

**Comment by dshuffma-ibm** [comment]
@dolph is there other documentation to reference, i'm not sure what these fields mean

**Comment by stevemar** [comment]
@dshuffma-ibm I can help here. Here's documentation about how git repo branches are used for starter kits and their respective deployments: https://pages.github.ibm.com/arf/codegen-dev-guide/devops/starterkits/#devops-for-real

Here's a relevant snippet:
>The development, stage1, and master branches in a Starter Kit repository are special. Attempts to register branches from any other name is considered a dry-run by the Registration service, and does not result in a new registrant in the registry’s database.

> The rules to abide by are:
> * The development branch content is saved in the Registry’s database where the Registry microservice has stage1 in the domain and -dev hostname suffix.
> * The stage1 branch content is saved in the Registry’s database where the Registry microservice has stage1 in the domain and does not have the -dev hostname suffix.
> * The master branch content is saved in the Registry’s database where the Registry microservice is in production (where of course it lacks both the -dev hostname suffix and stage1 in the domain).

Here's information about the `blueprint.json` file that would contain all the information that the starterkit pulls from: https://pages.github.ibm.com/arf/codegen-dev-guide/starters-client-side/content/#the-blueprintjson-file-in-detail

The site https://pages.github.ibm.com/arf/codegen-dev-guide has a bunch of content.

**Comment by dolph** [comment]
Closing because this is no longer destined to become a starter kit.
