### ISSUE TITLE
Error when initializing marbles app

### ISSUE THREAD

**Issue by ptippett** [IBM-Blockchain-Archive/marbles#194]
I am seeing this issue when I start the marbles example from the IBM Blockchain Platform samples tab.

![image](https://user-images.githubusercontent.com/9286769/37685843-37f190f6-2c52-11e8-9499-d9b134f6f23f.png)

Marbles App: https://marbles-20180320210117284.mybluemix.net/home

The network id is `n8f42ea677452468da65939784e01e7b0` (https://ibmblockchain-starter.ng.bluemix.net/network/n8f42ea677452468da65939784e01e7b0/overview)

Let me know if I should provide any more information

**Comment by dshuffma-ibm** [comment]
Hello Mr. Ptippett. 

Try getting the latest marbles (killing off your clone, or updating it) and trying again.  This commit should have helped. https://github.com/IBM-Blockchain/marbles/commit/e1ee2e48e2306645fa8b618517039bb78e3f7a9a

**Comment by mrshah-at-work** [comment]
Thanks @dshuffma-ibm
