### ISSUE TITLE
Work Flow 

### ISSUE THREAD

**Issue by chandanpatil07** [IBM-Blockchain-Archive/marbles#195]
can anyone tell me how the control flows from .html file in any application of hyper ledger fabrics

**Comment by dshuffma-ibm** [comment]
the readme goes through this.  

- look at the [Application Communication Flow](https://github.com/IBM-Blockchain/marbles#application-communication-flow) section for the high level view + picture
- next look at the readme again, but the [code structure](https://github.com/IBM-Blockchain/marbles#code-structure) section to learn where the code lives
- next back to the readme and follow the actual code path with the [Marbles Deeper Dive](https://github.com/IBM-Blockchain/marbles#code-structure) section

**Comment by dshuffma-ibm** [comment]
closing, inactivity
