### ISSUE TITLE
 Error: Cannot find module

### ISSUE THREAD

**Issue by zyl34389** [IBM-Blockchain-Archive/marbles#197]
when i run this "node install_chaincode.js"

Error: Cannot find module '/home/zyl/marbles/config/[object Object]'
at Function.Module._resolveFilename (module.js:547:15)
at Function.Module._load (module.js:474:25)
at Module.require (module.js:596:17)
at require (internal/module.js:11:18)
at module.exports (/home/zyl/marbles/utils/connection_profile_lib/index.js:22:14)
at Object. (/home/zyl/marbles/scripts/install_chaincode.js:35:84)
at Module._compile (module.js:652:30)
at Object.Module._extensions..js (module.js:663:10)
at Module.load (module.js:565:32)
at tryModuleLoad (module.js:505:12)

**Comment by forestwater** [comment]
I am running into this problem too. 
It comes from line 35 in install_chaincode.js
`var fcw = require(path.join(__dirname, '../utils/connection_profile_lib/index.js'))({ block_delay: cp.getBlockDelay() }, logger);`.
The value of  `{ block_delay: cp.getBlockDelay() }` is "block_delay=10000". But index.js regards it as a filename. 
Can anybody fix this issue?
Thanks!

**Comment by zhulg** [comment]
try:
var fcw = require(path.join(__dirname, '../utils/fc_wrangler/index.js'))({ block_delay: cp.getBlockDelay() }, logger);

**Comment by theGloves** [comment]
I edit script/installchaincode.js(line 35):  var fcw = require(path.join(__dirname, '../utils/fc_wrangler/index.js'))({ block_delay: cp.getBlockDelay() }, logger);
node installchaincode.js can run, but met another problem :(
![image](https://user-images.githubusercontent.com/20971570/37969282-ec20a480-3202-11e8-8c03-2beab546ebdc.png)
how to change metadata size

**Comment by dshuffma-ibm** [comment]
ok so this commit should help most people here https://github.com/IBM-Blockchain/marbles/commit/bc4f9f934086b141590e247b2c120abc06777aa4  go update to the latest commit! thanks for the help

@theGloves I haven't ran into that error yet. are you using the vanilla marbles chaincode?

**Comment by theGloves** [comment]
@dshuffma-ibm
thanks! I can run after updating bc4f9f9, but i find the config/connection_profile_local.json will be changed, 
{
...
chaincode{
       "v4:v4" // when I first run gulp marbles_local, it will be changes to this
       "marbles:v4" //right
}

**Comment by dshuffma-ibm** [comment]
sorry about that, this should help https://github.com/IBM-Blockchain/marbles/commit/07337d73a82608c673410b87d367d5cc8f572897 @theGloves
