### ISSUE TITLE
Deployment to Bluemix failed

### ISSUE THREAD

**Issue by ibakirov** [IBM-Blockchain-Archive/marbles#2]
Deployment demo to Bluemix IBM Bluemix United Kingdom failed with errors:

> Downloading artifacts...DOWNLOAD SUCCESSFUL
> Target: https://api.eu-gb.bluemix.net
> Creating service instance myblockchain in org X@abcZ.com / space dev as X@abcZ.com...
> FAILED
> Server error, status code: 502, error code: 10001, message: Service broker error: Calling url >https://broker-prod.blockchain.ibm.com/v2/service_instances/f392e168-cc79-432b-8c08-cbcce425296b?accepts_incomplete=true failed with error message read ECONNRESET
> 
> Finished: FAILED
> Stage has no runtime information

**Comment by zamrokk** [comment]
It sounds like a connection issue. Check Bluemix status for Blockchain, then restart your application

**Comment by ibakirov** [comment]
Sounds like some internal 502 server error

https://broker-prod.blockchain.ibm.com/ Service broker up and running.

**Comment by dshuffma-ibm** [comment]
Thanks for the report. We have noticed the issue on the blockchain service broker and are working towards a fix. In the mean time you may have to re-attempt multiple times to get a successful network/deployment.  I will update/close this issue when its resolved.

**Comment by dshuffma-ibm** [comment]
A fix is in place. The service may be slow, but it is stable.

**Comment by mayoricodevault** [comment]
{ "code": "ECONNRESET" }
This application cannot run without the blockchain network :(

keep comming this error!!
