### ISSUE TITLE
Sample application deployment tracking: repository URL is missing

### ISSUE THREAD

**Issue by ptitzler** [IBM-Blockchain-Archive/marbles#20]
Hello!

It appears that the application is using the Sample application deployment tracking library `cf-deployment-tracker-client`(https://github.com/IBM-Blockchain/marbles/blob/master/app.js#L108) but doesn't specify a value for the [`repository` property in `package.json`](https://docs.npmjs.com/files/package.json#repository). Without this property no traceback information to your github repository is recorded. Please consider adding the following to `package.json`

```
    ...
    "dependencies": {
        ...   
       "cf-deployment-tracker-client": "*"
    },
    ...
   "repository": {
     "type": "git",
     "url": "https://github.com/IBM-Blockchain/marbles.git"
   }
```

as shown in this example:  https://github.com/IBM-Bluemix/node-helloworld/blob/master/package.json#L9-18

**Comment by masterDev1985** [comment]
Should be fixed here: https://github.com/IBM-Blockchain/marbles/commit/f18131b2cc750354eb4e52c8e2435712defe50d1

Thanks for the heads up!
