### ISSUE TITLE
Error to install chaincode - error "Promise is rejected: Error:14 UNAVAILABLE "

### ISSUE THREAD

**Issue by slugout01** [IBM-Blockchain-Archive/marbles#200]
Failed at installing chaincode locally

i read the "Error on installing chaincode  #187 " but i don't know what to do that this problem resolve. my local error is "Promise is rejected: Error:14 UNAVAILABLE "
Please help.
![20180329_140958](https://user-images.githubusercontent.com/37568558/38071692-4b6dfd4c-3312-11e8-87e4-c5337bcf844a.png)

**Comment by kavyaub** [comment]
Can anyone please provide the reasons for such an error..?I am facing a similar issue but could not find any related help or material online..

**Comment by dshuffma-ibm** [comment]
@kavyaub check:
- if you are sending the call to the incorrect ip/port (check the ip/port of your peer)
- peer is no longer running
- networking issues (turn off firewalls for a test)

**Comment by kavyaub** [comment]
@dshuffma-ibm I ensured all the above, still getting the same error. Unsure why..

If this may help, I tried to make a call to getChannelConfig  and got "grpc: Server.Serve failed to complete security handshake from "172.18.0.1:45760": tls: first record does not look like a TLS handshake" error in the orderer container logs.

**Comment by mrshah-at-work** [comment]
@kavyaub this can happen due to wrong TLS certificate. Looks like you are trying to connect to "grpc" endpoint using "grpcs"? or vice-versa.

**Comment by kavyaub** [comment]
@mrshah-at-ibm Yes.. I think that is it.. Thanks a lot.

**Comment by Matthewbalala** [comment]
can you help me？I have the same issue. don't find chain code.
