### ISSUE TITLE
Why enterprise plan?

### ISSUE THREAD

**Issue by thomassuedbroecker** [IBM-Blockchain-Archive/marbles#201]
In the documentation on IBM Cloud you are also pointed to the sample, when you choose **starter membership plan**?

https://console.bluemix.net/docs/services/blockchain/get_start_starter_plan.html#getting-started-with-starter-plan

**Deploying sample applications**
Starter Plan enables you to deploy sample applications to your network with only a few clicks. With the samples, you can easily learn how chaincodes and applications work in a network.

For more information, see Deploying sample applications._

Question: Why do I need to switch to enterprise?

**Comment by dshuffma-ibm** [comment]
You do not need to switch to enterprise.  Where exactly do you see that wording?

**Comment by thomassuedbroecker** [comment]
@dshuffma-ibm 

In the github project of the sample is written, [Documentation](https://github.com/IBM-Blockchain/marbles/blob/master/docs/use_bluemix_hyperledger.md ) 

> 4. Scroll to the bottom and change the "Selected Plan" to IBM Blockchain Platform - Enterprise Plan
> 5. Click the "Create" button at the bottom right.

This information in the documentation is misleading, it works with the **starter membership plan** , but you first have to fork and later configure you own github integration in the toolchain, when you going to deploy the sample.

**Comment by dshuffma-ibm** [comment]
@thomassuedbroecker thanks pointing this out. we are still changing the wording to reflect the latest changes. when that documentation was written the `starter membership plan` did not exist.  

i'll remove that soon
