### ISSUE TITLE
by runing marbles locally is the step Enroll Admin not going.  

### ISSUE THREAD

**Issue by wanyi000001** [IBM-Blockchain-Archive/marbles#203]
I use Host marbles on IBM Cloud.
by runing marbles locally is the step Enroll Admin not going.  

command terminal shows "Querying Channel Stats" and when successgully got enrollment ... It continue  "Querying Channel Stats" and go on and go on. already 5hours. is this execution all right?  must I waiting for the end of the programm?

**Comment by dshuffma-ibm** [comment]
the "querying channel stats" activity is a loop that will happen forever until you shut down the application. these messages are not an indication that the application is still starting up.

if there are enrollment issues, you will need to look at the logs referencing the enrollment part.

**Comment by dshuffma-ibm** [comment]
closing, inactivity
