### ISSUE TITLE
no such file or directory, open '/home/ibmadmin/fabric-samples/fabcar/hfc-key-store/admin'

### ISSUE THREAD

**Issue by sensahin** [IBM-Blockchain-Archive/marbles#204]
When running node install_chaincode.js, it throws below error:

no such file or directory, open '/home/**ibmadmin**/fabric-samples/fabcar/hfc-key-store/admin'

Somehow it is searching certificates in ibmadmin folder. Any thoughts on this?

**Comment by zhulg** [comment]
modify your path , open config->connection_profile_local.json

**Comment by zhulg** [comment]
@sensahin modify your path , open config->connection_profile_local.json
input your  xxxx/fabric-samples/fabcar/hfc-key-store

**Comment by sensahin** [comment]
Thanks, solved!
