### ISSUE TITLE
Duplicate users are creating in my marbles application

### ISSUE THREAD

**Issue by shravanigandla** [IBM-Blockchain-Archive/marbles#205]
I have updated my chaincode i.e, added new attribute, when i was running this application duplicate users were creating.Plz help me to solve this.
![image](https://user-images.githubusercontent.com/29254188/38370479-cc26c25c-3907-11e8-9a4b-756de537d6d2.png)

**Comment by dshuffma-ibm** [comment]
click the trash can icon to archive your duplicate users.
![image](https://user-images.githubusercontent.com/16085295/38423181-221aee4a-397b-11e8-9dcf-f17ce944c3ce.png)

note that creating users is a deliberate step. if you do not want users created do not click the "express setup" button or the "create" button in the register marbles owner step.

**Comment by dshuffma-ibm** [comment]
closing, inactivity
