### ISSUE TITLE
error: [Client.js]: Failed to load user "admin" from local key value store.

### ISSUE THREAD

**Issue by forestwater** [IBM-Blockchain-Archive/marbles#208]
When I tried to run marbles using this command: **gulp marbles_local**, I got below errors. Could anybody shine some light on this issue? Thanks in advance!  BTW, I have re-run commands "node enrollAdmin.js,     node registerUser.js, node query.js" to create crypto files before run "gulp marbles_local".
    

> error: [Client.js]: Failed to load user "admin" from local key value store. Error: Error: Private key missing from key store. Can not establish the signing identity for user admin
    at _cryptoSuite.importKey.then.then (/home/yan/workspace/marbles/node_modules/fabric-client/lib/User.js:255:11)
error: [Client.js]: Failed to load an instance of requested user "admin" from the state store on this Client instance. Error: Error: Private key missing from key store. Can not establish the signing identity for user admin
    at _cryptoSuite.importKey.then.then (/home/yan/workspace/marbles/node_modules/fabric-client/lib/User.js:255:11)
error: [fcw] Failed to get enrollment marblesDockerComposeNetworkmychannelOrg1MSPfabricpeerorg1 Error: Private key missing from key store. Can not establish the signing identity for user admin
    at _cryptoSuite.importKey.then.then (/home/yan/workspace/marbles/node_modules/fabric-client/lib/User.js:255:11)
error: [fcw] could not format error
error: Exhausted all CAs. There are no more CAs to try.

**Comment by dshuffma-ibm** [comment]
when you ran these commands `node enrollAdmin.js`, and `node registerUser.js` it should have generated some certs in this folder: `/$HOME/fabric-samples/fabcar/hfc-key-store`.  double check that it did.  then check if your connection profile `client.credentialStore.path` field is pointing to the same location:

![image](https://user-images.githubusercontent.com/16085295/38478056-58cf7752-3b84-11e8-9c23-810f4e900e57.png)

final thought - if the path to your `fabric-samples` is different than the default, you will need to modify the connection profile to match.

**Comment by forestwater** [comment]
Thank you @dshuffma-ibm!
Yes, there are some certs generated as below 
> 4696e3b05c75d47fa7c8e099be5d97a4e845298246bead7dae5208e14fe9bf9c-priv
4696e3b05c75d47fa7c8e099be5d97a4e845298246bead7dae5208e14fe9bf9c-pub
ad5dfd889126ef04e1fd43521a3e4eed7664c40e4789d2ab5fc095668b317075-priv
ad5dfd889126ef04e1fd43521a3e4eed7664c40e4789d2ab5fc095668b317075-pub
admin
Org1MSP
user1

And I modified the connection profile as below 

>         "client": {
                "organization": "Org1MSP",
                "credentialStore": {
                        "path": "/home/yan/git/fabric-samples/fabcar/hfc-key-store"
                }
        },

It seems everything is right. But it failed to load user "admin" from local key value store. 
Anymore suggestion? Thanks!

**Comment by forestwater** [comment]
The error is at marbles/node_modules/fabric-client/lib/User.js 

> fromString(str)
 {
...
                        // the key retrieved from the key store using the SKI could be a public key
                        // or a private key, check to make sure it's a private key
                        if (privateKey.isPrivate()) {
                                self._signingIdentity = new SigningIdentity(
                                        state.enrollment.identity.certificate,
                                        pubKey,
                                        self._mspId,
                                        self._cryptoSuite,
                                        new Signer(self._cryptoSuite, privateKey));
                                return self;
                        } else {
                                throw new Error(util.format('Private key missing from key store. Can not establish the signing identity for user %s', state.name));
                        }

It ran into "else" statement. 
And the parameter str is 

>  {"name":"admin","mspid":"Org1MSP","roles":null,"affiliation":"","enrollmentSecret":"","enrollment":{"signingIdentity":"66521d93be11090c63fefe6bbc276809a37fa72f36a130283835a110f9438f36","identity":{"certificate":"-----BEGIN CERTIFICATE-----\nMIICAjCCAaigAwIBAgIUDdV4tT+3ryPNoLdVwcHV3wcwptkwCgYIKoZIzj0EAwIw\nczELMAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNh\nbiBGcmFuY2lzY28xGTAXBgNVBAoTEG9yZzEuZXhhbXBsZS5jb20xHDAaBgNVBAMT\nE2NhLm9yZzEuZXhhbXBsZS5jb20wHhcNMTgwNDA5MDQ0MTAwWhcNMTkwNDA5MDQ0\nNjAwWjAhMQ8wDQYDVQQLEwZjbGllbnQxDjAMBgNVBAMTBWFkbWluMFkwEwYHKoZI\nzj0CAQYIKoZIzj0DAQcDQgAE/2dDmHsc4m+znF75veEvNDCDqD+O5XnvWbzEYE2N\nLjxMvOdN2fuaE/2769VX7NZSpXt7S7WlYh03LG4YCs5K2qNsMGowDgYDVR0PAQH/\nBAQDAgeAMAwGA1UdEwEB/wQCMAAwHQYDVR0OBBYEFIkRuymWb5o9EiFM/j692ttQ\nByZbMCsGA1UdIwQkMCKAIEI5qg3NdtruuLoM2nAYUdFFBNMarRst3dusalc2Xkl8\nMAoGCCqGSM49BAMCA0gAMEUCIQCw9GuIYqEZHqDbQVHzFaLlumictNdhnpPF9BCa\nWrLNeQIgMBCDzEJ9lI2l8Kf0ADp97sPSYueXWRMJn1P0L3UYohs=\n-----END CERTIFICATE-----\n"}}}

Any idea? Thanks!

**Comment by forestwater** [comment]
The privateKey looks like 

> ECDSA_KEY {
  _key: 
   { type: 'EC',
     getBigRandom: [Function],
     setNamedCurve: [Function],
     setPrivateKeyHex: [Function],
     setPublicKeyHex: [Function],
     getPublicKeyXYHex: [Function],
     getShortNISTPCurveName: [Function],
     generateKeyPairHex: [Function],
     signWithMessageHash: [Function],
     signHex: [Function],
     sign: [Function],
     verifyWithMessageHash: [Function],
     verifyHex: [Function],
     verify: [Function],
     verifyRaw: [Function],
     serializeSig: [Function],
     parseSig: [Function],
     parseSigCompact: [Function],
     curveName: 'secp256r1',
     ecparams: 
      { name: 'secp256r1',
        keylen: 256,
        curve: [Object],
        G: [Object],
        n: [Object],
        h: [Object],
        oid: undefined,
        info: undefined },
     prvKeyHex: null,
     pubKeyHex: '04ff6743987b1ce26fb39c5ef9bde12f343083a83f8ee579ef59bcc4604d8d2e3c4cbce74dd9fb9a13fdbbebd557ecd652a57b7b4bb5a5621d372c6e180ace4ada',
     isPublic: true } }

It shows that the privateKey.isPublic=true!
Why?
@dshuffma-ibm Could you take a look at it? Thanks!

**Comment by jhsea3do** [comment]
@forestwater   this bug is caused by fabric-sdk-node  https://jira.hyperledger.org/browse/FAB-2593, 
you may need copy hfc-key-store directory to your home directory $HOME/.hfc-key-store, and re-config the  `client.credentialStore.path`  of `connection_profile_local.json`

**Comment by forestwater** [comment]
@jhsea3do Thank you! It works!

**Comment by nyetwurk** [comment]
Why is this not documented in the Marbles documentation?

**Comment by dshuffma-ibm** [comment]
@nyetwurk feel free to make a PR

**Comment by nyetwurk** [comment]
Working on it now. Will submit a PR if I find a reasonable solution.

**Comment by nyetwurk** [comment]
In particular, it looks like https://jira.hyperledger.org/browse/FAB-2593 (and https://jira.hyperledger.org/browse/FABN-417) are closed, so hopefully a more reasonable solution is possible.

**Comment by linzhuvi** [comment]
3x

**Comment by linboosted** [comment]
@jhsea3do thanks
