### ISSUE TITLE
[client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: chaincode error

### ISSUE THREAD

**Issue by sensahin** [IBM-Blockchain-Archive/marbles#209]
I dont know how many times i tried this but cant get over from this error.

I am always encountering below error when i run **node install_chaincode.js**

Yes, i am using latest version of marbles.
```
[client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: chaincode error (status: 500, message: Authorization for INSTALL has been denied (error-Failed verifying that proposal's creator satisfies local MSP principal during channelless check policy with policy [Admins]: [This identity is not an admin]))
    at new createStatusError (/home/marbles/node_modules/grpc/src/client.js:64:15)
    at /home/marbles/node_modules/grpc/src/client.js:583:15
```

![image](https://user-images.githubusercontent.com/802267/38638033-99e9feee-3dd5-11e8-8a27-2838b03f4318.png)

**Comment by dshuffma-ibm** [comment]
I'm guessing you have seen this thread already? https://github.com/IBM-Blockchain/marbles/issues/198

check what cert you are sending by looking in you connection profile file.  I'm assuming you are using a local hyperledger network thus your connection profile would be [this file](https://github.com/IBM-Blockchain/marbles/blob/master/config/connection_profile_local.json#L39). 

the field `x-adminCert.path` needs to point to a real admin cert. in the latest code we are using the peer's cert from the `basic-network` example in `fabric-samples`. make sure the path to this cert is correct.

you can also dig into the marbles code and print out the contents of the PEM you are using. https://github.com/IBM-Blockchain/marbles/blob/master/utils/connection_profile_lib/parts/org.js#L87

**Comment by dshuffma-ibm** [comment]
closing, inactivity
