### ISSUE TITLE
Marble is not creating when i have added a new attribute.

### ISSUE THREAD

**Issue by bingimanasa** [IBM-Blockchain-Archive/marbles#211]
I have added a new attribute for user, everything is fine while running  attribute is also added. when i have seen marble container logs attribute is added. But marble is not creating in UI.

![image](https://user-images.githubusercontent.com/29275309/38729909-3703bcf8-3f32-11e8-92c9-8d70ddaae2d8.png)
![image](https://user-images.githubusercontent.com/29275309/38730045-b52d6cb4-3f32-11e8-8b80-7fa956826e0c.png)

**Comment by dshuffma-ibm** [comment]
check the js console logs in your browser as well.  see if the [ws(websocket)](https://github.com/IBM-Blockchain/marbles/blob/master/public/js/websocket.js#L55) message contains your marble. If you find the marble/attribute there, then some [logic in the drawing UI](https://github.com/IBM-Blockchain/marbles/blob/master/public/js/ui_building.js#L12) doesn't want to draw it... or maybe the client side js is having an error.

**Comment by dshuffma-ibm** [comment]
closing, inactivity
