### ISSUE TITLE
Calling enrollment endpoint failed with error [Error: connect ECONNREFUSED 127.0.0.1:7054]

### ISSUE THREAD

**Issue by karankk1991** [IBM-Blockchain-Archive/marbles#213]
hey

while connecting to buisness network i am getting this error.

Please can someone help me ...
![issue](https://user-images.githubusercontent.com/38460043/38863983-e6408c4c-4256-11e8-9134-969792ba9f01.png)

**Comment by mrshah-at-work** [comment]
@karankk1991 I am not sure if this is related to the marbles repository. Marbles does not use hyperledger composer at all. Please open the issue on https://github.com/hyperledger/composer

If you still think it is related to marbles repository, feel free to reopen this issue.
