### ISSUE TITLE
Enrolling Admin failed.

### ISSUE THREAD

**Issue by anushaath** [IBM-Blockchain-Archive/marbles#214]
I followed all the steps to get the marbles network deployed, from the readme. I encountered no errors while setting up the network. However after the login screen, Enrolling the Admin failed with the following error.

![screenshot from 2018-04-18 19-14-44](https://user-images.githubusercontent.com/11595241/38935785-d527716e-433c-11e8-839f-2c770d2fdaab.png)

The Logs: 

![screenshot from 2018-04-18 19-17-13](https://user-images.githubusercontent.com/11595241/38935904-22079a72-433d-11e8-98db-7815a677145b.png)

**Comment by YoleYu** [comment]
@anushaath This is duplicated with #208 . 
`this bug is caused by fabric-sdk-node https://jira.hyperledger.org/browse/FAB-2593,
you may need copy hfc-key-store directory to your home directory $HOME/.hfc-key-store, and re-config the client.credentialStore.path of connection_profile_local.json`

**Comment by anushaath** [comment]
That worked. Thanks!
