### ISSUE TITLE
Any REST API？

### ISSUE THREAD

**Issue by vaynetian** [IBM-Blockchain-Archive/marbles#216]
Wonder if I can use http request to use Marble~!

**Comment by dshuffma-ibm** [comment]
Afraid not. The Marbles app uses a websocket to communicate between the back end and the front end. Which handles the marble creation/moving/deletion operations.

Creating a rest layer shouldn't be too bad especially if you are already familiar with Express.  Just a matter of making routes around the functions in [marbles_cc_lib.js](https://github.com/IBM-Blockchain/marbles/blob/master/utils/marbles_cc_lib.js)

**Comment by dshuffma-ibm** [comment]
closing, inactivity
