### ISSUE TITLE
Failed to load an instance of requested user "admin" from the state store on this Client instance

### ISSUE THREAD

**Issue by westudiodev** [IBM-Blockchain-Archive/marbles#221]
------------------------------------------ Websocket Up ------------------------------------------

info: [fcw] Going to enroll peer_urls=[grpc://localhost:7051], channel_id=mychannel, uuid=marblesDockerComposeNetworkmychannelOrg1MSPfabricpeerorg1, ca_url=http://localhost:7054, orderer_url=grpc://localhost:7050, enroll_id=admin, enroll_secret=adminpw, msp_id=Org1MSP, kvs_path=/root/fabric-samples/fabcar/hfc-key-store
error: [Client.js]: Failed to load user "admin" from local key value store. Error: Error: Private key missing from key store. Can not establish the signing identity for user admin
    at _cryptoSuite.importKey.then.then (/root/marbles/node_modules/fabric-client/lib/User.js:255:11)
    at <anonymous>
error: [Client.js]: Failed to load an instance of requested user "admin" from the state store on this Client instance. Error: Error: Private key missing from key store. Can not establish the signing identity for user admin
    at _cryptoSuite.importKey.then.then (/root/marbles/node_modules/fabric-client/lib/User.js:255:11)
    at <anonymous>
error: [fcw] Failed to get enrollment marblesDockerComposeNetworkmychannelOrg1MSPfabricpeerorg1 Error: Private key missing from key store. Can not establish the signing identity for user admin
    at _cryptoSuite.importKey.then.then (/root/marbles/node_modules/fabric-client/lib/User.js:255:11)
    at <anonymous>
error: [fcw] could not format error
error: Exhausted all CAs. There are no more CAs to try.
error: could not enroll...
warn: removing older kvs and trying to enroll again
warn: removed older kvs
info: [fcw] Going to enroll peer_urls=[grpc://localhost:7051], channel_id=mychannel, uuid=marblesDockerComposeNetworkmychannelOrg1MSPfabricpeerorg1, ca_url=http://localhost:7054, orderer_url=grpc://localhost:7050, enroll_id=admin, enroll_secret=adminpw, msp_id=Org1MSP, kvs_path=/root/fabric-samples/fabcar/hfc-key-store
error: [Client.js]: Failed to load user "admin" from local key value store. Error: Error: Private key missing from key store. Can not establish the signing identity for user admin
    at _cryptoSuite.importKey.then.then (/root/marbles/node_modules/fabric-client/lib/User.js:255:11)
    at <anonymous>
error: [Client.js]: Failed to load an instance of requested user "admin" from the state store on this Client instance. Error: Error: Private key missing from key store. Can not establish the signing identity for user admin
    at _cryptoSuite.importKey.then.then (/root/marbles/node_modules/fabric-client/lib/User.js:255:11)
    at <anonymous>
error: [fcw] Failed to get enrollment marblesDockerComposeNetworkmychannelOrg1MSPfabricpeerorg1 Error: Private key missing from key store. Can not establish the signing identity for user admin
    at _cryptoSuite.importKey.then.then (/root/marbles/node_modules/fabric-client/lib/User.js:255:11)
    at <anonymous>
error: [fcw] could not format error
error: Exhausted all CAs. There are no more CAs to try.
error: could not enroll...
warn: Error enrolling admin

**Comment by cgthink** [comment]
I get the same error if i try to start marble by "gulp marbles_local": 
error: [Client.js]: Failed to load user "admin" from local key value store. Error: Error: Private key missing from key store. Can not establish the signing identity for user admin

Install and instantiate chaincode works.

**Comment by cgthink** [comment]
ok ... my problem was that I start node enrollAdmin.js and node registerUser.js after ./startFabric.sh.

If you only ./startFabric.sh / install und instantiate the chaincode and start marble with gulp marbles_local it works.

May be you have the same issue.

**Comment by nerd010** [comment]
it's worked, ths!

**Comment by mathwalerp** [comment]
I am yet to get it can u please provide proper details...

**Comment by mastreips** [comment]
aw man - cgthink - thank you soooo much - not running enrollAdmin.js and registerUser.js before doing the install/instantiate and gulp marbles_local was the answer!!! So happy

**Comment by fleasharp** [comment]
Ran into the same problem and cgthink's solution worked.   Here are the steps I had to take:

1. Stop the Fabric Network:   (goto fabric-samples/basic-network)  ./stop.sh
2. Tear down the network:  ./teardown.sh
3. Go back to Fabcar and execute ./startFabric.sh
4. Goto Marbles and execute node install_chaincode.js
5. execute node instantiate_chaincode.js
6. execute gulp marbles_local

By skipping the enrollAdmin.js and registerUser.js it allows Marbles to run locally.

**Comment by SajiJohnMiranda** [comment]
> Ran into the same problem and cgthink's solution worked. Here are the steps I had to take:
> 
> 1. Stop the Fabric Network:   (goto fabric-samples/basic-network)  ./stop.sh
> 2. Tear down the network:  ./teardown.sh
> 3. Go back to Fabcar and execute ./startFabric.sh
> 4. Goto Marbles and execute node install_chaincode.js
> 5. execute node instantiate_chaincode.js
> 6. execute gulp marbles_local
> 
> By skipping the enrollAdmin.js and registerUser.js it allows Marbles to run locally.

Thanks a Ton!!

**Comment by biserd** [comment]
For this error: "

> Private key missing from key store. Can not establish the signing identity for user

" 
One of the possible solutions is running: "`rm -rf fabric-client-kv-*`" to remove the old key-value stores.

**Comment by ajaya-man** [comment]
`Failed to enroll user 'admin'. ReferenceError: CryptoSuite_ECDSA_AES is not defined`
I got this error while creating channel of [https://github.com/IBM/todo-list-fabricV1](url)
