### ISSUE TITLE
How to run marbles v5?

### ISSUE THREAD

**Issue by github-harry** [IBM-Blockchain-Archive/marbles#226]
I ran this example successfully, but it shows marbles v4 not v5. Is there any difference? 

Also the behaviour of the example is slightly different and there are some problems.

1. I can't run both "Express" and "Guided" mode on start page. Just closed the first page and tried to create and move the marbles. I couldn't move forward at Enrolling admin stage in Guided mode(Log looks fine. I have attached).

![screen shot 2018-05-22 at 11 56 01](https://user-images.githubusercontent.com/39504520/40335372-5594b796-5db7-11e8-86bb-0c13dab63755.png)

2. I couldn't see transactions at left side.  Also I couldn't see transaction hash-code at bottom when I clicked block number different from demo screen.

3. Both "Start up help" and "Setting" buttons are disabled.

Could you give some advice for this?

**Comment by dshuffma-ibm** [comment]
there are differences in the application for v4 and v5, but the chaincode is the same (ie. using the v4 chaincode on the v5 app is correct & fine)

hmm this doesn't add up.  with that many issues you should have errors in the logs.  Check the browser's logs as well (right click page, inspect, open the console).  

any chance the server side logs are not actually the right logs for the web server you are interacting with?

**Comment by github-harry** [comment]
Thanks dshuffma,

Let me check web page console log.
And, how to check the server side log?

**Comment by dshuffma-ibm** [comment]
the screen shot you posted above are server side logs.  these are the logs that print out in your terminal/command prompt after typing `gulp marbles_local`.  

I'm just wondering if you happen to have multiple instances of marbles running? and potentially you are looking at the wrong terminal.  b/c those logs look great, but you are describing lots of issues.

**Comment by github-harry** [comment]
Yes, it works well without any error when I ran the examples except the issues what I mentioned. During creating marbles and moving marbles, I couldn't see any error. I couldn't test yesterday, but I may be able to check today. I will update later.

**Comment by github-harry** [comment]
Guided mode have run successfully with Chrome instead of using Safari.
For a couple of days, I tried it with Safari only, but I tried it with Chrome today.
After that, the problem was gone. I am not sure it is related to Safari version, but I am using Safari Version 11.1 (13605.1.33.1.4) on macOS 10.13.4 high Sierra.

I have done guided 5 steps well, and Setting and Start up help buttons are enabled. 

But my results is still different from demo footprint. 
I couldn't see transaction id at bottom and transaction history at left side of screen as followed capture screen.

<img width="1306" alt="screen shot 2018-05-24 at 16 43 56" src="https://user-images.githubusercontent.com/39504520/40464963-6079006a-5f72-11e8-9486-7b348c1d05b0.png">

Also I've attached web console log history. There is only one error but it is not related to show transaction stuff. 

**websocket.js?v=1527136681504:191 [ws] error handling a ws message TypeError: Cannot read property 'id' of undefined
    at onMessage (websocket.js?v=1527136681504:97)
    at WebSocket.ws.onmessage (websocket.js?v=1527136681504:32)**

[chrome-marble-console-log.log](https://github.com/IBM-Blockchain/marbles/files/2033876/marble-console-log.log)

**Comment by dshuffma-ibm** [comment]
interesting... not sure whats going on here, but there are two methods to trigger the audit panel.  one is just clicking the audit icon and then left clicking a marble.  the other is by right clicking a particular marble.  try out both ways.  I don't have high hops though, for some reasons its chocking on some missing data...

if someone else can repeat this, i'd like to find out how to get in this situation

**Comment by github-harry** [comment]
You can close this case as it works after following your instruction by clicking a particular marble. It works really well. Thank you very much!

**Comment by dshuffma-ibm** [comment]
great!
