### ISSUE TITLE
How to Start Developing Client App using Node SDK?

### ISSUE THREAD

**Issue by rezkus** [IBM-Blockchain-Archive/marbles#228]
Hi guys,

I am trying to make a client app using Fabric SDK Node, but I appear to be clueless on how to start developing it since there are very few beginner's tutorials. 

I already made and ran successfully my chaincode (adopting the Marble's chaincode) and the blockchain network using BYFN sample. So my issue is, what are the next steps I need to take to develop the client app? If any, where should I learn it?

Any help would be very much appreciated. Thanks!

P.s.: I am very new to development with Node.js. If I have to learn it, where should I start? :)

**Comment by dshuffma-ibm** [comment]
I'm not sure what to recommend. Do you have a use case or some target application?  I'm not sure how useful coding against hyperledger fabric just for the sake of it would be.  Or how one would even do that... 

Typically you have some idea you want to build. Then:
- Create some chaincode around the functions you expect to need (creating/editing assets)
- Setup a fabric network + a channel
- Get your chaincode installed/instantiated
- Learn your way around the SDK to interact with your chaincode assets they way you need to
- Expose the SDK interactions through some UI/application for your end users

As for node.js help, I find the mozilla docs to be hands down the best, especially for beginners. Here is their tutorial section https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs .  They also do a great job of documenting specific JS functions.

**Comment by rezkus** [comment]
Hi dshuffma,

Thanks for your reply.

Ah yes sorry, what I'm developing is something called Smart Identity, a distributed identity management system to enable self-sovereign identity: basically, transfer of identity attributes with the consent of identity owners. It pretty much works like [this](https://www.youtube.com/watch?v=zpO7eH5FYdo)

From your guide, I have already done point 1, 2, and 3. Now, I am stuck on the point 4 and 5. Would you kindly elaborate what should I do on those 2 steps? Or where could I learn? I've tried to read tutorials from [here](https://fabric-sdk-node.github.io) but still don't understand where to start since I am a beginner. Sorry if these are stupid questions. 

Thanks again for your help!

**Comment by dshuffma-ibm** [comment]
since this project is young, you will be unable to find any tutorials on SDK usage.  the closest I know of is in Marbles: https://github.com/IBM-Blockchain/marbles#sdk-deeper-dive

The real knowledge will come from reading the [SDK source](https://github.com/hyperledger/fabric-sdk-node/tree/release-1.1/fabric-client/lib).  
- open one of the files, and read the functions that are defined to learn what you can do
- search the repo for usages of the function, and you will likely find a test file showing how its done

**Comment by dshuffma-ibm** [comment]
closing, inactivity
