### ISSUE TITLE
[ibc-js] Register - failure after IBM update

### ISSUE THREAD

**Issue by SvnGpsk** [IBM-Blockchain-Archive/marbles#23]
Hey,
I was running the marbles demo inside of bluemix for the last few days and everything worked perfectly fine. Today IBM released a new version (see [here](https://bluemix-service-status.blockchain.ibm.com/)) of its blockchain-service. And suddenly my Application stopped working. It fails to register the users somehow, although the users that are tried are valid users (they are all visible at API -> Network's Enroll IDs and passwords are correct, too).

I would really appreciate some help!
Best regards

EDIT: There seems to be a problem with the Blockchain service itself..so probably this ticket is at the wrong place. I'll wait for IBM to fix their issue and then close this ticket if the error is gone.

Here is what the app log says:

> App/0
> ------------------------------------------ Server Up - 0.0.0.0:61078 ------------------------------------------
> 2016-07-15T15:07:23.010+0200
> App/0
> Running using Developer settings
> 2016-07-15T15:07:23.010+0200
> App/0
> - Tracking Deployment
>   2016-07-15T15:07:23.010+0200
>   App/0
>   loading hardcoded users
>   2016-07-15T15:07:23.197+0200
>   App/0
>   [!] looks like you are in bluemix, I am going to clear out the deploy_name so that it deploys new cc.
>   2016-07-15T15:07:23.197+0200
>   App/0
>   overwritting users, loading from a vcap service: ibm-blockchain-5-prod
>   2016-07-15T15:07:23.197+0200
>   App/0
>   loading hardcoded peers
>   2016-07-15T15:07:23.197+0200
>   App/0
>   overwritting peers, loading from a vcap service: ibm-blockchain-5-prod
>   2016-07-15T15:07:23.197+0200
>   App/0
>   [!] hope that is ok budddy
>   2016-07-15T15:07:23.197+0200
>   App/0
>   [ibc-js] Peer: vp0-6cbde53e-afe...:30443
>   2016-07-15T15:07:23.200+0200
>   App/0
>   [ibc-js] Peer: vp1-6cbde53e-afe...:30443
>   2016-07-15T15:07:23.203+0200
>   App/0
>   [ibc-js] Peer: vp2-6cbde53e-afe...:30443
>   2016-07-15T15:07:23.203+0200
>   App/0
>   [ibc-js] Peer: vp3-6cbde53e-afe...:30443
>   2016-07-15T15:07:23.203+0200
>   App/0
>   [ibc-js] Registering vp0-6cbde53e-afe...:30443 w/enrollID - user_type1_eb92dc0802
>   2016-07-15T15:07:23.204+0200
>   App/0
>   [ibc-js] Registering vp3-6cbde53e-afe...:30443 w/enrollID - user_type1_c501966b65
>   2016-07-15T15:07:23.212+0200
>   App/0
>   [ibc-js] Registering vp1-6cbde53e-afe...:30443 w/enrollID - user_type1_61e36d90b2
>   2016-07-15T15:07:23.216+0200
>   App/0
>   [ibc-js] Registering vp2-6cbde53e-afe...:30443 w/enrollID - user_type1_1cb6af04b6
>   2016-07-15T15:07:23.217+0200
>   App/0
>   [ibc-js] going to try to register again in 30 secs
>   2016-07-15T15:07:23.447+0200
>   App/0
>   [ibc-js] Register - failure x1 : user_type1_eb92dc0802 500
>   2016-07-15T15:07:23.447+0200
>   App/0
>   [ibc-js] Register - failure x1 : user_type1_1cb6af04b6 500
>   2016-07-15T15:07:23.451+0200
>   App/0
>   [ibc-js] going to try to register again in 30 secs
>   2016-07-15T15:07:23.451+0200
>   App/0
>   [ibc-js] going to try to register again in 30 secs
>   2016-07-15T15:07:23.452+0200
>   App/0
>   [ibc-js] Register - failure x1 : user_type1_61e36d90b2 500
>   2016-07-15T15:07:23.452+0200
>   App/0
>   [ibc-js] Register - failure x1 : user_type1_c501966b65 500
>   2016-07-15T15:07:23.457+0200
>   App/0
>   [ibc-js] going to try to register again in 30 secs
>   2016-07-15T15:07:23.457+0200
>   App/0
>   Uploaded stats { ok: true }
>   2016-07-15T15:07:24.020+0200
>   RTR/0
>   trade-finance-test.eu-gb.mybluemix.net - [15/07/2016:13:07:24.587 +0000] "GET / HTTP/1.1" 101 0 0 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0" 159.122.215.10:18086 x_forwarded_for:"195.212.29.168, 159.122.215.10" x_forwarded_proto:"http" vcap_request_id:d6168395-8d9a-4d4a-5be1-edd03380b0e8 response_time:0.003958422 app_id:f4346050-bd7d-4271-a42b-0bb5f181c8dc x_global_transaction_id:"418089773"
>   2016-07-15T15:07:24.592+0200
>   App/0
>   [ibc-js] Registering vp0-6cbde53e-afe...:30443 w/enrollID - user_type1_eb92dc0802
>   2016-07-15T15:07:53.477+0200
>   App/0
>   [ibc-js] Registering vp2-6cbde53e-afe...:30443 w/enrollID - user_type1_1cb6af04b6
>   2016-07-15T15:07:53.480+0200
>   App/0
>   [ibc-js] Registering vp1-6cbde53e-afe...:30443 w/enrollID - user_type1_61e36d90b2
>   2016-07-15T15:07:53.481+0200
>   App/0
>   [ibc-js] Registering vp3-6cbde53e-afe...:30443 w/enrollID - user_type1_c501966b65
>   2016-07-15T15:07:53.483+0200
>   App/0
>   [ibc-js] Register - failure x2 : user_type1_eb92dc0802 500
>   2016-07-15T15:07:53.705+0200
>   App/0
>   { name: 'register() error',
>   2016-07-15T15:07:53.708+0200
>   App/0
>   code: 500,
>   2016-07-15T15:07:53.708+0200
>   App/0
>   details: { [Error: socket hang up] code: 'ECONNRESET' } }
>   2016-07-15T15:07:53.708+0200
>   App/0
>   ! looks like an error loading the chaincode or network, app will fail
>   2016-07-15T15:07:53.708+0200
>   App/0
>   [ibc-js] Register - failure x2 : user_type1_61e36d90b2 500
>   2016-07-15T15:07:53.709+0200
>   App/0
>   [ibc-js] Register - failure x2 : user_type1_1cb6af04b6 500
>   2016-07-15T15:07:53.709+0200
>   App/0
>   [ibc-js] Register - failure x2 : user_type1_c501966b65 500
>   2016-07-15T15:07:53.714+0200

**Comment by dshuffma-ibm** [comment]
Yeah, there are issues with the Blumix service. Once that's fixed, you should try again.
