### ISSUE TITLE
Chaincode tab on the left no longer exists

### ISSUE THREAD

**Issue by tdietter** [IBM-Blockchain-Archive/marbles#230]
The chaincode tab no longer exists off the left tab.  It's in Channels tab 

![image](https://user-images.githubusercontent.com/19152719/40778007-9a207b6a-649d-11e8-8d75-6caa5cfa39f0.png)

I was going through the 'Try Samples' and installing Marbles and the info was stating to use the Chaincode tab.  I saw this here:
https://github.com/IBM-Blockchain/marbles/blob/master/docs/install_chaincode.md

Under this section:
Install and Instantiate Chaincode w/IBM Cloud

**Comment by dshuffma-ibm** [comment]
out of date doc, need to update the screen shots.  

fyi you would use the tab labeled `Install Chaincode` these days - 06/20/2018

**Comment by dshuffma-ibm** [comment]
done in https://github.com/IBM-Blockchain/marbles/commit/07b706978a555f55f1b200dc1fae8f76ea351359
