### ISSUE TITLE
error: [Orderer.js]: sendBroadcast - timed out after:45000

### ISSUE THREAD

**Issue by sasikumar13** [IBM-Blockchain-Archive/marbles#232]
hlf running

./runApp.sh

error: [Orderer.js]: sendBroadcast - timed out after:45000

[2018-06-08 09:57:08.392] [ERROR] Create-Channel - Error: REQUEST_TIMEOUT

**Comment by mrshah-at-work** [comment]
@sasikumar13 can you let us know how you run HLF - local/IBM Blockchain Platform/kubernetes?

**Comment by sivachaitanya** [comment]
how did you resolve this ?

**Comment by walmon** [comment]
@sasikumar13 how did you solve it?
