### ISSUE TITLE
STDOUT shows the same hash for the previous and current block

### ISSUE THREAD

**Issue by Parece** [IBM-Blockchain-Archive/marbles#234]
I am running a local marbles application, and have been looking at STDOUT when i start the application by running `gulp marbles_tls`.

It appears that a new hash is being created for each committed block, however it almost seems like it outputs the same new hash value for  both the previous block, and the current block -

```
info: New block detected! 17 low=17, high=0, unsigned=true, currentBlockHash=811122002440000089017008719001094000380290067000002000004214276705018045016705836667281902287001600, previousBlockHash=811122002440000089017008719001094000380290067000002000004214276705018045016705836667281902287001600
```

if i run another transaction, we can see that block 18 has a different hash from that of block 17, but that it is also repeating this same 'new' hash. 

```
info: New block detected! 18 low=18, high=0, unsigned=true, currentBlockHash=81212200865000000256700080989400630008400064087085020024400000890170087190010940003802900670000, previousBlockHash=81212200865000000256700080989400630008400064087085020024400000890170087190010940003802900670000
```

It does appear however that the blocks are being committed properly, and helios appears to be properly updating with each invoke.

Please let me know if i can provide more information.

**Comment by dshuffma-ibm** [comment]
interesting, I haven't looked at the hashes too closely, but this is what the peer is reporting. marbles is not formatting/misinterpreting the block data (from what I can tell).  this is either an issue with the SDK or Fabric.  Either way they take issues on [Jira](https://jira.hyperledger.org)

if you open an issue in Jira, please link it over here. 

thanks!

**Comment by Parece** [comment]
@dshuffma-ibm https://jira.hyperledger.org/browse/FAB-10638

thanks
