### ISSUE TITLE
Unable to Connect to Bluemix Network

### ISSUE THREAD

**Issue by aswinkumarrhex** [IBM-Blockchain-Archive/marbles#24]
Hi, 
Newbie here trying to learn/demo on the Marble Application. Unfortunately i am not able to connec to the BlockChain Network. Can anyone share the reasons on the issue and possible work arounds?
**_Error Message**_
Start Up Error
{ "code": "ECONNRESET" }
This application cannot run without the blockchain network :(

Thank You 
Aswink

**Comment by dshuffma-ibm** [comment]
there are known issues with the Bluemix service.  We are working towards a fix but its unstable at the moment.  You can check https://bluemix-service-status.blockchain.ibm.com/ for status and communication messages.

**Comment by kimdotnet** [comment]
@dshuffma-ibm when can we expect the service become available again?

**Comment by dshuffma-ibm** [comment]
There has been substantial progress, but it is not yet resolved.  Nor is there a date for a resolution.  I'll update this thread when its alive an well.

**Comment by dshuffma-ibm** [comment]
The service is back! try again. @kimdotnet

**Comment by aswinkumarrhex** [comment]
hi, @dshuffma-ibm ,
been having issues since yesterday in pushing custom code into the Marbles App
"Deploy to Bluemix failed" "Push to Cloud Foundry 1 failed"  are the only few logs/messages i see,
is it more a CF issue or "Bluemix integration services (AddGIT) related? what other sources to view a detailed log for any deployment ?

**Comment by dshuffma-ibm** [comment]
A push to cloud foundry error sounds like a Bluemix issue (unrelated to our service).  I also noticed a few failed to push errors myself yesterday, but its been okay today so far. You can open a tick with Bluemix itself (click the top right) to investigate. 

![image](https://cloud.githubusercontent.com/assets/16085295/17589074/a1ad39e4-5fa0-11e6-944d-3f451f067563.png)
