### ISSUE TITLE
gulp marbles_local

### ISSUE THREAD

**Issue by BoBoGithub** [IBM-Blockchain-Archive/marbles#241]
![2018-07-05 11-52-52](https://user-images.githubusercontent.com/4011103/42302867-42d4b852-8050-11e8-92de-380d8dde7a07.png)

执行最后一部时， 报这个错误（# gulp marbles_local）

**Comment by fedorax** [comment]
Hi! I'm same problem.
Plz help!

**Comment by fedorax** [comment]
Hi! I solved myself.

I deleted the file in the hfc-key-store folder and made it empty.
https://github.com/IBM-Blockchain/marbles/blob/master/config/connection_profile_local.json#L10

after run `gulp marbles_local` as well.

**Comment by BoBoGithub** [comment]
That's Good, I have a try too.  

But then console Notice This :  error: Exhausted all CAs. There are no more CAs to try.

**Comment by dshuffma-ibm** [comment]
@BoBoGithub try deleting the entire `/$HOME/fabric-samples/fabcar/hfc-key-store` folder?

**Comment by BoBoGithub** [comment]
@dshuffma-ibm That day I not delete `/$HOME/fabric-samples/fabcar/hfc-key-store` folder. I try delete files in this folder, then run `gulp marbles_local` , but the result is not good！

**Comment by BoBoGithub** [comment]
Today I reinstall, when run `gulp marbles_local` before, I delete the files in `/$HOME/fabric-samples/fabcar/hfc-key-store`  folder 

 **it run success!**  Thanks for Help！@fedorax @dshuffma-ibm 

After I will lean the code.

![2018-07-10 17-04-28](https://user-images.githubusercontent.com/4011103/42500515-1b363d26-8464-11e8-8dfa-d31391770d84.png)

**Comment by dshuffma-ibm** [comment]
glad to hear it

**Comment by youlindongxiao** [comment]
@fedorax thank you very much ,the same thing with you. Perfect solution
