### ISSUE TITLE
shell  startFabric.sh  CC Not Find?

### ISSUE THREAD

**Issue by BoBoGithub** [IBM-Blockchain-Archive/marbles#243]
![2018-07-24 22-59-58](https://user-images.githubusercontent.com/4011103/43147312-53be3554-8f95-11e8-90b7-cf3810d8cb22.png)

the `$CC_SRC_PATH` => `github.com/fabcar/go`

Can you tell me  the ` $CC_SRC_PATH` is where ?

I find this in cli `sudo docker run hyperledger/fabric-tools ls -al` but not find

Help me Thanks!

**Comment by dshuffma-ibm** [comment]
its here [fabric-samples/chaincode/fabcar/go](https://github.com/hyperledger/fabric-samples/tree/release-1.2/chaincode/fabcar/go)

**Comment by BoBoGithub** [comment]
@dshuffma-ibm Thanks!

But why?    `$CC_SRC_PATH` => `github.com/fabcar/go`    **=?=**   [fabric-samples/chaincode/fabcar/go](https://github.com/hyperledger/fabric-samples/tree/release-1.2/chaincode/fabcar/go)

I don't find something relations in code.

**Comment by dshuffma-ibm** [comment]
Oh, I see what you mean now. I actually confused you here, forget my previous comment.

This path is for the peer process *inside* the docker container.  It does **not** need to match your host machine's file structure.  The peer image will contain the `github.com/fabcar/go` files.

**Comment by BoBoGithub** [comment]
@dshuffma-ibm Oh, I know, Thanks!

**1.** I look the peer image `sudo docker run hyperledger/fabric-peer ls -al ` 
    But not find the `github.com/fabcar/go` files, My idear is right?

    I find the cc code of the fabcar in cli image peer, use cmd 
    $ sudo docker exec -e "CORE_PEER_LOCALMSPID=Org1MSP" -e "CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp" cli ls /opt/gopath/src/github.com/fabcar/go


**2.** I want to rewrite or update the cc code of the fabcar, How can I do? 
   
         I try   update the cc of the fabcar in local  ->  docker cp local dest -> remove peer image and install
         It's run success!

@dshuffma-ibm Above two action, My idear is right?

**Comment by dshuffma-ibm** [comment]
> update the cc of the fabcar in local ->  docker cp local dest 

I believe that's right, but I'm not really familiar with the setup of fabcar. Typically I can only help with `marbles` related questions.

**Comment by BoBoGithub** [comment]
@dshuffma-ibm Thanks, You are welcome.

Now I run the marbles app success, Then I will see the code around this.
