### ISSUE TITLE
install_chaincode error

### ISSUE THREAD

**Issue by yyyfor** [IBM-Blockchain-Archive/marbles#244]
Hi. I encountered this error when i run node install_chaincode.js:

```
info: Loaded config file /home/siming/marbles/config/marbles_local.json
info: Loaded connection profile file /home/siming/marbles/config/connection_profile_local.json



Connection Profile Lib Functions:()
  getNetworkName()
  getNetworkCredFileName()
  buildTlsOpts()
  getFirstChannelId()
  getChannelId()
  loadPem()
  getMarblesField()
  getChaincodeId()
  getChaincodeVersion()
  getFirstCaName()
  getCA()
  getCasUrl()
  getAllCaUrls()
  getCaName()
  getCaTlsCertOpts()
  getEnrollObj()
  getFirstPeerName()
  getPeer()
  getPeersUrl()
  getAllPeerUrls()
  getPeerEventUrl()
  getPeerTlsCertOpts()
  getMarbleUsernamesConfig()
  getCompanyNameFromFile()
  getMarblesPort()
  getEventsSetting()
  getKeepAliveMs()
  getFirstOrdererName()
  getOrderer()
  getOrderersUrl()
  getOrdererTlsCertOpts()
  getBlockDelay()
  getKvsPath()
  getFirstOrg()
  getClientsOrgName()
  getClientOrg()
  getMarbleUsernames()
  getOrgsMSPid()
  getAdminPrivateKeyPEM()
  getAdminSignedCertPEM()
Bus error (core dumped)
```

**Comment by dshuffma-ibm** [comment]
What does your environment look like (OS, node js version, is it a VM?)? 

That is a strange error to see in node.js.

**Comment by yyyfor** [comment]
@dshuffma-ibm 
Thank you for your reply.

I got those informations: 
uame -a
```
Linux JD 4.4.0-109-generic #132-Ubuntu SMP Tue Jan 9 19:52:39 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

node -v 
`v8.11.3`

It's a cloud host.

And i believe connection_profile_local.json is well configured. I guess core dumped is more likely related to a memory issue. Still trying to figure out the solution :(

**Comment by dshuffma-ibm** [comment]
hmm node v8 should be fine.  you may want to try node v6 just as an experiment.  make sure to delete your `node_modules` folder and re-do the `npm install` step.

ubuntu is fine... not sure! make sure you have at least 256MB of memory free. though being out of memory should look different.

**Comment by yyyfor** [comment]
@dshuffma-ibm Thank you for your reply. Finally it works.

I deleted node_modules directory and redo all the steps following Get Crypto Material instructions with no error appears.

Thanks for your help.
