### ISSUE TITLE
Error occured when running "gulp marbles_local"

### ISSUE THREAD

**Issue by offthewall123** [IBM-Blockchain-Archive/marbles#249]
info: [fcw] Going to enroll peer_urls=[grpc://localhost:7051], channel_id=mychannel, uuid=marblesDockerComposeNetworkmychannelOrg1MSPfabricpeerorg1, ca_url=http://localhost:7054, orderer_url=grpc://localhost:7050, enroll_id=admin, enroll_secret=adminpw, msp_id=Org1MSP, kvs_path=/Users/xu/Desktop/fabric-samples/fabcar/hfc-key-store
error: [Client.js]: Failed to load user "admin" from local key value store. Error: Error: Private key missing from key store. Can not establish the signing identity for user admin
    at _cryptoSuite.importKey.then.then (/Users/xu/Desktop/marbles/node_modules/fabric-client/lib/User.js:255:11)
    at <anonymous>
error: [Client.js]: Failed to load an instance of requested user "admin" from the state store on this Client instance. Error: Error: Private key missing from key store. Can not establish the signing identity for user admin
    at _cryptoSuite.importKey.then.then (/Users/xu/Desktop/marbles/node_modules/fabric-client/lib/User.js:255:11)
    at <anonymous>
error: [fcw] Failed to get enrollment marblesDockerComposeNetworkmychannelOrg1MSPfabricpeerorg1 Error: Private key missing from key store. Can not establish the signing identity for user admin
    at _cryptoSuite.importKey.then.then (/Users/xu/Desktop/marbles/node_modules/fabric-client/lib/User.js:255:11)
    at <anonymous>
error: [fcw] could not format error
error: Exhausted all CAs. There are no more CAs to try.
error: could not enroll...
warn: Error enrolling admin

**Comment by dshuffma-ibm** [comment]
try deleting your key value store folder `/Users/xu/Desktop/fabric-samples/fabcar/hfc-key-store` and re-running the steps.  also make sure you didn't skip the [register steps](https://github.com/IBM-Blockchain/marbles/blob/master/docs/use_local_hyperledger.md#4-test-network-with-fabcar).

**Comment by miku2000** [comment]
See my merge request for the documentation, based on https://github.com/IBM-Blockchain/marbles/issues/208

**Comment by dshuffma-ibm** [comment]
closing - inactivity
