### ISSUE TITLE
HOWTO Deploy this demo on a local network?

### ISSUE THREAD

**Issue by ProgramErgoSum** [IBM-Blockchain-Archive/marbles#25]
I am able to start-up the peer and member service separately with Docker images on my Ubuntu VM. I used the instructions from here: https://github.com/hyperledger/fabric/blob/master/docs/Setup/Network-setup.md 

Can you please list out the next steps that I need to follow to deploy this demo on my local network?

**Comment by WindyCitySDR** [comment]
Hello,

On Tue, Jul 26, 2016 at 3:46 PM, ProgramErgoSum notifications@github.com
wrote:

> I am able to start-up the peer and member service separately with Docker
> images on my Ubuntu VM. I used the instructions from here:
> https://github.com/hyperledger/fabric/blob/master/docs/Setup/Network-setup.md
> 
> Can you please list out the next steps that I need to follow to deploy
> this demo on my local network?

​Can you post your Ubuntu VM Images with both the "Peer" and "Member
Services" for all ?

I'm sure, like myself, there are plenty of others who could utilize it to,
for example, prospectively assist you.​

**Comment by ProgramErgoSum** [comment]
Gladly. I was hoping to finish the demo before I can upload the .ova. What is a good place to store the .ova? Box?

But, really, the set-up is not too difficult. Just installed Docker and followed the network set-up instructions from here.

**Comment by WindyCitySDR** [comment]
On Jul 26, 2016, at 10:38 PM, ProgramErgoSum notifications@github.com wrote:

> Gladly. I was hoping to finish the demo before I can upload the .ova. What is a good place to store the .ova? Box?

GitHub would work

> But, really, the set-up is not too difficult. Just installed Docker and followed the network set-up instructions from here.

I figured since you already had done that I wanted to attach it to this:

https://t.co/a5Rs2dSlbN

IBM Blockchain SDR financial networks could prospectively be attained.

;-)

Just installing the dependencies necessary to run the blockchain network itself, within the same SDR Environment, destroys the SDR environment.

**Comment by ProgramErgoSum** [comment]
As I had expected, I am unable to upload the whole of .ova file to GitHub. I will upload elsewhere and share with you the link. Can I have your mail ID to share privately, please?

Can you please describe the SDR as applied to financial networks? I am somewhat familiar with SDR but, it would be nice to know how Blockchain and financial networks are involved.

**Comment by dshuffma-ibm** [comment]
I've added a new section to tutorial 1 to address your original question. [Configure the SDK for your Blockchain Network](https://github.com/IBM-Blockchain/marbles/blob/master/tutorial_part1.md#confignetwork)

**Comment by ProgramErgoSum** [comment]
I am going through that article now.

Just so that I am clear, going by the figure for Application Communication flow, the Blockchain network is not in Bluemix, whereas, the application to communicate with the Blockchain network is in Bluemix. The blockchain network could either be in Bluemix or could exist locally too. Is this correct?

**Comment by ProgramErgoSum** [comment]
Thanks. I meant to ask, how is SDR involved with Blockchain and financial networks.

**Comment by WindyCitySDR** [comment]
Sent from my iPhone

On Jul 27, 2016, at 8:47 PM, ProgramErgoSum notifications@github.com wrote:

> Thanks. I meant to ask, how is SDR involved with Blockchain and financial networks.

It's something I'm doing currently, through my own initiative, and with your forthcoming images, it'll be easier for me to "connect up" a "Blockchain Network" with "Financial Networks".

I'll keep everyone updated upon my success with what I've already done and your forthcoming images.

**Comment by ProgramErgoSum** [comment]
ok. I was able to get the blockchain network running successfully with PBFT; I will keep you posted.
