### ISSUE TITLE
gulp marbles_local Errors

### ISSUE THREAD

**Issue by rghorpade** [IBM-Blockchain-Archive/marbles#250]
I did everything right without any errors except "npm install" in marbles directory with errors which I tried to fix but unable  to fix some errors ...

 Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Prototype pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ hoek                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ > 4.2.0 < 5.0.0 || >= 5.0.3                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ gulp-sass [dev]                                              │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ gulp-sass > node-sass > node-gyp > request > hawk > boom >   │
│               │ hoek                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/566                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Prototype pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ hoek                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ > 4.2.0 < 5.0.0 || >= 5.0.3                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ gulp-sass [dev]                                              │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ gulp-sass > node-sass > node-gyp > request > hawk >          │
│               │ cryptiles > boom > hoek                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/566                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Prototype pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ hoek                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ > 4.2.0 < 5.0.0 || >= 5.0.3                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ gulp-sass [dev]                                              │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ gulp-sass > node-sass > node-gyp > request > hawk > hoek     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/566                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Prototype pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ hoek                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ > 4.2.0 < 5.0.0 || >= 5.0.3                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ gulp-sass [dev]                                              │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ gulp-sass > node-sass > node-gyp > request > hawk > sntp >   │
│               │ hoek                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/566                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ lodash                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=4.17.5                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ gulp-dependencies                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ gulp-dependencies > lodash                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/577    

Then after this when I run gulp marbles_local I got following error. Tried to get help but nothing working... for this gulp issue. Please help

~/coding/golang/marbles$ gulp marbles_local
assert.js:42
  throw new errors.AssertionError({
  ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (/home/rg1/coding/golang/marbles/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (/home/rg1/coding/golang/marbles/node_modules/undertaker/lib/task.js:13:8)
    at Object.<anonymous> (/home/rg1/coding/golang/marbles/gulpfile.js:29:6)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)

**Comment by dshuffma-ibm** [comment]
according to this [issue](https://github.com/gulpjs/undertaker/issues/54) you might need to revert `gulp` to `v3`.  try `npm uninstall -g gulp` and then `npm install -g gulp@3.9.1`

**Comment by rghorpade** [comment]
Thanks for the immediate reply.
I am using Ubuntu 18.04 and with gulp 3.9.1 also it gives errors but tells me to open in browser. Its just first page in browser with errors and its a non working first page.
Do you want me to check it on Ubuntu 16.04?

**Comment by ragpach2** [comment]
@rghorpade Hi, I had also faced the same problem as you.
I read that the problem is resolved with gulp 3 and went back to gulp 3.9.1 from 4.0.0. It worked really fine for me.

npm install gulp@3.9.1 --save

Ubuntu 16.04 is my machine.

**Comment by rghorpade** [comment]
Very good. I am now using Ubuntu 16.04, node v8.9.4 and latest gulp

**Comment by rghorpade** [comment]
Now I am on Ubuntu 16.04 with node v8.9.4 as node v6.11.1 was giving error for enrollAdmin.js file.
I install gulp $npm install gulp -g and its working fine. But now have following error with 
$gulp marbles_local

error: [fcw] could not format error
error: Exhausted all CAs. There are no more CAs to try.
error: could not enroll...
warn: Error enrolling admin


- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
info: Detected that we have NOT launched successfully yet
debug: Open your browser to http://localhost:3001 and login as "admin" to initiate startup
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Trying to log in in browser but not able to login using "admin" and "adminpw"

Can anyone please help? Am I doing something wrong?

**Comment by rghorpade** [comment]
SOLVED.
Need to copy hfc-key-store directory to your home directory $HOME/.hfc-key-store, and re-config the client.credentialStore.path of connection_profile_local.json

**Comment by ragpach2** [comment]
@rghorpade Please can you tell me if you were able to instantiate your code?

**Comment by rghorpade** [comment]
Yes I did instantiate and used it successfully. Now I need guidance to
customize it like enroll the customers, and do the accounts.
