### ISSUE TITLE
Download Marbles Git Checkout error

### ISSUE THREAD

**Issue by vishalsinha82** [IBM-Blockchain-Archive/marbles#251]
Hi,
When trying to setup Hyperledger fabric on my local system following steps mentioned in link:
https://github.com/IBM-Blockchain/marbles/blob/v4.0/README.md#downloadmarbles
In Download marbles section of Marbles Setup section , i get error while doing git checkout
The step says:
Open a command prompt/terminal and browse to your desired working directory
(However, no specific directory is mentioned here). So, i created a new directory
mkdir -p $GOPATH/src/github.com/marble1
But when i try to run below commend it fails.
git clone https://github.com/IBM-Blockchain/marbles.git --depth 1
cd marbles
git checkout v4.0

AzureAD+VISHALSinha@DESKTOP-PILVKEQ MINGW64 ~/go/src/github.com/marble1/marbles (master)
$ git checkout v4.0
er
ror: pathspec 'v4.0' did not match any file(s) known to git.

Please can you guide as to in which folder to checkut v4.0 ?

Regards,
Vishal Sinha
vishal.sinha@in.ibm.com

**Comment by dshuffma-ibm** [comment]
any reason you are trying to grab the older version of marbles? `v4.0` is not the latest.  `v5.0` is.  
https://github.com/IBM-Blockchain/marbles#1-download-marbles


if you are intent on using v4.0, then you should fresh your clone with `git fetch`, then try `git checkout v4.0`

**Comment by rghorpade** [comment]
Oh. I was not knowing this.

Thanks.
Rajeev Ghorpade

**Comment by dshuffma-ibm** [comment]
ok try `git branch` to see what branch you are on.  if you are on `v5.0` or `master` then you are good to go. they are the same, and are the latest version.

**Comment by vishalsinha82** [comment]
Hi All,
Thanks for your suggestion!
I created a new directory mkdir -p $GOPATH/src/github.com/marble2, then cloned the marbles into this folder.
Then executed "git branch" command to check my branch. I am in "master" branch. I tried both git checkout v4.0 and git checkout v5.0 but in both cases error was returned.

AzureAD+VISHALSinha@DESKTOP-PILVKEQ MINGW64 ~/go/src/github.com/marble2/marbles (master)
$ git checkout v5.0
**error: pathspec 'v5.0' did not match any file(s) known to git.**

AzureAD+VISHALSinha@DESKTOP-PILVKEQ MINGW64 ~/go/src/github.com/marble2/marbles (master)
$ git branch
* master

AzureAD+VISHALSinha@DESKTOP-PILVKEQ MINGW64 ~/go/src/github.com/marble2/marbles (master)
$ git checkout v4.0
**error: pathspec 'v4.0' did not match any file(s) known to git.**

AzureAD+VISHALSinha@DESKTOP-PILVKEQ MINGW64 ~/go/src/github.com/marble2/marbles (master)
$ ls
app.js           cSpell.json                gulpfile.js   package.json  README-ja.md  scripts/
chaincode/       dictionary_blockchain.txt  LICENSE       public/       README-ko.md  scss/
config/          doc_images/                manifest.yml  README.md     README-pt.md  utils/
CONTRIBUTING.md  docs/                      nodemon.json  README-cn.md  routes/       views/


Please let me know if any other option can be tried. Thanks !
Regards,
Vishal

**Comment by dshuffma-ibm** [comment]
Do not use v4.0.  I'm not sure why people are trying to checkout that branch. You may be looking at older directions? if so please post where you are getting these instructions.

 the `master` or `v5.0` branch are correct.  there is no need to checkout a different one. You are on master already, so you are good to go.
