### ISSUE TITLE
Unable to instantiate chaincode label:"help wanted" 

### ISSUE THREAD

**Issue by ragpach2** [IBM-Blockchain-Archive/marbles#252]
Hi, I have been following the README file.

I could install the chaincode without any errors.
**info: Install done. Errors: nope** 
But I am facing errors while instantiating the same chaincode.
using : **node instantiate.js**

The errors are:

error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: chaincode error (status: 500, message:  is not a valid endorsement system chaincode)
    at new createStatusError (/home/ragpach2/marbles_tutorial/marbles/node_modules/fabric-client/node_modules/grpc/src/client.js:64:15)
    at /home/ragpach2/marbles_tutorial/marbles/node_modules/fabric-client/node_modules/grpc/src/client.js:583:15
error: [fcw] Failed to obtain endorsement for transaction. code=2, , details=chaincode error (status: 500, message:  is not a valid endorsement system chaincode)
error: [fcw] Error in instantiate catch block object code=2, , details=chaincode error (status: 500, message:  is not a valid endorsement system chaincode)
---------------------------------------
info: Instantiate done. Errors: parsed=Blockchain network error -  is not a valid endorsement system chaincode), raw=[code=2, , details=chaincode error (status: 500, message:  is not a valid endorsement system chaincode)]
---------------------------------------
``
Kindly help. ****
Thanking You

Raginee

**Comment by dshuffma-ibm** [comment]
strange error. can you run the [test instructions](https://github.com/IBM-Blockchain/marbles/blob/master/docs/use_local_hyperledger.md#4-test-network-with-fabcar)?

**Comment by dshuffma-ibm** [comment]
closing - inactivity

**Comment by bhemeswararao** [comment]
sowedane@sowedane-OptiPlex-3010:~/hyperledger/wallet/wallet/scripts$ node install_chaincode.js 
info: Loaded config file /home/sowedane/hyperledger/wallet/wallet/config/data_local.json
info: Loaded creds file /home/sowedane/hyperledger/wallet/wallet/config/blockchain_creds_local.json
---------------------------------------
info: Lets install some chaincode - Data v24
---------------------------------------
info: First we enroll
info: [fcw] Going to enroll with admin cert!  peer_urls=[grpc://localhost:7051], channel_id=mychannel, uuid=rutes-Docker Compose Network-mychannel-fabric-peer-org1, orderer_url=grpc://localhost:7050, msp_id=Org1MSP
debug: added peer grpc://localhost:7051
debug: [fcw] Successfully got enrollment rutes-Docker Compose Network-mychannel-fabric-peer-org1
---------------------------------------
info: Now we install
---------------------------------------
debug: [fcw] Installing Chaincode
debug: [fcw] Sending install req targets=[grpc.max_receive_message_length=-1, grpc.max_send_message_length=-1, grpc.keepalive_time_ms=120000, grpc.http2.min_time_between_pings_ms=120000, grpc.keepalive_timeout_ms=20000, grpc.http2.max_pings_without_data=0, grpc.keepalive_permit_without_calls=1, clientCert=undefined, _url=grpc://localhost:7051, protocol=grpc, addr=localhost:7051, , _name=localhost:7051, _request_timeout=90000, _grpc_wait_for_ready_timeout=3000, $interceptors=[], $interceptor_providers=[], $callInvocationTransformer=undefined, , $interceptors=[], $interceptor_providers=[], $callInvocationTransformer=undefined, ], chaincodePath=Data, chaincodeId=Data, chaincodeVersion=v24
debug: [fcw] Successfully obtained transaction endorsement
---------------------------------------
info: Install done. Errors: nope
---------------------------------------
sowedane@sowedane-OptiPlex-3010:~/hyperledger/wallet/wallet/scripts$ node instantiate_chaincode.js 
info: Loaded config file /home/sowedane/hyperledger/wallet/wallet/config/data_local.json
info: Loaded creds file /home/sowedane/hyperledger/wallet/wallet/config/blockchain_creds_local.json
---------------------------------------
info: Lets instantiate some chaincode - Data v24
---------------------------------------
warn: Note: the chaincode should have been installed before running this script
info: First we enroll
info: [fcw] Going to enroll with admin cert!  peer_urls=[grpc://localhost:7051], channel_id=mychannel, uuid=rutes-Docker Compose Network-mychannel-fabric-peer-org1, orderer_url=grpc://localhost:7050, msp_id=Org1MSP
debug: added peer grpc://localhost:7051
debug: [fcw] Successfully got enrollment rutes-Docker Compose Network-mychannel-fabric-peer-org1
---------------------------------------
info: Now we instantiate
---------------------------------------
debug: [fcw] Instantiating Chaincode peer_urls=[grpc://localhost:7051], channel_id=mychannel, chaincode_id=Data, chaincode_version=v24, cc_args=[12345], ssl-target-name-override=null, pem=null
debug: [fcw] Sending instantiate req targets=[grpc.max_receive_message_length=-1, grpc.max_send_message_length=-1, grpc.keepalive_time_ms=120000, grpc.http2.min_time_between_pings_ms=120000, grpc.keepalive_timeout_ms=20000, grpc.http2.max_pings_without_data=0, grpc.keepalive_permit_without_calls=1, clientCert=undefined, _url=grpc://localhost:7051, protocol=grpc, addr=localhost:7051, , _name=localhost:7051, _request_timeout=90000, _grpc_wait_for_ready_timeout=3000, $interceptors=[], $interceptor_providers=[], $callInvocationTransformer=undefined, , $interceptors=[], $interceptor_providers=[], $callInvocationTransformer=undefined, ], chaincodeId=Data, chaincodeVersion=v24, fcn=init, args=[12345], 0=163, 1=37, 2=236, 3=75, 4=171, 5=178, 6=145, 7=124, 8=40, 9=36, 10=211, 11=133, 12=239, 13=42, 14=155, 15=243, 16=142, 17=10, 18=73, 19=143, 20=75, 21=145, 22=111, 23=64, _transaction_id=3ef55e17cf2089154bc42c24ee87bdab7f7c7b0ba4d8dc7e5da4f46a3143788e, _admin=false
error: [fcw] Failed to obtain endorsement for transaction. status=500, , url=grpc://localhost:7051, name=localhost:7051, grpc.max_receive_message_length=-1, grpc.max_send_message_length=-1, grpc.keepalive_time_ms=120000, grpc.http2.min_time_between_pings_ms=120000, grpc.keepalive_timeout_ms=20000, grpc.http2.max_pings_without_data=0, grpc.keepalive_permit_without_calls=1, isProposalResponse=true
error: [fcw] Error in instantiate catch block object status=500, , url=grpc://localhost:7051, name=localhost:7051, grpc.max_receive_message_length=-1, grpc.max_send_message_length=-1, grpc.keepalive_time_ms=120000, grpc.http2.min_time_between_pings_ms=120000, grpc.keepalive_timeout_ms=20000, grpc.http2.max_pings_without_data=0, grpc.keepalive_permit_without_calls=1, isProposalResponse=true
---------------------------------------
info: Instantiate done. Errors: parsed=Blockchain network error - Customer
", raw=[status=500, , url=grpc://localhost:7051, name=localhost:7051, grpc.max_receive_message_length=-1, grpc.max_send_message_length=-1, grpc.keepalive_time_ms=120000, grpc.http2.min_time_between_pings_ms=120000, grpc.keepalive_timeout_ms=20000, grpc.http2.max_pings_without_data=0, grpc.keepalive_permit_without_calls=1, isProposalResponse=true]
---------------------------------------

**Comment by bhemeswararao** [comment]
same error provide solution
