### ISSUE TITLE
Custimazation of Marbles for asset transfer

### ISSUE THREAD

**Issue by rghorpade** [IBM-Blockchain-Archive/marbles#255]
Is there any guide available to customize the marbles code? 

I have successfully installed marbles on my local machine and its working smoothly. Thanks to IBM code developers and on line community who posted solutions to so many small small problems. 

Now I need to go ahead and allow user to enroll using its secret pass phrase or finger print and allow them to add assets and transfer it to anyone they want.

Can anyone please help me?
Thanks
rGhorpade

**Comment by dshuffma-ibm** [comment]
Not really. Assuming you read this description on [how marbles was built](https://github.com/IBM-Blockchain/marbles#sdk-deeper-dive).  If you understand that section and are proficient with node.js you would be able to customize it.

**Comment by dshuffma-ibm** [comment]
closing - inactivity
