### ISSUE TITLE
Installation problem Local Hyperledger Network (Windows 10 with Bash shell)

### ISSUE THREAD

**Issue by iamjouza** [IBM-Blockchain-Archive/marbles#257]
Hello,

I am trying install the local hyperledger network on my PC.
I have Windows 10 and the Bash shell and have this error at the first step :

![prblem](https://user-images.githubusercontent.com/24362673/44243129-bf9e7280-a1cd-11e8-9424-01fc46cfe09c.PNG)

And after of course, there is no containers running : 
![prblem2](https://user-images.githubusercontent.com/24362673/44243144-d6dd6000-a1cd-11e8-8bd4-deca12d14815.PNG)

Docker version : 18.06.0-ce, build 0ffa825

Thank you !

**Comment by dshuffma-ibm** [comment]
I believe the script runs under a different profile and that profile doesn't find `docker` in its PATH.  This is more of a linux configuration issue, so I'm not sure how to fix that.

**Comment by chrim5** [comment]
@iamjouza make sure you have docker-compose installed (https://docs.docker.com/compose/install/) or check your PATH variable.

**Comment by dshuffma-ibm** [comment]
closing - inactivity

**Comment by ravi0511** [comment]
This post worked for me in Windows 10 Enterprise version.

https://blog.jayway.com/2017/04/19/running-docker-on-bash-on-windows/
