### ISSUE TITLE
Failed to query successfully :: Error: "targets" parameter not specified and no peers are set on this Channel instance or specfied for this channel in the network 

### ISSUE THREAD

**Issue by Jayaramdas2002** [IBM-Blockchain-Archive/marbles#260]
I got the following error while executing node query.js

Store path:/root/marbles/fabric-samples/fabcar/hfc-key-store
Successfully loaded user1 from persistence
Failed to query successfully :: Error: "targets" parameter not specified and no peers are set on this Channel instance or specfied for this channel in the network 
 
The node enrollAdmin.js and node registerUser.js were successful.

**Comment by dshuffma-ibm** [comment]
Any luck? Did you edit the default script?  The fabcar sample is pretty reliable.

**Comment by dshuffma-ibm** [comment]
closing - inactivity
