### ISSUE TITLE
Not able to clone marbles

### ISSUE THREAD

**Issue by shchaudh** [IBM-Blockchain-Archive/marbles#268]
When I try to clone marbles using command : 
git clone https://github.com/IBM-Blockchain/marbles.git --depth 1

I get below error:

C:\Program Files\Git>git clone https://github.com/IBM-Blockchain/marbles.git --depth 1
Cloning into 'marbles'...
C:/Program Files/Git/marbles/.git: Permission denied

I also tried creating marbles folder and run the command from there still no success.

C:\Program Files\Git\marbles>git clone https://github.com/IBM-Blockchain/marbles.git --depth 1
fatal: could not create work tree dir 'marbles': Permission denied

Tried running from gitbash:

AzureAD+SHARDENDUCHAUDHARY@DESKTOP-VFFDGML MINGW64 /
$ git clone https://github.com/IBM-Blockchain/marbles.git --depth 1
C:/Program Files/Git/marbles/.git: Permission deniedCloning into 'marbles'...
C:/Program Files/Git/marbles/.git: Permission denied

AzureAD+SHARDENDUCHAUDHARY@DESKTOP-VFFDGML MINGW64 /
$ Cloning into 'marbles'...
bash: Cloning: command not found

AzureAD+SHARDENDUCHAUDHARY@DESKTOP-VFFDGML MINGW64 /
$ C:/Program Files/Git/marbles/.git: Permission denied
bash: C:/Program: No such file or directory

**Comment by dshuffma-ibm** [comment]
strange, i'm unsure if its github that is blocking you, or if its just your file system. is your windows user an admin?

do you have trouble cloning other repositories?

you may want to try cloning in a different path outside of "program files".  something like `C:\marbles`.  or in your my documents folder `C:\Users\your-username-here\Documents`. 

finally it may be worth trying an elevated command prompt. 
![image](https://user-images.githubusercontent.com/16085295/47435855-5e69c100-d773-11e8-845a-852de7fb21f6.png)

**Comment by shchaudh** [comment]
Thanks a lot, running Git Bash from C:\Users\your-username-here\Documents ,
I was able to clone.


Regards,
Sharad
-------------------------------------
Shardendu K Chaudhary
Advisory Project Manager,
Cell# +91 9960096532
Email-ID : shchaudh@in.ibm.com
