### ISSUE TITLE
running locally- error - configure of 'mycreds.json'?

### ISSUE THREAD

**Issue by smatthewenglish** [IBM-Blockchain-Archive/marbles#27]
I'm trying to run the marbles example locally- but I ran into this error: 

![12121j2kkkmm123](https://cloud.githubusercontent.com/assets/9053984/17271913/1b85d3aa-5689-11e6-8211-6ac5c05623c3.png)

![12121j2kkkmm1234](https://cloud.githubusercontent.com/assets/9053984/17271916/287ba738-5689-11e6-8f33-e3b7df2e6b00.png)

![kkmm123](https://cloud.githubusercontent.com/assets/9053984/17271917/2eb2ae1c-5689-11e6-905b-f40c7bc76f97.png)

I guess maybe it has something to do with my `mycreds.json` file, because that was the only part of the tutorial I didn't fully grasp.

In the docs this is given as an example: 

{
  "credentials": {
    "peers": [
      {
        "api_host": "12345678-abcde-_vp0.blockchain.ibm.com",   //hostname or ip of peer
        "api_port_tls": 443,                                    //https port (optional)
        "api_port": 80,                                         //http port
        "id": "12345678-abcde-4d6f-_vp0",                       //unique id of peer
      },
    ],
    "users": [
      {
        "enrollId": "user_type1_1234567890",                     //enroll username
        "enrollSecret": "1234567890"                             //enroll's secret
      }
    ]
  }
}

but I don't really understand how that relates to my system or what I need to change exactly. 

```
{
  "credentials": {
    "peers": [
      {
        "discovery_host": "8aa42d25-c620-4d6f-872e-90545ce399d4_vp0.blockchain.ibm.com",
        "discovery_port": 30304,
        "api_host": "8aa42d25-c620-4d6f-872e-90545ce399d4_vp0.blockchain.ibm.com",
        "api_port_tls": 30443,
        "api_port": 30443,
        "type": "peer",
        "network_id": "8aa42d25-c620-4d6f-872e-90545ce399d4",
        "container_id": "82b2cbfd17c5495296cc048edf7d5a7d50032d2e8191e4603626231da648a01c",
        "id": "8aa42d25-c620-4d6f-872e-90545ce399d4_vp0",
        "api_url": "http://8aa42d25-c620-4d6f-872e-90545ce399d4_vp0.blockchain.ibm.com:30443"
      },
      {
        "discovery_host": "8aa42d25-c620-4d6f-872e-90545ce399d4_vp1.blockchain.ibm.com",
        "discovery_port": 30304,
        "api_host": "8aa42d25-c620-4d6f-872e-90545ce399d4_vp1.blockchain.ibm.com",
        "api_port_tls": 30443,
        "api_port": 30443,
        "type": "peer",
        "network_id": "8aa42d25-c620-4d6f-872e-90545ce399d4",
        "container_id": "d1e19c515263370793044fb0b64d4a049c4c033c161522782296a635c840ef69",
        "id": "8aa42d25-c620-4d6f-872e-90545ce399d4_vp1",
        "api_url": "http://8aa42d25-c620-4d6f-872e-90545ce399d4_vp1.blockchain.ibm.com:30443"
      },
      {
        "discovery_host": "8aa42d25-c620-4d6f-872e-90545ce399d4_vp3.blockchain.ibm.com",
        "discovery_port": 30304,
        "api_host": "8aa42d25-c620-4d6f-872e-90545ce399d4_vp3.blockchain.ibm.com",
        "api_port_tls": 30443,
        "api_port": 30443,
        "type": "peer",
        "network_id": "8aa42d25-c620-4d6f-872e-90545ce399d4",
        "container_id": "bd69aef23dd06381d0cc64b68e834ff4dbb59de311bf4a97b10a606d6f0d68a8",
        "id": "8aa42d25-c620-4d6f-872e-90545ce399d4_vp3",
        "api_url": "http://8aa42d25-c620-4d6f-872e-90545ce399d4_vp3.blockchain.ibm.com:30443"
      }
    ],
    "ca": {
      "8aa42d25-c620-4d6f-872e-90545ce399d4_ca": {
        "url": "8aa42d25-c620-4d6f-872e-90545ce399d4_ca.blockchain.ibm.com:30304",
        "discovery_host": "8aa42d25-c620-4d6f-872e-90545ce399d4_ca.blockchain.ibm.com",
        "discovery_port": 30304,
        "api_host": "8aa42d25-c620-4d6f-872e-90545ce399d4_ca.blockchain.ibm.com",
        "api_port_tls": 30304,
        "api_port": 30443,
        "type": "ca",
        "network_id": "8aa42d25-c620-4d6f-872e-90545ce399d4",
        "container_id": "da818d4c027963635671a81f96c99a17cfa92d052449ef07d40db1419b4a077d"
      }
    },
    "users": [
      {
        "username": "admin",
        "secret": "dfc2dd1fe7",
        "enrollId": "admin",
        "enrollSecret": "dfc2dd1fe7"
      },
      {
        "username": "WebAppAdmin",
        "secret": "00cac86b46",
        "enrollId": "WebAppAdmin",
        "enrollSecret": "00cac86b46"
      },
      {
        "username": "dashboarduser_type1_de9e08c8e7",
        "secret": "d356d1801e",
        "enrollId": "dashboarduser_type1_de9e08c8e7",
        "enrollSecret": "d356d1801e"
      },
      {
        "username": "dashboarduser_type1_733b81ccfb",
        "secret": "d1359b3bb9",
        "enrollId": "dashboarduser_type1_733b81ccfb",
        "enrollSecret": "d1359b3bb9"
      },
      {
        "username": "dashboarduser_type1_4a9f59b3dc",
        "secret": "46863c70da",
        "enrollId": "dashboarduser_type1_4a9f59b3dc",
        "enrollSecret": "46863c70da"
      },
      {
        "username": "dashboarduser_type1_f5387afa3b",
        "secret": "0df4cbc984",
        "enrollId": "dashboarduser_type1_f5387afa3b",
        "enrollSecret": "0df4cbc984"
      },
      {
        "username": "user_type1_c711dabdbe",
        "secret": "d0903ab61d",
        "enrollId": "user_type1_c711dabdbe",
        "enrollSecret": "d0903ab61d"
      },
      {
        "username": "user_type1_14824e9f6d",
        "secret": "1473f80c51",
        "enrollId": "user_type1_14824e9f6d",
        "enrollSecret": "1473f80c51"
      },
      {
        "username": "user_type1_6586bcd182",
        "secret": "e853fa6073",
        "enrollId": "user_type1_6586bcd182",
        "enrollSecret": "e853fa6073"
      },
      {
        "username": "user_type1_07799d5465",
        "secret": "24ee24ca15",
        "enrollId": "user_type1_07799d5465",
        "enrollSecret": "24ee24ca15"
      },
      {
        "username": "user_type1_4c682e8a20",
        "secret": "6880c1e88c",
        "enrollId": "user_type1_4c682e8a20",
        "enrollSecret": "6880c1e88c"
      },
      {
        "username": "user_type2_b5bbab6465",
        "secret": "df62eb3bb8",
        "enrollId": "user_type2_b5bbab6465",
        "enrollSecret": "df62eb3bb8"
      },
      {
        "username": "user_type2_187a4aabfb",
        "secret": "f8af825a13",
        "enrollId": "user_type2_187a4aabfb",
        "enrollSecret": "f8af825a13"
      },
      {
        "username": "user_type2_9f757a0ea7",
        "secret": "2b63039ac9",
        "enrollId": "user_type2_9f757a0ea7",
        "enrollSecret": "2b63039ac9"
      },
      {
        "username": "user_type2_7f91f93fa5",
        "secret": "e607419b15",
        "enrollId": "user_type2_7f91f93fa5",
        "enrollSecret": "e607419b15"
      },
      {
        "username": "user_type2_24b8b22ac6",
        "secret": "6894ea9800",
        "enrollId": "user_type2_24b8b22ac6",
        "enrollSecret": "6894ea9800"
      },
      {
        "username": "user_type4_0289fe29cf",
        "secret": "7251384b2b",
        "enrollId": "user_type4_0289fe29cf",
        "enrollSecret": "7251384b2b"
      },
      {
        "username": "user_type4_2049ded2b4",
        "secret": "b8a51ab655",
        "enrollId": "user_type4_2049ded2b4",
        "enrollSecret": "b8a51ab655"
      },
      {
        "username": "user_type4_cec61f8db5",
        "secret": "b23f764bb3",
        "enrollId": "user_type4_cec61f8db5",
        "enrollSecret": "b23f764bb3"
      },
      {
        "username": "user_type4_1c39d64696",
        "secret": "c74e91332b",
        "enrollId": "user_type4_1c39d64696",
        "enrollSecret": "c74e91332b"
      },
      {
        "username": "user_type4_565ca41b4b",
        "secret": "8a278015b8",
        "enrollId": "user_type4_565ca41b4b",
        "enrollSecret": "8a278015b8"
      },
      {
        "username": "user_type8_8e704c3bcb",
        "secret": "c74eb98482",
        "enrollId": "user_type8_8e704c3bcb",
        "enrollSecret": "c74eb98482"
      },
      {
        "username": "user_type8_ef8c228d33",
        "secret": "e3cbee199d",
        "enrollId": "user_type8_ef8c228d33",
        "enrollSecret": "e3cbee199d"
      },
      {
        "username": "user_type8_2a3d9753fe",
        "secret": "86f50dc81f",
        "enrollId": "user_type8_2a3d9753fe",
        "enrollSecret": "86f50dc81f"
      },
      {
        "username": "user_type8_743bc5dfcf",
        "secret": "7458320203",
        "enrollId": "user_type8_743bc5dfcf",
        "enrollSecret": "7458320203"
      },
      {
        "username": "user_type8_bd45a365d9",
        "secret": "ebd96b87b0",
        "enrollId": "user_type8_bd45a365d9",
        "enrollSecret": "ebd96b87b0"
      }
    ]
  }
}
```

**Comment by dshuffma-ibm** [comment]
You are using a problematic network! sorry about that, we have been trying to let people know about our outage. You network was created on July 20th and if you see our status message: `Networks on/after 7/15 will not be working`.

You should delete this network and hang tight till we resume the service.  Currently no new networks can be created and only networks created before 7/15 are working.

Our [status page](https://bluemix-service-status.blockchain.ibm.com) will be updated when we resume normal operation. The same details can be found in the "Status" tab on the networks dashboard.
![image](https://cloud.githubusercontent.com/assets/16085295/17295740/a264f6ce-57cb-11e6-869e-a9bc5bc982ee.png)

---

**Oh but back to your question the json blob you posted last could be copied as is into `myrcreds.json`.**

**Comment by smatthewenglish** [comment]
:/ I don't get it- I was running it locally on my localhost- what does that have to do with your network? so then- I guess I need to specially configure `membersrvc.yaml` and `mycreds.json` as according to the fabric slac channel- but I don't know exactly how- do you have some idea about that?

**Comment by mrshah-at-work** [comment]
when you try to run the marbles example locally, it still points to the URLs mentioned in the JSON blob you posted (example - 8aa42d25-c620-4d6f-872e-90545ce399d4_vp0.blockchain.ibm.com). And as @dshuffma-ibm rightly mentioned, there was an outage on the Blockchain Network you mentioned.

When you say you are running it locally, do you have a blockchain network locally deployed? If yes, then you will have to edit `mycreds.json` with correct credentials to point to your local blockchain network.

**Comment by smatthewenglish** [comment]
yes, I've followed the procedure to configure fabric on my own machine. so I think I'm running it locally- or no? 

do you know what the `mycreds.json` file needs to look like? 

then `membersrvc.yaml` doesn't need to be modified?

**Comment by mrshah-at-work** [comment]
you will have to replace the URLs with the ones that will point to the local machine URLs.. I assume you are running it inside vagrant. Do you know what IP addresses of the peers and the ports running the REST APIs?

**Comment by dshuffma-ibm** [comment]
Yes, it sounds like you are running locally.  Sorry, I thought the JSON you posted was from your Bluemix network, but I see now it was just the file that came with the marbles repo.

So like mrshah says you need to replace the fields outline in this [section](https://github.com/IBM-Blockchain/marbles/blob/master/tutorial_part1.md#configure-the-sdk-for-your-blockchain-network) to those of your local network.

```
{
  "credentials": {
    "peers": [
      {
        "api_host": A_PEERS_IP_ADDRESS_HERE, 
        "api_port": A_PEERS_API_PORT_HERE, 
        "id": "vp1"
      }
    ],
    "users": [
      {
        "enrollId": "AN_ENROLL_ID_HERE",
        "enrollSecret": "AN_ENROLL_SECRET_HERE"
      }
    ]
  }
}
```

**Comment by smatthewenglish** [comment]
![12121j2kkkmm1234](https://cloud.githubusercontent.com/assets/9053984/17300521/03890a66-5813-11e6-92a1-f98b08e59ac8.png)

From that output is it possible to determine those value? 

I guess the PEER_IP is `3443`?

and, the ENROLLED_ID is `user_type1_c711dabde`?

but what to put for `api_port` or `enrolledSecret`?

In the slack channel they told me I should also modidfy `membersrvc.yaml`, but- it's not necessary?

**Comment by dshuffma-ibm** [comment]
Well no. Looks like you are running the application with the default `mycreds.json` file.  This file must be changed.  You must overwrite this file with literally this text:

```
{
  "credentials": {
    "peers": [
      {
        "api_host": A_PEERS_IP_ADDRESS_HERE, 
        "api_port": A_PEERS_API_PORT_HERE, 
        "id": "vp1"
      }
    ],
    "users": [
      {
        "enrollId": "AN_ENROLL_ID_HERE",
        "enrollSecret": "AN_ENROLL_SECRET_HERE"
      }
    ]
  }
}
```

Once you have overwritten the file you should now edit this file. Where it says `A_PEERS_IP_ADDRESS_HERE` you should replace it with some sort of ip address.  One that points to a peer you stood up. It might be `127.0.0.1` depending on how you created the network.

Next change where it says `A_PEERS_API_PORT_HERE` to the port you listed in **your** [core.yml](https://github.com/hyperledger/fabric/blob/master/peer/core.yaml#L26) file.

Next change where it says `AN_ENROLL_ID_HERE` and `AN_ENROLL_SECRET_HERE` to the enrollIDs you listed in **your** [membersrvc.yml](https://github.com/hyperledger/fabric/blob/master/membersrvc/membersrvc.yaml#L101) file.

Save the file and re-run marbles. If the logs you see say anything about 'vp0-8aa42d25-c62...' then you are not editing the correct file.

**Comment by smatthewenglish** [comment]
![12121j2kkkmm1234](https://cloud.githubusercontent.com/assets/9053984/17323648/399c195a-58a3-11e6-859b-53d8b7286a22.png)

I tried to follow your instructions. I got the error posted above. 

I set `mycreds.json` to this:

```
{
  "credentials": {
    "peers": [
      {
        "api_host": 127.0.0.1,
        "api_port": 0.0.0.0:5000,
        "id": "vp1",
      },
    ],
    "users": [
      {
        "enrollId": "lukas",
        "enrollSecret": "NPKYL39uKbkj"
      }
    ]
  }
}
```

the user lucas I chose because of the `membersrvc.yml`, i.e.: 

```
admin: 1 Xurw3yU9zI0l institution_a 00001 '{"registrar":{"roles":["client","peer","validator","auditor"],"delegateRoles":["client"]}}'
WebAppAdmin: 1 DJY27pEnl16d institution_a 00002 '{"registrar":{"roles":["client"]}}'
lukas: 1 NPKYL39uKbkj bank_a 00001
system_chaincode_invoker: 1 DRJ20pEql15a institution_a 00002
diego: 1 DRJ23pEQl16a institution_a 00003
jim: 1 6avZQLwcUe9b bank_a 00004
binhn: 1 7avZQLwcUe9q institution_a 00005
```

where did you get `127.0.0.1` from? has that been set somewhere? I just set up my network according to the docs. 

for `0.0.0.0:5000` I chose it from:

```
    # The address that the REST service will listen on for incoming requests.
    address: 0.0.0.0:5000
```

in `core.yml` since it was highlighted in the photo you linked to, I know you said _my_ `core.yml`, but actually mine looks the same

**Comment by dshuffma-ibm** [comment]
Hmm I can see at least one issue, try using this instead:

```
{
    "credentials": {
        "peers": [{
            "api_host": "127.0.0.1",
            "api_port": 5000,
            "id": "vp1"
        }],
        "users": [{
            "enrollId": "lukas",
            "enrollSecret": "NPKYL39uKbkj"
        }]
    }
}
```
- 127.0.0.1 is always your localhost (for any machine, ever).  I actually do not know if this is the correct IP or not. It depends on how you created the network...
- Port should be just an integer.
- EnrollId/Secret looks fine

**Comment by smatthewenglish** [comment]
![12121j2kkkmm1234](https://cloud.githubusercontent.com/assets/9053984/17335675/0cc2542a-58db-11e6-917f-7fb67743a450.png)

I tried with that file and it generated this error. 

I checked the file `app.js` at line `196` as it says and it looks like this: 

```
    // ==================================
    // configure options for ibm-blockchain-js sdk
    // ==================================
    var options =   {
                        network:{
                            peers: [peers[0]],                                                                  //lets only use the first peer! since we really don't need any more than 1
                            users: users,       
```

**Comment by dshuffma-ibm** [comment]
Sorry i should have linted that json code. It wasn't valid.  I corrected it above

**Comment by smatthewenglish** [comment]
hmm, seems that the following function gave an error:

```
    // check if we already have the chaincode in the local filesystem, else download it
    function cb_ready(){
        try{fs.mkdirSync(tempDirectory);}
        catch(e){ }
        fs.access(unzip_cc_dest, cb_file_exists);                                       //check if files exist yet
        function cb_file_exists(e){
            if(e != null){
                download_it(options.zip_url);                                           //nope, go download it
            }
            else{
                logger.log('[ibc-js] Found chaincode in local file system');
                fs.readdir(unzip_cc_dest, cb_got_names);                                //yeppers, go use it
            }
        }
    }
```

here's what it said: 

![12121j2kkkmm1234](https://cloud.githubusercontent.com/assets/9053984/17336451/8d650610-58de-11e6-8b33-d51dbeb663d8.png)

**Comment by dshuffma-ibm** [comment]
Your node version is too old. From the root of your marbles folder try running:

```
> npm update npm
> npm install 
```

That may not be sufficient. If it still fails you should try installing node v 4.4.x https://nodejs.org/en/

**Comment by smatthewenglish** [comment]
so- it took me a few days to figure out but I finally updated my version of `nodejs`\* and `npm`, but now I've encountered a new problem, here's the error message I got after reinstalling `gulp` and rerunning the `npm install` command: 

```
  Error: ENOENT: no such file or directory, open 'cc_summaries/8c5677016abb7b4885b8dc40bb5b28f1554888cd766e2c945bc61bca03b349092f19197d32785254c692c9210db34c31821efc89e8a9f4dcb3f5575bebb4584b.json'  

 at Error (native) 
 errno: -2, 
 code: 'ENOENT', 
 syscall: 'open', 
 path: 'cc_summaries/8c5677016abb7b4885b8dc40bb5b28f1554888cd766e2c945bc61bca03b349092f19197d32785254c692c9210db34c31821efc89e8a9f4dcb3f5575bebb4584b.json' }
```

in the terminal it looked like this: 

![12121j2kkkmm1234](https://cloud.githubusercontent.com/assets/9053984/17396541/27071938-5a34-11e6-911b-06ac8b079072.png)

I'm running Arch linux and it can sometimes be a pain to work with

**Comment by smatthewenglish** [comment]
ah! SUCCESS! now it works! :)
![12121j2kkkmm1234](https://cloud.githubusercontent.com/assets/9053984/17396667/ba7e01f4-5a34-11e6-892a-4018321fabd2.png)

![12121j2kkkmm12345](https://cloud.githubusercontent.com/assets/9053984/17396671/bed4861a-5a34-11e6-9431-4a6e75312f19.png)

![12121j2kkkmm123456](https://cloud.githubusercontent.com/assets/9053984/17396677/c2f0da78-5a34-11e6-9657-ef7b4d3bcada.png)

**Comment by dshuffma-ibm** [comment]
congrats!
