### ISSUE TITLE
 deploy resp error - there is no chaincode hash name in response: { jsonrpc: '2.0',   error:     { code: -32001,      message: 'Deployment failure',

### ISSUE THREAD

**Issue by indirakalagara** [IBM-Blockchain-Archive/marbles#28]
Hi, I am getting the below error when trying to deploy the marbles application on local  vagrant environment. It was working fine before and I have n't modified any thing specifically except that IP addresses when I connect to different network. 

---

[ibc-js] Deploy Chaincode - Starting
[ibc-js]    function: init , arg: [ '99' ]

```
 Waiting...


 deploy resp error - there is no chaincode hash name in response: { jsonrpc: '2.0',
```

  error: 
   { code: -32001,
     message: 'Deployment failure',
     data: 'Error when deploying chaincode: Error getting chaincode package bytes: Error getting code Getting chaincode took too long' },
  id: 1470050652578 }
! looks like a deploy error, holding off on the starting the socket
 { name: 'deploy() error no cc name',
  code: 502,
  details: 
   { jsonrpc: '2.0',
     error: 
      { code: -32001,
        message: 'Deployment failure',
        data: 'Error when deploying chaincode: Error getting chaincode package bytes: Error getting code Getting chaincode took too long' },
     id: 1470050652578 } }

---

Please let me know what could be the reason for this issue and if any possible solution.

**Comment by dshuffma-ibm** [comment]
Sounds like your network is having networking/firewall/setup issues. Specifically the chaincode isn't able to communicate back to the peer (just a guess at this point).  

_"It was working fine before and I haven't modified any thing specifically except that IP addresses when I connect to different network."_

So if you didn't modify anything, except changing the IP? Does this mean you previously had this working with a **local** vagrant network, and you recently created a new local network? Try rebuilding this new network. Also are both networks running? (that may not be wise) Oh maybe you mean you changed the peer you are deploying too, but its all the same network?

```
there is no chaincode hash name in response:
```

That's always a bad sign, but I've seen it be intermittent. Try deploying the chaincode again if you haven't already.

**Comment by indirakalagara** [comment]
Thanks for the response. 

Pleas bear with as I am pretty new to Blockchain. 

Yes. It was working before on my local vagrant setup and tested the application as well. I have the Vagrant setup with 2 peers running.  Modified the files setup.js/ app.js/ mycreds.json as suggested to work with local setup.  
I am also suspecting that it could be a network issue...but not sure where should I look at it.  I have updated mycreds.json as well as setup.js file with the correct IP address.  

Once the vargrant is up, I create the peers by  issuing the docker run cmd as below which also starts the peer.  Is this leading to the above issue ??

docker run --rm -it -e CORE_VM_ENDPOINT=http://172.17.0.1:2375 -e CORE_PEER_ID=ind0 -e CORE_PEER_ADDRESSAUTODETECT=true hyperledger/fabric-peer peer node start

How do I just stop and start the same peer again , instead of creating the peers everytime.  

Thanks & Regards,
Indira.

**Comment by indirakalagara** [comment]
Hi,
 
Adding to my earlier update on github,  I have tested the same application again.
 
What I have noticed is,  in office network (LAN) the same marbles application deployed successfully. 
The only thing I modified is IP address for the (HOST & EXTUI ) in the setup.js  file under the section : 3.Localhost- Development. 
 
 
![image](https://cloud.githubusercontent.com/assets/15938882/17318577/dfdddc4e-58a4-11e6-9c59-f16b226ef1db.png)

 The same application at HOME network (either LAN or Wifi ) is not working.  The chaincode deploy is failing as posted earlier.   At home network I do NOT have any firewall configured.  Though it looks like a network issue, I am not sure what could be the real cause.  
 
Can you please help me to understand what could the be the issue and any pointers.
 
Thanks 
Indira

**Comment by dshuffma-ibm** [comment]
Ah that was a good test to run. You are confident there is **no** firewall blocking you?... The peer will reach out to github.com and download the marbles chaincode. Do you have any issues reaching github.com from home? 

You shouldn't need to change "HOST & EXTUI". Keep it localhost and localhost:3000. These are values for your marbles application and nothing to do with your blockchain network.

**Comment by indirakalagara** [comment]
Yes.  I could connect to github and even clone the application. You can see it in below image
 
 

 
What I suspect is -either I am doing some thing wrong with peer network or the it must be a timeout issue as shown in error message.
 
Just want to check with you if I am following the correct approach in creating the peers.
 
I use the below cmd to create and star the peer. 
docker run --rm -it -e CORE_VM_ENDPOINT=http://172.17.0.1:2375 -e CORE_PEER_ID=ind0 -e CORE_PEER_ADDRESSAUTODETECT=true hyperledger/fabric-peer peer node start
 
Similarly I create peer 2 with peer_id : ind1
 
After  this cmd , the peers created are the one in red., but doesn't show the peer ids as I have given. 
 

## docker ps -a 

 

## CONTAINER ID        IMAGE                                                                                                                                       COMMAND                  CREATED             STATUS                    PORTS               NAMES7d12d5a2eaef        hyperledger/fabric-peer                                                                                                                     "peer node start"        34 minutes ago      Up 34 minutes                                 tender_ramanujane7ea14a20c05        hyperledger/fabric-peer                                                                                                                     "peer node start"        35 minutes ago      Up 35 minutes                                 clever_thompson1ba8a670c055        dev-ind1-8c5677016abb7b4885b8dc40bb5b28f1554888cd766e2c945bc61bca03b349092f19197d32785254c692c9210db34c31821efc89e8a9f4dcb3f5575bebb4584b   "/opt/gopath/bin/8c56"   11 hours ago        Exited (0) 5 hours ago                        dev-ind1-8c5677016abb7b4885b8dc40bb5b28f1554888cd766e2c945bc61bca03b349092f19197d32785254c692c9210db34c31821efc89e8a9f4dcb3f5575bebb4584b1fb021087393        dev-ind0-8c5677016abb7b4885b8dc40bb5b28f1554888cd766e2c945bc61bca03b349092f19197d32785254c692c9210db34c31821efc89e8a9f4dcb3f5575bebb4584b   "/opt/gopath/bin/8c56"   11 hours ago        Exited (0) 5 hours ago                        dev-ind0-8c5677016abb7b4885b8dc40bb5b28f1554888cd766e2c945bc61bca03b349092f19197d32785254c692c9210db34c31821efc89e8a9f4dcb3f5575bebb4584ba7dbc3d1bfc4        hyperledger/fabric-peer                                                                                                                     "peer node start"        4 days ago          Exited (0) 30 hours ago                       modest_raman382d4f854a96        hyperledger/fabric-peer                                                                                                                     "peer node start"        4 days ago          Exited (0) 30 hours ago                       furious_morsea37f0871687d        dev-jdoe-28bb2b2316171a706bb2810ec35d095f430877bf443f1061ef0f60bbe753ed440700a5312c16390d3b30199fe9465c3b75d5944358caae01ca81ef28128a1bfb   "/opt/gopath/bin/28bb"   2 weeks ago         Exited (0) 2 weeks ago                        dev-jdoe-28bb2b2316171a706bb2810ec35d095f430877bf443f1061ef0f60bbe753ed440700a5312c16390d3b30199fe9465c3b75d5944358caae01ca81ef28128a1bfb

 
 
But there are  other images which already exists which are shown in green  above.  Those images are showing dev-ind0-xxxx and dev-ind1-xxx which contains the peer ids which I have used in the above cmd.   I am not sure how these 2 images are created.
 
Am I following the right approach to create the peers ?? 
 
Thanks & Regards, 
Indira,
 
 
----- Original message -----From: dshuffma-ibm notifications@github.comTo: IBM-Blockchain/marbles marbles@noreply.github.comCc: Indra S Kumari/India/IBM@IBMIN, Author author@noreply.github.comSubject: Re: [IBM-Blockchain/marbles] deploy resp error - there is no chaincode hash name in response: { jsonrpc: '2.0', error: { code: -32001, message: 'Deployment failure', (#28)Date: Tue, Aug 2, 2016 9:45 PM 
Ah that was a good test to run. You are confident there is no firewall blocking you?... The peer will reach out to github.com and download the marbles chaincode. Do you have any issues reaching github.com from home?
You shouldn't need to change "HOST & EXTUI". Keep it localhost and localhost:3000. These are values for your marbles application and nothing to do with your blockchain network.

**Comment by dshuffma-ibm** [comment]
sorry but I don't know, you may want to ask your question in the [hyperledger issues](https://github.com/hyperledger/fabric/issues)

**Comment by indirakalagara** [comment]
Sure. I will ask in hyperledger issues.

Thanks a lot for your help and support !
