### ISSUE TITLE
error when runntin marble

### ISSUE THREAD

**Issue by ghost** [IBM-Blockchain-Archive/marbles#282]
info: [EventHub.js]: _connect - options {"grpc.http2.keepalive_time":300,"grpc.keepalive_time_ms":300000,"grpc.http2.keepalive_timeout":35,"grpc.keepalive_timeout_ms":3500,"grpc.max_receive_message_length":-1,"grpc.max_send_message_length":-1}
error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: premature execution - chaincode (marbles:v4) is being launched
    at new createStatusError (/home/daily/Desktop/hyper/marbles/node_modules/grpc/src/client.js:64:15)
    at /home/daily/Desktop/hyper/marbles/node_modules/grpc/src/client.js:583:15
error: [fcw] Failed to obtain endorsement for transaction. code=2, , details=error executing chaincode: premature execution - chaincode (marbles:v4) is being launched
error: [fcw] Error in invoke catch block object code=2, , details=error executing chaincode: premature execution - chaincode (marbles:v4) is being launched
debug: [fcw] transaction event is disconnected
error: Exhausted all peers. There are no more peers to try.

error: error creating the marble owner { parsed: 'Blockchain network error - 4) is being launched',
  raw: 
   [ { Error: 2 UNKNOWN: error executing chaincode: premature execution - chaincode (marbles:v4) is being launched
    at new createStatusError (/home/daily/Desktop/hyper/marbles/node_modules/grpc/src/client.js:64:15)
    at /home/daily/Desktop/hyper/marbles/node_modules/grpc/src/client.js:583:15
       code: 2,
       metadata: [Object],
       details: 'error executing chaincode: premature execution - chaincode (marbles:v4) is being launched' } ] } id=o01552996702741bbX2S
error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: premature execution - chaincode (marbles:v4) is being launched
    at new createStatusError (/home/daily/Desktop/hyper/marbles/node_modules/grpc/src/client.js:64:15)
    at /home/daily/Desktop/hyper/marbles/node_modules/grpc/src/client.js:583:15
error: [fcw] Failed to obtain endorsement for transaction. code=2, , details=error executing chaincode: premature execution - chaincode (marbles:v4) is being launched
error: [fcw] Error in invoke catch block object code=2, , details=error executing chaincode: premature execution - chaincode (marbles:v4) is being launched
debug: [fcw] transaction event is disconnected
error: Exhausted all peers. There are no more peers to try.

error: error creating the marble owner { parsed: 'Blockchain network error - 4) is being launched',
  raw: 
   [ { Error: 2 UNKNOWN: error executing chaincode: premature execution - chaincode (marbles:v4) is being launched
    at new createStatusError (/home/daily/Desktop/hyper/marbles/node_modules/grpc/src/client.js:64:15)
    at /home/daily/Desktop/hyper/marbles/node_modules/grpc/src/client.js:583:15
       code: 2,
       metadata: [Object],
       details: 'error executing chaincode: premature execution - chaincode (marbles:v4) is being launched' } ] } id=o01552996702749VW11M

I did "install_chaincode", and "instantiate_chaincode", but there is no error.

But when i running "gulp marbles_local" and do guide step4(maybe register 3 users), this error is occur..

Need help ..

**Comment by dshuffma-ibm** [comment]
so `error executing chaincode: premature execution` is a Fabric error saying you have to wait a bit more for your chaincode to start.  it can take awhile depending on your environment and internet speed (2-10minutes). the peer needs to download some dependency images, which takes time.

**Comment by ghost** [comment]
Thanks, all problem is solved :)
