### ISSUE TITLE
not able to create CA using free kubernetes cluster on IBM blockchain Platform

### ISSUE THREAD

**Issue by tarandeeparora** [IBM-Blockchain-Archive/marbles#290]
I was following this  document to explore the blockchain platform
but seems like everything is different on ibm blockchain platform. Steps are completely different. I tried creating CA using free Kubernetes cluster in order to create Peers and Orders etc. But got error that "Cluster can't be created under free kubernetes cluster".

**Comment by dshuffma-ibm** [comment]
@tarandeeparora i'm afraid this repo is no longer maintained. its been archived, and left as is. it was written for the IBM Blockchain v1 service.

I suggest reading the read the [IBP v2 docs](https://cloud.ibm.com/docs/blockchain?topic=blockchain-get-started-ibp) for blockchain related questions.

however the error you are hitting doesn't sound IBP related... you can ask the [IBM cloud support](https://www.ibm.com/cloud/support) for more details, but I _think_ your error indicates you simply can't create the type of cluster you want w/o creating a paid kubernetes service.
