### ISSUE TITLE
Undefined setTimeout references in tutorial_part2.md

### ISSUE THREAD

**Issue by lehors** [IBM-Blockchain-Archive/marbles#3]
part2 makes two references to not using setTimeout() anymore but this is not something that is talked about in part1.
Either part1 needs to talk about setTimeout() so the reader understands the reference in part2 or part2 should not talk about it.

**Comment by dshuffma-ibm** [comment]
all done in https://github.com/IBM-Blockchain/marbles/commit/65bdc2750d9599c2023fa08d8d20d7a01e3d7fa5. 

the setTimeout() stuff was old and no longer in use in either part1 or part2.  To correct the tutorials I also moved a section from part2 into part1 (`monitor_blockheight()` section).  Then I added a little more info to part2.
