### ISSUE TITLE
[ibc-js] deploy - failure: 500 ! looks like a deploy error, holding off on the starting the socket.......many thanks for help

### ISSUE THREAD

**Issue by tonywang5671** [IBM-Blockchain-Archive/marbles#33]
# Hello sir......my environment is running Nodejs app on local and use Blockchain on Bluemix. I encounter an error in bellow when Nodejs app try to deploy chaincode....Please give some help, many thanks!

Running using Developer settings
- Tracking Deployment
  loading hardcoded peers
  loading hardcoded users
  [ibc-js] Peer:  vp0-e09125f8-45d...:30303
  [ibc-js] No membership users found after filtering, assuming this is a network w/o membership
  [ibc-js] removing temp dir
  [ibc-js] Downloading zip
  redirect... https://codeload.github.com/IBM-Blockchain/marbles-chaincode/zip/master
  [ibc-js] Downloading zip
  [ibc-js] Unzipping zip
  [ibc-js] Unzip done
  [ibc-js] Scanning files [ 'part2_chaincode.go' ]
  [ibc-js] Parsing file for shim version
  [ibc-js] Found shim version: github.com/hyperledger/fabric/core/chaincode/shim
  [ibc-js] Parsing file for invoke functions - part2_chaincode.go
  [ibc-js] Found cc invoke function:  init
  [ibc-js] Found cc invoke function:  delete
  [ibc-js] Found cc invoke function:  write
  [ibc-js] Found cc invoke function:  init_marble
  [ibc-js] Found cc invoke function:  set_user
  [ibc-js] Found cc invoke function:  open_trade
  [ibc-js] Found cc invoke function:  perform_trade
  [ibc-js] Found cc invoke function:  remove_trade
  [ibc-js] Parsing file for query functions - part2_chaincode.go
  [ibc-js] Found cc query function:  read
  [ibc-js] load_chaincode() finished
  [ibc-js] Deploy Chaincode - Starting
  [ibc-js]        function: init , arg: [ '99' ]
  
  ```
   Waiting...
  ```
  
  [ibc-js] deploy - failure: 500
  ! looks like a deploy error, holding off on the starting the socket
  { name: 'deploy() error',
  code: 500,
  details:
  { Error: socket hang up
     at createHangUpError (_http_client.js:252:15)
     at TLSSocket.socketOnEnd (_http_client.js:344:23)
     at emitNone (events.js:91:20)
     at TLSSocket.emit (events.js:185:7)
     at endReadableNT (_stream_readable.js:975:12)
     at _combinedTickCallback (internal/process/next_tick.js:74:11)
  #    at process._tickCallback (internal/process/next_tick.js:98:9) code: 'ECONNRESET' } }
  # It seems problem happen in user register....."No membership users found after filtering, assuming this is a network w/o membership". I modified mycreds.json by the user listed in Service Credentials page on Bluemix. Bellow is my mycreds.json
  
  {
  "credentials": {
    "peers": [
      {
        "discovery_host": "e09125f8-45df-4cce-96b5-8ce57858f622_vp0.us.blockchain.ibm.com",
        "discovery_port": 30303,
        "api_host": "e09125f8-45df-4cce-96b5-8ce57858f622_vp0.us.blockchain.ibm.com",
        "api_port_tls": 30303,
        "api_port": 443,
        "type": "peer",
        "network_id": "e09125f8-45df-4cce-96b5-8ce57858f622",
        "container_id": "ea18a428f5133461b99edcfbb4c59d2da6cce006ddcb252a4faf496b2fa13e06",
        "id": "e09125f8-45df-4cce-96b5-8ce57858f622_vp0",
        "api_url": "http://e09125f8-45df-4cce-96b5-8ce57858f622_vp0.us.blockchain.ibm.com:433"
      }
    ],
    "ca": {
      "e09125f8-45df-4cce-96b5-8ce57858f622_ca": {
        "url": "e09125f8-45df-4cce-96b5-8ce57858f622_ca.us.blockchain.ibm.com:30303",
        "discovery_host": "e09125f8-45df-4cce-96b5-8ce57858f622_ca.us.blockchain.ibm.com",
        "discovery_port": 30303,
        "api_host": "e09125f8-45df-4cce-96b5-8ce57858f622_ca.us.blockchain.ibm.com",
        "api_port_tls": 30303,
        "api_port": 433,
        "type": "ca",
        "network_id": "e09125f8-45df-4cce-96b5-8ce57858f622",
        "container_id": "3a17bd002c297e375190462377aa503a17cd2c9a53e13514f161e09bbad0772e"
      }
    },
    "users": [
      {
        "username": "user_type8_3b11bb4a7e",
        "secret": "2ae4ecee2f",
        "enrollId": "user_type8_3b11bb4a7e",
        "enrollSecret": "2ae4ecee2f"
      }
    ],
    "cert": "https://blockchain-certs.mybluemix.net/us.blockchain.ibm.com.cert"
  }
  # }
  # I had tried another user but still have other error. It look register error. 
  
  Running using Developer settings
- Tracking Deployment
  loading hardcoded peers
  loading hardcoded users
  [ibc-js] Peer:  vp0-e09125f8-45d...:30303
  [ibc-js] Registering  vp0-e09125f8-45d...:30303  w/enrollId - user_type1_270373e350
  [ibc-js] Register - failure x1 : user_type1_270373e350 500
  [ibc-js]        going to try to register again in 30 secs
  [ibc-js] Registering  vp0-e09125f8-45d...:30303  w/enrollId - user_type1_270373e350
  [ibc-js] Register - failure x2 : user_type1_270373e350 500
  ! looks like an error loading the chaincode or network, app will fail
  { name: 'register() error',
  code: 500,
  details:
  { Error: socket hang up
     at createHangUpError (_http_client.js:252:15)
     at TLSSocket.socketOnEnd (_http_client.js:344:23)
     at emitNone (events.js:91:20)
     at TLSSocket.emit (events.js:185:7)
     at endReadableNT (_stream_readable.js:975:12)
  ===============================================================
  But I can register this user by APIs page on Bluemix. It is strange.

Many thanks for advise!

**Comment by tonywang5671** [comment]
# After I deleted and create new blockchain then it appear another error in bellow.......can anyone help? thanks!

```
     deploy resp error - there is no chaincode hash name in response: { jsonrpc: '2.0',
```

  error:
   { code: -32602,
     message: 'Invalid params',
     data: 'Must supply username for chaincode when security is enabled.' },
  id: 1470318645781 }
! looks like a deploy error, holding off on the starting the socket
 { name: 'deploy() error no cc name',
  code: 502,
  details:
   { jsonrpc: '2.0',
     error:
      { code: -32602,
        message: 'Invalid params',
        data: 'Must supply username for chaincode when security is enabled.' },

#      id: 1470318645781 } }

**Comment by dshuffma-ibm** [comment]
The original error was that you were not giving an enroll ID with **type1** in the name, you had **type8**.

The second error might just be unlucky, try running it again.

**Comment by tonywang5671** [comment]
Hello sir, it works now. Many thanks!

**Comment by dshuffma-ibm** [comment]
great!
