### ISSUE TITLE
No route, failed deploy 

### ISSUE THREAD

**Issue by LexReg** [IBM-Blockchain-Archive/marbles#35]
Hello,

Have tried deploying to bluemix through the "deploy" button on git as well as within my blockchain network on bluemix. 

When deployed, I receive the following error upon opening the application:

{ "jsonrpc": "2.0", "error": { "code": -32001, "message": "Deployment failure", "data": "Error when deploying chaincode: Error getting chaincode package bytes: Error getting code 'go get' failed with error: 'exit status 1'\n# cd .; git clone https://github.com/ibm-blockchain/marbles-chaincode /go/_usercode_/435367883/src/github.com/ibm-blockchain/marbles-chaincode\nCloning into '/go/_usercode_/435367883/src/github.com/ibm-blockchain/marbles-chaincode'...\nfatal: unable to access 'https://github.com/ibm-blockchain/marbles-chaincode/': Failed to connect to github.com port 443: No route to host\npackage github.com/ibm-blockchain/marbles-chaincode/hyperledger/part2: exit status 128\n" }, "id": 1475514717593 }

Have I failed to do something rudimentary?

Thanks!

**Comment by MrBuggySan** [comment]
I have the same error trying to run the example just now. At the bottom of the error message it says "This application cannot run without the blockchain network :("

**Comment by g8rengr** [comment]
We believe there is a backend networking issue going on at the moment, I do not think this something either @MrBuggySan or @LexReg is doing wrong. The issue is being worked on.

**Comment by LexReg** [comment]
Just updating this morning, new error message as follows:

"chaincode is taking an unusually long time to start. this sounds like a network error, check peer logs"

I have checked myblockchain network and all peers are up; status is "running"

**Comment by dshuffma-ibm** [comment]
at the time you posted there were pretty sever slowness with Bluemix IBM Blockchain networks.  it has been fixed! feel free to try it again
