### ISSUE TITLE
Using Marbles demo with IBM Blockchain Local with hardcoded enrollId/Secret 

### ISSUE THREAD

**Issue by likepunk** [IBM-Blockchain-Archive/marbles#37]
Hello,

Can someone help replace enrollId/Seceret with hardcoded ones from Dockerized IBM Hyperledger from docker hub please?

I am trying to use marbles demo in local machine, first it was connected to HSBN/Bluemix okay. When I tried to use local version of hyperledger( https://hub.docker.com/r/ibmblockchain/ ) - it seems it has a problem using enrollId/Secret as local version's hardcoded id/key (changed in mycred.json) is different format - I see the document said it should contain 'type_1' in the enrollId. Can following key be used with minimal modification? this is from ver0.6 membersvc.yaml...

                test_user0: 1 MS9qrN8hFjlE bank_a
                test_user1: 1 jGlNl6ImkuDo institution_a
                test_user2: 1 zMflqOKezFiA bank_c
                test_user3: 1 vWdLCE00vJy0 bank_a
                test_user4: 1 4nXSrfoYGFCP institution_a
                test_user5: 1 yg5DVhm0er1z bank_b
                test_user6: 1 b7pmSxzKNFiw bank_a
                test_user7: 1 YsWZD4qQmYxo institution_a
                test_user8: 1 W8G0usrU7jRk bank_a
		test_user9: 1 H80SiB5ODKKQ institution_a

**Comment by dshuffma-ibm** [comment]
we updated ibc over the weekend. v1.3.0 no longer filters users out.  this should make it easier to use with networks hosted locally. i've also updated marbles to use the newest ibc.

please download [marbles branch v2.0](https://github.com/IBM-Blockchain/marbles/tree/v2.0) again.

**Comment by likepunk** [comment]
Thanks a lot!
