### ISSUE TITLE
Unable to deploy on bluemix

### ISSUE THREAD

**Issue by albertleIBM** [IBM-Blockchain-Archive/marbles#40]
Tried to deploy Marbles using: https://bluemix.net/deploy?repository=https://github.com/ibm-blockchain/marbles.git. It seems to never be able to connect to the blockchain.

**Comment by branciard** [comment]
Hi, Maybe it is linked to the recent change in the app.js. The default config was for 'bluemix' before and now it is the docker compose which is loaded by default. see: `
 var manual =JSON.parse(fs.readFileSync('mycreds_docker_compose.json', 'utf8'));
//var manual = JSON.parse(fs.readFileSync('mycreds_bluemix.json', 'utf8'));`

**Comment by albertleIBM** [comment]
I switched it over to the mycreds_bluemix.json but the issue still persists . Any other possible causes?

**Comment by branciard** [comment]
Maybe another cause : the Readme says that only 'Marbles - Branch v1.0' works with IBM Bluemix Blockchain Service. The master of marbles is at Hyperledger fabric v0.6 level. I do not know if IBM Bluemix Blockchain Service support it yet.

**Comment by albertleIBM** [comment]
I switched branches and it still doesn't seem to work.

**Comment by likepunk** [comment]
what's the error message? I had to modify user filtering section on node_modules/ibmblockchain/lib/helper.js ....changed 'user_type1' into whatever users defined in mycreds.json.

**Comment by likepunk** [comment]
I believe Bluemix is not v0.6 yet....

What's the error message you got?

**Comment by albertleIBM** [comment]
I checked the run time logs, and it doesn't show the errors, just when I try to use the demo, it never is able to connect to the blockchain

**Comment by likepunk** [comment]
do you mean not able to see service is up from web browser? or from local app.js?

**Comment by likepunk** [comment]
do you see run time logs showing 'user_type1' getting registered?

**Comment by dshuffma-ibm** [comment]
sorry for the confusion.  at the time you posted bluemix networks were not compatible with hyperledger v0.6 chaincode (like likepunk said).

new bluemix networks (as of last week) are compatible with v0.6. note that they are not backwards compatible with v0.5.3.

also the documentation has been restructured to help setup marbles in a more straight forward way. please update marbles and get a new network to try again.

**Comment by dshuffma-ibm** [comment]
closed inactivity
