### ISSUE TITLE
Proposed changes to marbles demo documentation.

### ISSUE THREAD

**Issue by ptippett** [IBM-Blockchain-Archive/marbles#41]
Here's a few changes I'd suggest to the getting started demo documentation.  To be clear, the path I followed was running marbles app on my local system using a blockchain network in bluemix.

1. Suggestion: Keep as much "informational" stuff out of the initial instructions as possible.  Too much information causes people to get confused IMO.  Not sure if they need to care about
certain things or if they are extra.

For example, get rid of the whole "chaincode" part of these instructions.  If they want to learn chaincode, they can do it via the link.  If they don't want to yet, this will just confuse them, especially with code snippets since they'll likely think they need to do these.  Flow should be context flows then setup options.

2.  All Screenshots and instructions need to be updated to match new UI.  I captured a few of these.

3.  In the instructions where you have "Keep creds at the default value" - There's only one but it's not selected.  You don't need to do anything here.  I'd clarify that.

4.  In the instructions where you tell the user to rename network to "my blockchain".  Can be renamed from bluemix dashboard.  Need to tell people how to get back and rename.  I wouldn't assume they know bluemix.

5.  In the doc where you tell user to "Copy the value of the whole JSON object to the mycreds.json file in the root of this project".  You haven't told them to clone the project yet at this point.  I'd either have them copy this off and save it locally somewhere "You'll use these credentials later" or more likely refer them back to how to get this information when they actually get to the point of editing the file after cloning the project.

6.  Where you tell them this "Next we need to install our dependencies. Open a command prompt/terminal and browse to the root of this project."  Give them the exact directory name.

7.  For this: 
> npm install gulp -g
> npm install

I see some warnings.  Need to tell them how to check if it worked or not or at least let them know about the warnings and what's OK vs what isn't.

8.  I'd have multiple sets of instructions for editing the JSON file..basically the section you have where you tell them "if your usecase is this, you need to edit the JSON file".  Expand each one of those to show exactly what they need to do for each usecase.  Part of the confusion I think comes from the fact that the instructions jump around between the different usecases.

9.  VCAP, define this and make it clear it's an environment variable everytime it's referenced and where it will be set and where it won't.

**Comment by ptippett** [comment]
I started working on this yesterday.  I can't assign it, but feel free.

**Comment by dshuffma-ibm** [comment]
all done in branch master and v2.0, thanks
