### ISSUE TITLE
In docker toolbox getting ECONNREFUSED error and registration failure

### ISSUE THREAD

**Issue by kmohanar** [IBM-Blockchain-Archive/marbles#48]
HI @dshuffma-ibm ,

i am trying to run marbles application using docker toolbox option in local.

While executing the gulp command in the prompt getting the ECONNREFUSED error and registration failure message.

My docker-compose.yml file looks like:

### membersrvc:
  image: hyperledger/fabric-membersrvc
  command: membersrvc
vp0:
  image: hyperledger/fabric-peer
  environment:
    - CORE_PEER_ADDRESSAUTODETECT=true
    - CORE_VM_ENDPOINT=http://172.17.0.1:2375
    - CORE_LOGGING_LEVEL=DEBUG
    - CORE_PEER_ID=vp0
    - CORE_PEER_PKI_ECA_PADDR=membersrvc:7054
    - CORE_PEER_PKI_TCA_PADDR=membersrvc:7054
    - CORE_PEER_PKI_TLSCA_PADDR=membersrvc:7054
    - CORE_SECURITY_ENABLED=true
    - CORE_SECURITY_ENROLLID=test_vp0
    - CORE_SECURITY_ENROLLSECRET=MwYpmSRjupbT
  links:
    - membersrvc
  command: sh -c "sleep 5; peer node start --peer-chaincodedev"

my mycreds_docker_compose.json file looks like:

### {
	"credentials": {
		"peers": [{
			"api_host": "localhost",
			"api_port": 7050,
			"type": "peer",
			"id": "vp0"
		}],
		"users": [{
			"enrollId": "bob",
			"enrollSecret": "NOE63pEQbL25"
		}],
	}
}

Can you please explain what are all the configuration changes need to do in the following files app.js, setup.js, docker-compose.yml and mycreds_docker_compose.json.

**Comment by dshuffma-ibm** [comment]
have you tried the new documentation? (its brand new, posted it yesterday)
https://github.com/IBM-Blockchain/marbles/blob/master/docs/use_local_hyperledger.md

if you are using docker toolbox then i'm assuming you are on windows. therefore the `api_host` param is not correct, it won't be on `localhost`. its probably on `192.168.99.100`. when you open the docker toolbox command prompt it will be there at the top:

![image](https://cloud.githubusercontent.com/assets/16085295/20527019/b7ef2682-b094-11e6-824c-5936476dca76.png)

**Comment by dshuffma-ibm** [comment]
closed inactivity
