### ISSUE TITLE
Local installation tutorial

### ISSUE THREAD

**Issue by ghost** [IBM-Blockchain-Archive/marbles#50]
Request: local (non-bluemix) installation tutorial with all the following configuration steps specified: 
1. docker-compose.yml
2. options in app.js
3. mycreds_docker json
4. os / environment (e.g. OSX / ubuntu / windows / vagrant)

that gets the demo working. See https://github.com/IBM-Blockchain/marbles/issues/13#issuecomment-268658306

**Comment by dshuffma-ibm** [comment]
could you point out which parts are missing? what did you have to do in docker-compose.yml?

2 and 3 should be taken care of by [this file](https://github.com/IBM-Blockchain/marbles/blob/v2.0/docs/use_local_hyperledger.md)

what is 4 referring to? are you asking for separate tutorials that are specific to each environment?

**Comment by ghost** [comment]
@dshuffma-ibm thanks for getting back on this. The file you linked does help, but unfortunately doesn't quite do it. I did make an attempt to write myself a tutorial like I was requesting, maybe someone else can finish it

## Tutorial attempt

The goal is to end up with a tutorial like [this](https://github.com/hyperledger/iroha/blob/master/docs/how_to_build.rst) 
which works **first time** to get the demo / blockchain running, with no additional troubleshooting. Below is an attempt, but unfortunately still unsuccessful. 

### Environment
ubuntu 16.04.1 server in virtualbox.

### Install docker

Install docker-engine
```
sudo apt install docker-engine
sudo service docker start
```

Install docker-compose [ref](https://docs.docker.com/compose/install)
```
sudo curl -L "https://github.com/docker/compose/releases/download/1.9.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo  chmod +x /usr/local/bin/docker-compose
```

### Get fabric
[ref](https://hub.docker.com/r/ibmblockchain/fabric-peer/)
```
git clone https://github.com/IBM-Blockchain/fabric-images.git
cd fabric-images/docker-compose
echo CORE_CHAINCODE_DEPLOYTIMEOUT="90000" >> setenv.sh
. setenv.sh
docker-compose -f four-peer-ca.yaml up
```
### Test fabric
```
wget http://localhost:7050/chain
cat chain
```
Output should be some JSON object with current block hash

### Install marbles
```
sudo apt install npm
sudo apt install nodejs-legacy
git clone https://github.com/IBM-Blockchain/marbles.git
cd marbles
npm i gulp -g
npm i 
```
### Edit mycreds
edit mycreds_docker_compose.json to look like the following:
```
{
        "credentials": {
                "peers": [{
                        "api_host": "localhost",
                        "api_port": 7050,
                        "type": "peer",
                        "id": "vp0"
                }],
                "users": [{
                        "enrollId": "bob",
                        "enrollSecret": "NOE63pEQbL25"
                }]
        }
}
```
### Start the app
```
gulp
```
output:
```
        deploy resp error - there is no chaincode hash name in response: { jsonrpc: '2.0',
  error:
   { code: -32001,
     message: 'Deployment failure',
     data: 'Error when deploying chaincode: Error getting chaincode package bytes: Error getting code Getting chaincode took too long' },
  id: 1483591736149 }
! looks like a deploy error, holding off on the starting the socket
 { name: 'deploy() error no cc name',
```

**Comment by ghost** [comment]
The markdown of above if someone wants to fix whatever I missed and add to the docs:
https://gist.github.com/divbit/470a86eb645bb25612bd22b7fd779672

Also btw, any other OS is fine - I just picked Ubuntu 16.04 as the environment, because it seems sort of easy to use.

**Comment by ghost** [comment]
Interesting - (with the above tutorial) I left the thing running, and took a shower and came back and it deployed chaincode successfully. It appears the last step is to wait 5-10 minutes. I'm not sure if this is desired behavior?

**Comment by dshuffma-ibm** [comment]
The deploy step will fail pretty often on the very first try, but be successfully if you simply retry it... i'll take a look at fixing that soon. It probably retried itself and that's why when you came back it was successful.. 

thanks for the write up, i'll also try to include aspects of it.

**Comment by ghost** [comment]
Thanks for the help- feel free to delete the anakin gif from the md gist, I was excited to finally get it running :)
