### ISSUE TITLE
Refactor to use hfc

### ISSUE THREAD

**Issue by sibelius** [IBM-Blockchain-Archive/marbles#51]
as fabric v0.7+ no longer has REST apis, so we should use `hfc` package instead of `ibm-blockchain-js`

**Comment by mrshah-at-work** [comment]
Please have a look at https://github.com/IBM-Blockchain/marbles/tree/v3.0 for the marbles with fabric v0.7+. We will be waiting for a release of fabric to move it to master.

**Comment by dshuffma-ibm** [comment]
also note instructions for how to use v3.0 marbles are coming soon (its very different).
