### ISSUE TITLE
read property '0' undefined

### ISSUE THREAD

**Issue by leobekhuis** [IBM-Blockchain-Archive/marbles#56]
Hi I am little bit confused about the marble tutorial

npm install
gulp 

its done here locally on osx yosemite with the blockchain hyperledger api connectivity
the mycreds_bluemix.json is correctly filled with credentials and users  (user_type1_0 plus the secret)

I am experiencing this nodejs error and I can understand why.

TypeError: Cannot read property '0' of undefined
    at Object.<anonymous> (/.../marbles.v2/app.js:218:20)

node -v
v7.2.1

npm -v
4.1.1

looking at the line mentioned in code snippet:  peers: [peers[0]],

thanks

**Comment by mychewcents** [comment]
I had this same issue.
Check the mycreds_docker_compose.json file.
There is an extra comma after "users" field. Remove that and it will work just fine.

If the error still persists, check whether are you able to run JSON.parse command in nodejs. In not, try reinstalling it from scratch and it will work.

Thanks

**Comment by dshuffma-ibm** [comment]
along those lines you can test if something is valid JSON quickly here: http://jsonlint.com/

also if there is a bug in the vanilla code, let me know or better yet make a PR
