### ISSUE TITLE
error deploying chaincode at node startup - chaincode took too long

### ISSUE THREAD

**Issue by vincentserpoul** [IBM-Blockchain-Archive/marbles#58]
on a local single node setup, I get this error:
```
	 deploy resp error - there is no chaincode hash name in response: { jsonrpc: '2.0',
  error:
   { code: -32001,
     message: 'Deployment failure',
     data: 'Error when deploying chaincode: Error getting chaincode package bytes: Error getting code Getting chaincode took too long' },
  id: 1484720495587 }
! looks like a deploy error, holding off on the starting the socket
 { name: 'deploy() error no cc name',
  code: 502,
  details:
   { jsonrpc: '2.0',
     error:
      { code: -32001,
        message: 'Deployment failure',
        data: 'Error when deploying chaincode: Error getting chaincode package bytes: Error getting code Getting chaincode took too long' },
     id: 1484720495587 } }
```

**Comment by dshuffma-ibm** [comment]
do you know if this network is setup correctly? have you deployed other chaincode on this network before, such as [example02](https://github.com/IBM-Blockchain/example02)?

you will likely need to look at the logs in the peer to see the root cause of `getting code Getting chaincode took too long`. could be a networking problem or bad deployment parameters,

**Comment by vincentserpoul** [comment]
I can deploy example02.

Here are the logs:

```
17:51:15.201 [rest] Register -> INFO 530 REST client login...
17:51:15.202 [rest] Register -> INFO 531 Local data store for client loginToken: /var/hyperledger/production/client/
17:51:15.202 [rest] Register -> INFO 532 User 'bob' is already logged in.
17:51:22.854 [rest] ProcessChaincode -> INFO 533 REST processing chaincode request...
17:51:22.854 [rest] processChaincodeDeploy -> INFO 534 REST deploying chaincode...
17:51:22.855 [rest] processChaincodeDeploy -> INFO 535 Local user 'bob' is already logged in. Retrieving login token.
17:51:22.855 [devops] getChaincodeBytes -> DEBU 536 Received build request for chaincode spec: type:GOLANG chaincodeID:<path:"http://gopkg.in/ibm-blockchain/marbles.v2/chaincode" > ctorMsg:<args:"init" args:"99" > secureContext:"bob"
17:51:22.855 [golang/hash] getCodeFromHTTP -> DEBU 537 getCodeFromHTTP gopkg.in/ibm-blockchain/marbles.v2/chaincode
17:51:22.856 [golang/hash] getCodeFromHTTP -> DEBU 538 go get gopkg.in/ibm-blockchain/marbles.v2/chaincode
17:51:42.167 [peer] ensureConnected -> DEBU 539 Touch service indicates no dropped connections
17:51:42.167 [peer] ensureConnected -> DEBU 53a Connected to: []
17:51:42.167 [peer] ensureConnected -> DEBU 53b Discovery knows about: []
17:51:52.861 [devops] getChaincodeBytes -> ERRO 53c Error getting chaincode package bytes: Error getting code Getting chaincode took too long
17:51:52.862 [devops] Deploy -> ERRO 53d Error deploying chaincode spec: type:GOLANG chaincodeID:<path:"http://gopkg.in/ibm-blockchain/marbles.v2/chaincode" > ctorMsg:<args:"init" args:"99" > secureContext:"bob"

 error: Error getting chaincode package bytes: Error getting code Getting chaincode took too long
17:51:52.862 [rest] processChaincodeDeploy -> ERRO 53e Error when deploying chaincode: Error getting chaincode package bytes: Error getting code Getting chaincode took too long
17:51:52.862 [rest] ProcessChaincode -> INFO 53f REST successfully deploy chaincode: {"jsonrpc":"2.0","error":{"code":-32001,"message":"Deployment failure","data":"Error when deploying chaincode: Error getting chaincode package bytes: Error getting code Getting chaincode took too long"},"id":1484761882851}
17:56:43.169 [peer] ensureConnected -> DEBU 540 Touch service indicates no dropped connections
17:56:43.169 [peer] ensureConnected -> DEBU 541 Connected to: []
17:56:43.169 [peer] ensureConnected -> DEBU 542 Discovery knows about: []
```

**Comment by dshuffma-ibm** [comment]
try bumping up [deploytimeout](https://github.com/hyperledger/fabric/blob/v0.6/peer/core.yaml#L314) to `120000`

**Comment by vincentserpoul** [comment]
That would mean rebuilding the whole docker image... 
I'll try to do it later

**Comment by mrshah-at-work** [comment]
you can increase it by passing environment variable `CORE_CHAINCODE_DEPLOYTIMEOUT=120000`. You don't need to rebuild the image

**Comment by vincentserpoul** [comment]
the env variable setup worked but it is still timing out.
I tried to run the go get command directly from my computer, and after a very long time (like 2mn, I got this error)

```
$ go get gopkg.in/ibm-blockchain/marbles.v2/chaincode

# gopkg.in/ibm-blockchain/marbles.v2/chaincode
go/src/gopkg.in/ibm-blockchain/marbles.v2/chaincode/marbles_chaincode.go:67: cannot use new(SimpleChaincode) (type *SimpleChaincode) as type shim.Chaincode in argument to shim.Start:
	*SimpleChaincode does not implement shim.Chaincode (wrong type for Init method)
		have Init(shim.ChaincodeStubInterface, string, []string) ([]byte, error)
		want Init(shim.ChaincodeStubInterface) ([]byte, error)
```

```
go version 
go1.7.4 darwin/amd64
```

**Comment by dshuffma-ibm** [comment]
you have mismatching hyperledger versions. since you are using the branch v2.0 you must use hyperledger **fabric v0.6.x**.  If you have 0.7.x or 0.5.x fabric it will not work b/c they changed the chaincode stub interfaces.

**Comment by vksuktha** [comment]
I guess I too hit upon this issue..
cache busting hash js 5f0791a56911bb2a730efb972c0441ce css 5c5213ec16de93e801c4aaf7a7eb956b
------------------------------------------ Server Up - localhost:3000 ------------------------------------------
Running using Developer settings
- Tracking Deployment
loading hardcoded peers
loading hardcoded users
[ibc-js] Peer:  vp0-vp0...:7050
[ibc-js] Registering  vp0-vp0...:7050  w/enrollId - bob
[ibc-js] Registration success x1 : bob
[ibc-js] removing temp dir
[ibc-js] Downloading zip
redirect... https://codeload.github.com/IBM-Blockchain/marbles/zip/v2.0
[ibc-js] Downloading zip
[ibc-js] Unzipping zip
[ibc-js] Unzip done
[ibc-js] Scanning files [ 'marbles_chaincode.go' ]
[ibc-js] Parsing file for shim version
[ibc-js] Found shim version: github.com/hyperledger/fabric/core/chaincode/shim
[ibc-js] Parsing file for invoke functions - marbles_chaincode.go
[ibc-js] Found cc invoke function:  init
[ibc-js] Found cc invoke function:  delete
[ibc-js] Found cc invoke function:  write
[ibc-js] Found cc invoke function:  init_marble
[ibc-js] Found cc invoke function:  set_user
[ibc-js] Found cc invoke function:  open_trade
[ibc-js] Found cc invoke function:  perform_trade
[ibc-js] Found cc invoke function:  remove_trade
[ibc-js] Parsing file for query functions - marbles_chaincode.go
[ibc-js] Found cc query function:  read
[ibc-js] load_chaincode() finished
[ibc-js] Deploy Chaincode - Starting
[ibc-js] 	function: init , arg: [ '99' ]
Waiting...


	 deploy resp error - there is no chaincode hash name in response: { jsonrpc: '2.0',
  error: 
   { code: -32001,
     message: 'Deployment failure',
     data: 'Error when deploying chaincode: Error getting chaincode package bytes: Error getting code Getting chaincode took too long' },
  id: 1485866761810 }
! looks like a deploy error, holding off on the starting the socket
 { name: 'deploy() error no cc name',
  code: 502,
  details: 
   { jsonrpc: '2.0',
     error: 
      { code: -32001,
        message: 'Deployment failure',
        data: 'Error when deploying chaincode: Error getting chaincode package bytes: Error getting code Getting chaincode took too long' },
     id: 1485866761810 } }

The hyperledger fabric version is v0.6.1-preview. I also tested the Rest calls to Query Chaincode and it returns fine.

**Comment by dshuffma-ibm** [comment]
@vksuktha  did you try the solutions in this thread yet?
```
you can increase it (the timeout) by passing environment variable CORE_CHAINCODE_DEPLOYTIMEOUT=120000. You don't need to rebuild the image
```

or

```
try bumping up deploytimeout https://github.com/hyperledger/fabric/blob/v0.6/peer/core.yaml#L314 to `120000` 
```

**Comment by vincentserpoul** [comment]
none of these solutions solve the issue on my side

**Comment by vksuktha** [comment]
These commands do not work for me too.

Sent from Yahoo Mail on Android 
 
  On Wed, Feb 1, 2017 at 8:28 PM, Vincent Serpoul<notifications@github.com> wrote:   
none of these commands solve the issue on my side

**Comment by dshuffma-ibm** [comment]
well they aren't commands. the first one is an environmental variable you should set. the command would be `export CORE_CHAINCODE_DEPLOYTIMEOUT=500000`. 

and the 2nd method is to change the .yaml file and rebuild.

i'm also going to suggest bumping it up even farther to 500 seconds.  time it yourself to make sure your setting is actually getting applied. You could also time how long it takes to clone marbles locally and set your timeout to 1.5 times that.

**Comment by vksuktha** [comment]
I could get this working by adding CORE_CHAINCODE_DEPLOYTIMEOUT=1000000. That was a random number I selected.

**Comment by vksuktha** [comment]
bumping the timeout worked for me. Thanks
