### ISSUE TITLE
Always failing to Register user with gulp

### ISSUE THREAD

**Issue by ykcai** [IBM-Blockchain-Archive/marbles#59]
```
[ibc-js] Registering  eedd070b694947d382a9aace7bb52783-vp2-eedd070b6949...:5004  w/enrollId - user_type1_0
Register - failure x1 : user_type1_0 401
! looks like an error loading the chaincode or network, app will fail
 { name: 'register() error',
  code: 401,
  details: { Error: 'rpc error: code = 2 desc = Identity or token does not match.' } }
```

**Comment by dshuffma-ibm** [comment]
the error code 401 would indicate your enroll ID and secret do not match what the membership services expects. (also the log below that says it)

if you are using a local network: follow the [tutorial](https://github.com/IBM-Blockchain/marbles/blob/master/docs/use_local_hyperledger.md#finished)

if you are using a bluemix network: follow the [tutorial](https://github.com/IBM-Blockchain/marbles/blob/master/docs/use_bluemix_hyperledger.md)

**Comment by ykcai** [comment]
Realized I was using a pre-existing service that already had registered users, maybe thats why it didn't work. Anyways, create a new service and it works fine. Thanks!

**Comment by dshuffma-ibm** [comment]
cool, np
