### ISSUE TITLE
"Docker QuickStart Terminal" is needed on Windows 10 

### ISSUE THREAD

**Issue by chengxing1987** [IBM-Blockchain-Archive/marbles#62]
Could it be specifically suggested in the tutorial or trouble shooting so that users will not waste too much time trying cmd or powershell?

**Comment by dshuffma-ibm** [comment]
those instructions wouldn't belong here.  running marbles does not require `docker` nor `docker-toolbox`.

all the commands i'm aware of in the marbles instructions would work across any OS with the proper installations of git/node/npm. no special terminals needed.  

Maybe you are referring to commands from a different repository?

**Comment by chengxing1987** [comment]
According to the experience from Bluemix support, some steps are proved to be a bit tricky on Windows 10. For example, to use a locally hosted Hyperledger Network, from https://hub.docker.com/r/ibmblockchain/fabric-peer, the setenv.sh cannot be used on Windows.
