### ISSUE TITLE
v3 docker network cannot be set up as COP enrollment credentials not available

### ISSUE THREAD

**Issue by snoeber** [IBM-Blockchain-Archive/marbles#65]
Hi,

I'd like to set up a local network for deploying the marbles app in version 3 as described at:
https://github.com/IBM-Blockchain/marbles/blob/v3.0/docs/use_local_hyperledger.md

The referenced connecathon setup uses a hosted COP server which is behind a firewall. To access this credentials are required, that only have been provided to the participants.

Could you please provide those or explain another way to set up such a network.

Thank you in advance,
kc

**Comment by dshuffma-ibm** [comment]
sorry but so far the connect-a-thon experience is only for those that were invited. 

marbles v3.0 will not work with the current master branch of hyperledger fabric... marbles will be updated to work with the [hackfest](http://hyperledger-fabric.readthedocs.io/en/latest/gettingstarted/) hyperledger fabric docker images, but that work has not yet started. I am planning to start the work this week. I'll update this issue when its done.

**Comment by dshuffma-ibm** [comment]
this tagged works with connnect-a-thon: https://github.com/IBM-Blockchain/marbles/releases/tag/v3.0.2

and the latest v3.0 works with the IBM Blockchain Service vNext
