### ISSUE TITLE
Not found manifest for ibmblockchain/fabric-membersrvc:latest

### ISSUE THREAD

**Issue by raderio** [IBM-Blockchain-Archive/marbles#66]
> sudo docker-compose -f four-peer-ca.yaml up
> WARNING: The ARCH_TAG variable is not set. Defaulting to a blank string.
> Pulling membersrvc (ibmblockchain/fabric-membersrvc:latest)...
> ERROR: manifest for ibmblockchain/fabric-membersrvc:latest not found

from [https://hub.docker.com/r/ibmblockchain/fabric-peer/](https://hub.docker.com/r/ibmblockchain/fabric-peer/)

**Comment by raderio** [comment]
Works only if I run as sudo

**Comment by dshuffma-ibm** [comment]
I can't update those instructions. But since you made the issue maybe other can find this.

use `sudo` to launch docker-compose
