### ISSUE TITLE
Error loading the chaincode or network

### ISSUE THREAD

**Issue by raderio** [IBM-Blockchain-Archive/marbles#67]
> ------------------------------------------ Server Up - localhost:3000 ------------------------------------------
> Running using Developer settings
> - Tracking Deployment
> loading hardcoded peers
> loading hardcoded users
> [ibc-js] Peer:  vp0-vp0...:7050
> [ibc-js] Registering  vp0-vp0...:7050  w/enrollId - bob
> [ibc-js] Register - failure x1 : bob 401
> [ibc-js] 	going to try to register again in 30 secs
> [ibc-js] Registering  vp0-vp0...:7050  w/enrollId - bob
> [ibc-js] Register - failure x2 : bob 401
> ! looks like an error loading the chaincode or network, app will fail
>  { name: 'register() error',
>   code: 401,
>   details: { Error: 'rpc error: code = 2 desc = Identity or token does not match.' } }

> {
> 	"credentials": {
> 		"peers": [{
> 			"api_host": "localhost",
> 			"api_port": 7050,
> 			"type": "peer",
> 			"id": "vp0"
> 		}],
> 		"users": [{
> 			"enrollId": "bob",
> 			"enrollSecret": "NOE63pEQbL25"
> 		}],
> 		"cert": "https://blockchain-certs.mybluemix.net/us.blockchain.ibm.com.cert"
> 	}
> }

Also I get
> Error creating connection to peer address 172.20.0.7:7051: grpc: timed out when dialing
in console when I run "docker-compose -f four-peer-ca.yaml up"

**Comment by dshuffma-ibm** [comment]
you need to change the credentials file.  looks like you are using marbles v2.0 and using a locallly hosted network? if so look at [these instructions](https://github.com/IBM-Blockchain/marbles/blob/v2.0/docs/use_local_hyperledger.md) about the mycreds file
