### ISSUE TITLE
Marbles timeout

### ISSUE THREAD

**Issue by TheCodeBuccaneer** [IBM-Blockchain-Archive/marbles#70]
> **When I try to run marbles (version 2) using the gulp command I get the below error. I am running fabric locally using vagrant.**

[ibc-js] Deploy Chaincode - Starting
[ibc-js]        function: init , arg: [ '99' ]

Waiting...

[http POST - y] localhost:7050
[http POST - y] /chaincode
  body: {"jsonrpc":"2.0","method":"deploy","params":{"type":1,"chaincodeID":{"path":"http://gopkg.in/ibm-blockchain/marbles.v2/chaincode"},"ctorMsg":{"function":"init","args":["99"]},"secureContext":"bob"},"id":XXXXXXXXXXX}

[http POST - y] Error - request timed out
[ibc-js] deploy - failure: 408
! looks like a deploy error, holding off on the starting the socket
 { name: 'deploy() error',
  code: 408,
  details: 'Request timed out' }
[http POST - y] Error - request timed out
[http POST - y] Status code: 200

> **I changed the content of 'mycreds_docker_compose.json" to:**

{
	"credentials": {
		"peers": [{
			"api_host": "localhost",
			"api_port": 7050,
			"type": "peer",
			"id": "vp0"
		}],
		"users": [{
			"enrollId": "bob",
			"enrollSecret": "NOE63pEQbL25"
		}],
		"cert": "https://blockchain-certs.mybluemix.net/us.blockchain.ibm.com.cert"
	}
}

And the command to start the peer is:
peer node start --logging-level=DEBUG

And in the app.js I changed 
deploytimeout: 30000
to
deploytimeout: 120000

> **As otherwise I received the bellow error:**

[ibc-js] Deploy Chaincode - Starting
[ibc-js]        function: init , arg: [ '99' ]

Waiting...
deploy resp error - there is no chaincode hash name in response: { json   rpc: '2.0',
  error:
   { code: -32001,
     message: 'Deployment failure',
     data: 'Error when deploying chaincode: Error getting chaincode package byte   s: Error getting code Getting chaincode took too long' },
  id: 1489827931548 }
! looks like a deploy error, holding off on the starting the socket
 { name: 'deploy() error no cc name',
  code: 502,
  details:
   { jsonrpc: '2.0',
     error:
      { code: -32001,
        message: 'Deployment failure',
        data: 'Error when deploying chaincode: Error getting chaincode package b   ytes: Error getting code Getting chaincode took too long' },
     id: 1489827931548 } }

**Comment by dshuffma-ibm** [comment]
see this issue, and bump up the timeout: https://github.com/IBM-Blockchain/marbles/issues/58
