### ISSUE TITLE
docker-compose error: manifest for ibmblockchain/fabric-membersrvc: latest not found

### ISSUE THREAD

**Issue by qianlizimu** [IBM-Blockchain-Archive/marbles#73]
I used Docker Toolbox on Windows 7 and I followed the guide of IBM blockchain to pull the heyperledger fabric. When I ran the "docker-compose -f single-peer-ca.yaml up" command, I found this error message: 
[31mERROR[0m: **manifest for ibmblockchain/fabric-membersrvc: latest not found**
I ran "docker images" command and saw that the tag of "**ibmblockchain/fabric-membersrvc**" was "**x86_64-0.6.1-preview**" (it is indeed not the latest) and  the tag of "ibmblockchain/fabric-peer" was also x86_64-0.6.1-preview.
How to make them the latest? Thanks!

**Comment by dshuffma-ibm** [comment]
This is beyond my knowledge.  You should post this error in the [fabric-images repo](https://github.com/IBM-Blockchain/fabric-images).

**Comment by qianlizimu** [comment]
OK, Thanks!
