### ISSUE TITLE
How to host marbles locally?

### ISSUE THREAD

**Issue by bh4rtp** [IBM-Blockchain-Archive/marbles#74]
I run `npm install` and `gulp marbles1`. And open web browser with url `http://localhost:3001/`. In the browser, login with admin. The console side outputs many errors:
```
error: Error: Calling enrollment endpoint failed with error [Error: connect ECONNREFUSED 127.0.0.1:7054]
    at ClientRequest.<anonymous> (/home/allen/gopath/src/github.com/hyperledger/marbles/node_modules/fabric-ca-client/lib/FabricCAClientImpl.js:568:12)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1278:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
error: [fcw] Failed to get enrollment marbles-marbles-ibm-mychannel-fabric-peer-1a Error: Failed to obtain an enrolled user
    at ca_client.enroll.then.then.then.catch (/home/allen/gopath/src/github.com/hyperledger/marbles/utils/fc_wrangler/enrollment.js:131:12)
    at process._tickCallback (internal/process/next_tick.js:103:7)
error: [fcw] could not format error
error: could not enroll...
```
Run `docker ps -a`, I can not find any containers running. Does marbles need start docker-compose blockchain network first before running `gulp marbles1`? And how to host marbles locally? And most of most, does marbles support the latest fabric 1.0.0 release? Please give us some instructions.

**Comment by dshuffma-ibm** [comment]
if you skip any [instructions](https://github.com/IBM-Blockchain/marbles/blob/v3.0/docs/tutorial_start_here.md#marbles-setup-options) you are going to have a hard time getting it to work. 

- yes marbles v3.0 works with fabric 1.0.0
- marbles cannot help you start/build your network. if you are not using the bluemix service you are on your own, for now. any questions related to a local network via docker-compose will have to wait until thats offically supported/documented
- `gulp marbles1` **is** hosting marbles locally

**Comment by bh4rtp** [comment]
Thanks. I have cloned v3.0.2. The sfhackfest example is used to build blockchain networking. Then `gulp united_marbles` can run almost ok. But there are two problems. One is the endorsement demonstration stops to response when creating, deleting, and transferring marbles. The other is `error: [Chain.js]: Orderer with URL grpc://127.0.0.1:8050 already exists` when deploying chaincode at step 2 of setup.

**Comment by bh4rtp** [comment]
I find the latest marbles v3.0 does not have Deploy button in the home page, while v3.0.2 has. Does this mean the latest version does not support install and instantiate locally hosted chaincode?

**Comment by dshuffma-ibm** [comment]
correct.  more importantly there is no longer a "deploy" tx in v1.0 fabric.  it is now two steps.  1 is called `install` and the other is `instantiate`.  the new order is to:

1. Install - this step copies the chaincode source files into the peer
2. Instantiate - this will onboard the chaincode for a particular channel

both operations are supported by the [SDK](https://github.com/hyperledger/fabric-sdk-node), but marbles no longer demonstrates this.  we are favoring the Bluemix Blockchain Service UI for install + instantiate.

**Comment by bh4rtp** [comment]
Thanks.
I am try to learn your implements. Could you tell me how the marbles v3.0  pushs forward after each step succeeds and communicates the blockchain operation states between server and client?

**Comment by dshuffma-ibm** [comment]
Its using a websocket.  The websocket startup code is in `app.js` line 400 and in `/utils/websocket_server_side.js`.  The client side code is in `public/js/websocket.js`. 

The server sends a `state` messages as it moves through enrollment -> finding chaincode -> building assets.

**app.js line 371**
```js
//send to all connected clients
function broadcast_state(new_state) {
	process.env.app_state = new_state;
	wss.broadcast(build_state_msg());	    //tell client our app state
}
```

**Comment by bh4rtp** [comment]
Thanks.

**Comment by habpy** [comment]
@dshuffma-ibm
I’m following the Marbles on Bluemix (command line) instructions. It states

1. Well to do this correctly you need to first run marbles locally.

2. Seriously make sure marbles on your local machine starts up completely and you have traded a marble successfully before you continue.

after a run `gulp marbles1` and try to login as admin I get exactly the same error as @bh4rtp. 

Could you please explain what the probable cause is? What do I have to check in the enrollID and enrollSecret fields in the `blockchain_creds1.json` file as is suggested in the instructions?

**Comment by hots-sho** [comment]
The setup link is not working anymore. Can someone post the latest setup link?
