### ISSUE TITLE
error deploying chaincode at node startup - 

### ISSUE THREAD

**Issue by tonyltf** [IBM-Blockchain-Archive/marbles#75]
Hi all, on the local blockchain, I tried to deploy the marbles v2 but it failed.
I failed with #58 before and it was resolved after setting the CORE_CHAINCODE_DEPLOYTIMEOUT. And then I met this error after the deploy was said to be success. After a number of retrying, it stopped and the deploy is not completed at the end.
![2017-03-30 18_25_57-tony ubuntu_ _marbles v2](https://cloud.githubusercontent.com/assets/6047077/24500007/5a89aafc-1576-11e7-8f80-98494eff29e4.png)
![2017-03-30 18_33_14-tony ubuntu_ _marbles v2](https://cloud.githubusercontent.com/assets/6047077/24500294/60310b98-1577-11e7-9ab1-ac35f07cad29.png)

----------------------------------------------------------------------------------------------------------------
[ibc-js] Deploy Chaincode - Starting
[ibc-js]        function: init , arg: [ '99' ]

         Waiting...

         deploy success [waiting another 30 seconds]
         16e655c0fce6a9882896d3d6d11f7dcd4f45027fd4764004440ff1e61340910a9d67685c4bb723272a497f3cf428e6cf6b009618612220e1471e03b6c0aa76cb

[ibc-js] Deploy Chaincode - Complete
[preflight check] 1 : testing if chaincode is ready
[ibc-js] read  - success: { jsonrpc: '2.0',
  error:
   { code: -32003,
     message: 'Query failure',
     data: 'Error when querying chaincode: Error:Failed to launch chaincode spec(Could not get deployment transaction for 16e655c0fce6a9882896d3d6d11f7dcd4f45027fd4764004440ff1e61340910a9d67685c4bb723272a497f3cf428e6cf6b009618612220e1471e03b6c0aa76cb - LedgerError - ResourceNotFound: ledger: resource not found)' },
  id: 1490868623171 }
[preflight check] 1 : failed, trying again
[preflight check] 2 : testing if chaincode is ready

----------------------------------------------------------------------------------------------------------------
on the peer I saw there are new blocks after each time the deploy was said to success
(on localhost:7050/chain/blocks/{X})

Does anyone have idea why the "testing" is failed?

More information:
I host the hyperledger fabric from hyperledger's dockerhub image, running on a Ubuntu VM over my PC.

The docker-compose.yml is:

         vp0:
           image: hyperledger/fabric-peer
           ports:
             - "7050:7050"
             - "7051:7051"
             - "7052:7052"
           environment:
             - CORE_PEER_ID=vp0
             - CORE_PEER_ADDRESSAUTODETECT=true
             - CORE_VM_ENDPOINT=http://172.17.0.1:2375
             - CORE_LOGGING_LEVEL=DEBUG
             - CORE_CHAINCODE_DEPLOYTIMEOUT=500000
           command: peer node start

the mycred_docker_compose.json is

         {
                 "credentials": {
                         "peers": [{
                                 "api_host": "172.17.0.2",
                                 "api_port": 7050,
                                 "type": "peer",
                                 "id": "vp0"
                         }],
                         "users": []
                 }
         }

**Comment by dshuffma-ibm** [comment]
Check the logs on the peer (the port 7050 peer). The peer might be having some issue with starting the container for the chaincode.

You might be able to get logs for the chaincode container itself, if it made it that far.  Looked for stopped containers with `docker ps -a` and ones that have names similar to that long hash `16e655c0fce..`

**Comment by tonyltf** [comment]
@dshuffma-ibm  sorry for late reply as I was out of office for few days...
I got the log by command `docker logs <container ID>`
> 01:12:58.705 [dockercontroller] deployImage -> ERRO 070 Error building images: cannot connect to > Docker endpoint
01:12:58.706 [dockercontroller] deployImage -> ERRO 071 Image Output:
\********************
\
\********************

And then I tried to change my docker-compose.yml to
> vp0:
  image: hyperledger/fabric-peer
  ports:
    - "7050:7050"
    - "7051:7051"
    - "7052:7052"
  environment:
    - CORE_PEER_ID=vp0
    - CORE_PEER_ADDRESSAUTODETECT=true
    #- CORE_VM_ENDPOINT=http://172.17.0.1:2375
    - CORE_VM_ENDPOINT=unix:///var/run/docker.sock
    - CORE_LOGGING_LEVEL=DEBUG
    - CORE_CHAINCODE_DEPLOYTIMEOUT=500000
  command: peer node start

It comes another error 
> 01:19:42.488 [dockercontroller] deployImage -> ERRO 073 Error building images: dial unix /var/run/docker.sock: connect: no such file or directory

while `/var/run/docker.sock`  actually exists

**Comment by tonyltf** [comment]
I found some hints from the fabric-composer project sample's setup, here is my final docker-compose.yml

The marbles demo can be started using this config. 

> vp0:
  image: hyperledger/fabric-peer
  ports:
    - "7050:7050"
    - "7051:7051"
    - "7052:7052"
  environment:
    - CORE_PEER_ID=vp0
    - CORE_PEER_ADDRESSAUTODETECT=true
    - CORE_VM_ENDPOINT=unix:///var/run/docker.sock
    - CORE_LOGGING_LEVEL=DEBUG
    - CORE_CHAINCODE_DEPLOYTIMEOUT=500000
  command: peer node start
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock

Thanks for your help!
