### ISSUE TITLE
Doesn't work with grpcs

### ISSUE THREAD

**Issue by gemtot** [IBM-Blockchain-Archive/marbles#76]
There does not seem to be a way to specify the CA file required for connecting to peers over TLS

**Comment by dshuffma-ibm** [comment]
version v3 will have TLS support shortly (today or tomorrow).

**Comment by gemtot** [comment]
Almost working with TLS, but failing with the TLS handshake.  Currently orderers cannot handle client certificates.  Is there a way to disable the handshake through configuration similar to the CLI CORE_PEER_GOSSIP_SKIPHANDSHAKE=true? 

```
debug: [startup] going to create marble: color=green, size=35, owner_id=o014912489668427c3pp, auth_company=United Marbles

info: Creating a marble...
debug: [fcw] Invoking Chaincode: init_marble()
debug: [fcw] Sending invoke req chainId=passkit, chaincodeId=marbles, chaincodeVersion=v3.5, fcn=init_marble, args=[m01491248972116devRF, green, 35, o014912489668427c3pp, United Marbles], txId=e0302698609e32ec3eab84ec0694f0bd5b68415d5ae2d18130d25dd1cf49718c, 0=4, 1=12, 2=64, 3=184, 4=23, 5=255, 6=84, 7=165, 8=127, 9=100, 10=43, 11=61, 12=105, 13=165, 14=78, 15=233, 16=126, 17=63, 18=126, 19=190, 20=163, 21=90, 22=1, 23=245
debug: [fcw] listening to event url grpcs://peer-us-east-2a.blockchain.passkit.com:7053
debug: [fcw] Successfully obtained transaction endorsement
debug: [fcw] Successfully obtained transaction endorsement
debug: [fcw] Successfully obtained transaction endorsement
debug: [fcw] Successfully obtained transaction endorsement
debug: [fcw] Successfully obtained transaction endorsement
debug: [fcw] Successfully obtained transaction endorsement
debug: [fcw] Successfully obtained transaction endorsement
E0403 19:49:32.787119138      48 ssl_transport_security.c:947] Handshake failed with fatal error SSL_ERROR_SSL: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed.
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Connect Failed
    at ClientDuplexStream._emitStatusIfDone (/var/hyperledger/marbles/node_modules/grpc/src/node/src/client.js:201:19)
    at ClientDuplexStream._readsDone (/var/hyperledger/marbles/node_modules/grpc/src/node/src/client.js:169:8)
    at readCallback (/var/hyperledger/marbles/node_modules/grpc/src/node/src/client.js:229:12)
```

The orderer logs the following:

`2017/04/04 04:39:32 grpc: Server.Serve failed to complete security handshake from "42.98.123.123:65123": EOF`

**Comment by dshuffma-ibm** [comment]
Are you hosting the network locally? Well, a more direct question is are you using self-signed certs?  If so we need to add another option to get TLS to work. 

```
chain.addOrderer(new Orderer(options.orderer_url, {
	pem: options.pem,
	'ssl-target-name-override': "common name that was used in pem here"
}));
```

its the ssl-target-name-override that I *think* you need. And you need that everywhere a `pem` certificate was added.

I'll push an update today for this. The tricky part is I don't want to break support for root signed certs (such as those in the Blockchain Service).  So i can't just parse the url for the hostname since the self signed cert will not always use the common name as its hostname.... I guess i'll need a new field in the blockchain_credsX.json.

**Comment by gemtot** [comment]
Yes, I am hosting remotely with self-signed certs.  I've had intermittent success with setting the hostname to match the SAN in the cert and importing the roots into the node server trust store when turning off events.  With events on, then I always get the unhandled error above.

**Comment by dshuffma-ibm** [comment]
<strike>
did you add the override to the eventhub `setPeerAddr` method too?

/utils/fc_wrangler/invoke_cc.js - line 51ish
</strike>

```js
// Setup EventHub
if (options.event_url) {
	logger.debug('[fcw] listening to event url', options.event_url);
	eventhub = new EventHub();
	eventhub.setPeerAddr(options.event_url, {
	         pem: options.pem,
		'ssl-target-name-override': options.common_name        //<--------- over here!
	});
	eventhub.connect();
```
**Edit** Oh, I misread your post.... Maybe you sent eventhub the wrong cert?

in your setup are you using different certs for orderer/peer/ca? (not a problem, i'm just curious)

**Comment by gemtot** [comment]
Certs for TLS are the same - have a server cert and a client cert which I share across all TLS connections, including Orderer<=>Kafka<=>Zookeeper. Peers use the server cert, and the MSP cert as the client.  They are all signed by the same intermediate cert and all contain wildcard SAN entries which makes things simpler.

Will try overriding the event hub method tomorrow.

**Comment by gemtot** [comment]
Similar to my experience before, I am getting intermittent failures.  Sometimes it will fail with the orderer, other times the peer, other times the endorser - mostly it works.

```debug: [fcw] listening to event url grpcs://peer-us-east-2a-example.com:7053
debug: [fcw] Successfully obtained transaction endorsement
debug: [fcw] Successfully obtained transaction endorsement
debug: [fcw] Successfully obtained transaction endorsement
debug: [fcw] Successfully obtained transaction endorsement
debug: [fcw] Successfully obtained transaction endorsement
debug: [fcw] Successfully obtained transaction endorsement
debug: [fcw] Successfully obtained transaction endorsement
debug: [fcw] Successfully obtained transaction endorsement
E0405 05:27:26.461223101      38 ssl_transport_security.c:947] Handshake failed with fatal error SSL_ERROR_SSL: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed.
events.js:160
      throw er; // Unhandled 'error' event
      ^
```
If I run with events off then it muddles through these errors, mostly catching up when new blocks are received, but occasionally dropping transactions when the failure happens at the peer.

With events on, the unhandled error crashes the app.

**Comment by dshuffma-ibm** [comment]
Oh! Hey in every PEM file (the certificate) make sure you have a blank new line at the end.  I know it sounds crazy, but try it.

The eventHub.js code in the SDK is tricky.  I can't catch those errors without resorting to catching all errors on the node process.  I'm investigating a way to do this without blinding catching everything.  That should at least keep your marbles alive through random SSL hiccups.

**Comment by gemtot** [comment]
Crazy indeed - but that seems to have stabilised it.

**Comment by dshuffma-ibm** [comment]
great
