### ISSUE TITLE
App allows double spending

### ISSUE THREAD

**Issue by gemtot** [IBM-Blockchain-Archive/marbles#79]
When transferring a marble to party b, during the transfer there can be a refresh and the marble appears back in the transferor's (a) account.  The transferor is able to then transfer the same marble to another transferee (c).

Eventually the blocks catch up and the audit will show that the marble was owned by a, then b, then c.  But it was not b that initiated the transfer to c.  Party a has essentially stolen party b's marble and given it to party c.

If using this as a demo, it creates confusion and raises challenges to the integrity of the blockchain.

**Comment by dshuffma-ibm** [comment]
Well keep in mind you are the admin for your marble company.  When you clicked the login button you logged in as `admin` not `amy` or `alice` etc.  Nobody stole a marble, b/c as the admin you have authority on all actions for your marble owners. You, as the admin, moved the marble from party a -> c.

However there is more to it than that. I suspect the "history" aka audit marbles chaincode is returning **all** transactions.  Even if they failed on the validation step. This would mean if you trade a marble a -> b and a -> c (at the same time) you will see the marble's history as containing both transactions.  But 1 was rejected. This is not obvious b/c I have no data telling me if a tx was rejected or not.  There is also a chance the fabric peer code has a bug and both tx were successful.  I hope that's not the case. We will run some tests to figure this out. Thanks for bringing this up.

**Comment by dshuffma-ibm** [comment]
I actually can't get this to happen on my version. But I know I've seen it before....  Still investigating.

Regardless the peer does invalidate transactions if they are conflicting in most cases.  Just need to find the corner case where it does not.

**Comment by gemtot** [comment]
Maybe because my network is remote and has higher latency?

Will try to post a screen flow of how I can replicate. However, now, the latest build has broken the chaincode.

**Comment by dshuffma-ibm** [comment]
i've been unable to repeat this for awhile now.  i'm going to close this since we have moved on to a new fabric build.
