### ISSUE TITLE
Can't deploy v2 to Bluemix

### ISSUE THREAD

**Issue by dklesev** [IBM-Blockchain-Archive/marbles#85]
Getting this error when trying to deploy to bluemix. Car-lease-demo works without any problems.

![deploy to bluemix](https://cloud.githubusercontent.com/assets/6021382/24874681/d6ef666a-1e25-11e7-8a80-6a69e3c75f2a.png)

**Comment by dshuffma-ibm** [comment]
Sorry about that, but that system is out of my hands. You should open a Bluemix ticket.

**Comment by DvdChavarri** [comment]
IBM BlueMix doesn´t find the master branch needed to deploy the example.

I have forked the project and merged in a master branch and works for me.
https://bluemix.net/deploy?repository=https://github.com/Twiinlab/marbles.git

I hope it helps
Cheers
