### ISSUE TITLE
Marbles on VirtualBox: localhost:3001: Name or service not known

### ISSUE THREAD

**Issue by tjdurant** [IBM-Blockchain-Archive/marbles#87]
I am trying to host marbles on a virtual CentOs machine running in VirtualBox. I am using a Host-Only network adapter which I use to ssh into the machine and run my commands through putty.

I am following the tutorial here:http://fabric-rtd.readthedocs.io/en/latest/marbles.html

I get to here:
`gulp marbles1`

and I have this output:
`    ------------------------------------------ Server Up - localhost:3001 --
    ----------------------------------------
    ------------------------------------------ Websocket Up ----------------
    --------------------------

    debug: Detected that we have NOT launched successfully yet
    debug: Open your browser to http://localhost:3001 and login as "admin" 
    to initiate startup`

At this point, I try to open http://"host-only-ip":3001 from my local machine in the browser and I get:

`<host-only-ip> took too long to respond 
Search Google for <host-only-ip> 3001
ERR_CONNECTION_TIMED_OUT`

when I ping "http://host-only-ip" from a windows terminal I get a reply, but when I do:

`ping <host-only-ip>:3001`

I get:

`Ping request could not find host <host-only-ip>:3001`

The only way that I have deviated from the Marbles tutorial is by forking and cloning my own version of the marbles repo.

I am not sure why this isn't working. Is the Node.js application running in a docker container? if so, where should I add the port-bindings?

if not: does anyone know why this isn't working?

Please let me know what additional information someone might need to troubleshoot this, or if there is a better place to post a question like this.

Thanks, T

*** Edit ***
I went back and performed all of the same steps from the Marbles tutorial using the recommended repo and I have the same errors. I also tried enabling a NAT network adapter with port forwarding.

**Comment by dshuffma-ibm** [comment]
- Marbles via those instructions is not in a docker container
- I bet if you try `http://localhost:3001` from within the virtual machine you will see the application load in your browser. give that a try
  - if it works then its some networking issue between the host and the vm.  could be a windows firewall, virtual box setting, or CentOs firewall.  You could disabled the firewalls one at a time, temporary, to figure out which one or which ones need to be tweaked.

**Comment by tjdurant** [comment]
Thank you for the clarification. I was working in CLI so I used wget which returned 200

Turned off the firewall on the VM and it worked. Thanks!
