### ISSUE TITLE
Return 404 when enrolling admin with fabric CA

### ISSUE THREAD

**Issue by linyuadam** [IBM-Blockchain-Archive/marbles#97]
<img width="1071" alt="error" src="https://cloud.githubusercontent.com/assets/20940043/25697234/c4ed94bc-30ec-11e7-9a74-c2d7adca3441.png">

**Comment by linyuadam** [comment]
I am building the app locally

**Comment by mrshah-at-work** [comment]
@linyuadam Can you please share your network id

**Comment by linyuadam** [comment]
@mrshah-at-ibm Thanks for your response. According to the doc, we just set it to anything other than `FakeNetworkId`. So I set it as "Marble_Network".

**Comment by linyuadam** [comment]
Here also attached my config file of blockchain_creds. [blockchain_creds1.json.txt](https://github.com/IBM-Blockchain/marbles/files/978164/blockchain_creds1.json.txt)

**Comment by ravengit** [comment]
I also run into the same issue. @linyuadam , are you able to resolve it and if so, how?

**Comment by hchawla1** [comment]
I was getting 400. When I use the default enrollId "admin", I am able to verify enrollemtn. But when I change enollId to "test" in blockchain-credentilas1.json file -> I am unable to enroll the admin. Until this is fixed. I did a workaround by making code changes to the getSubmitter function. This might not be the right way but right now the else part of this getSubmitter does not seem to work.

```
function getSubmitter(client, options) {
        var member;
        return client.getUserContext(enrollId, true).then((user) => {
            if (user && user.isEnrolled()) {
                console.log('Successfully loaded enrollment from persistence'); 
                return user;
            } else {
                getSubmitterWithAdminCert(client, options);
            }
});
```

**Comment by dshuffma-ibm** [comment]
closing, inactivity
