### ISSUE TITLE
Failed to obtain an enrolled user

### ISSUE THREAD

**Issue by bancey** [IBM-Blockchain-Archive/marbles#98]
Hi,

I'm hosting the chaincode in bluemix, the node app is having a problem get the enrolment for "admin".
I get the following error:
`error: Error: Calling enrollment endpoint failed with error [Error: connect ECONNREFUSED 169.50.208.49:13411]
    at ClientRequest.<anonymous> (D:\Users\abance\Documents\BlockChain\marbles-3.0\node_modules\fabric-ca-client\lib\FabricCAClientImpl.js:568:12)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1281:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
error: [fcw] Failed to get enrollment marbles-a5cc7fd2d65b4036b9c325664fc8a912-supply-chain-channel-1-fabric-peer-1a Error: Failed to obtain an enrolled user
    at ca_client.enroll.then.then.then.catch (D:\Users\abance\Documents\BlockChain\marbles-3.0\utils\fc_wrangler\enrollment.js:167:12)
    at process._tickCallback (internal/process/next_tick.js:103:7)
error: [fcw] could not format error
error: could not enroll...`

Any suggestions?

Cheers,
Alex

**Comment by habpygo** [comment]
Do you see message like the one below in the terminal window after `gulp marbles1`?
```
warn: ----------------------------------------------------------------------
warn: ----------------------------- Hey Buddy! -----------------------------
warn: ------------------------ It looks like you did -----------------------
error: ------------------------------- not  --------------------------------
warn: ------------------------- follow my instructions ---------------------
warn: ----------------------------------------------------------------------
warn: Your network config JSON has a network ID of "FakeNetworkID"...
warn: You likely have other settings that are wrong too!
warn: ----------------------------------------------------------------------
error: Fix this file: blockchain_creds1.json
warn: It must have credentials/hostnames/ports/channels/etc for YOUR network
warn: How/where would I get that info? Using the Bluemix service? Then look at these instructions(near the end):
warn:   https://github.com/IBM-Blockchain/marbles/blob/v3.0/docs/install_chaincode.md
warn: ----------------------------------------------------------------------
```
This is the case with me. Problem is that I can't get the JSON credentials following the link above, because in Bluemix I'm stuck because of an error that is still open!
[unknown error, contact support](https://developer.ibm.com/answers/questions/373603/when-i-instantiated-chaincode-there-was-an-unknown/#)

**Comment by dshuffma-ibm** [comment]
closing, inactivity
